### ISSUE TITLE
[Bug] "Invalid integer value for param Seed - must be a valid integer (eg '0', '3', '-5', etc)"

### ISSUE THREAD

**Issue by T3chRomanc3r** [Stability-AI/StableSwarmUI#10]
Bug: when using any integer for seed, getting the error "Invalid integer value for param Seed - must be a valid integer (eg '0', '3', '-5', etc)"

**Comment by xray7474** [comment]
your seed is too large for an integer value. 2147483647 is max for integer.

**Comment by mcmonkey4eva** [comment]
Oh, yep, the above reply is correct, but Torch allows uint32 seeds (ie up to double the normal max) so many generated random seeds are in that range - fixed with the commit above.
