### ISSUE TITLE
Requesting help, reporting an error

### ISSUE THREAD

**Issue by aimarxjg** [Stability-AI/StableSwarmUI#100]
Traceback (most recent call last):
10:15:39.281 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
10:15:39.282 [Warning] ComfyUI launcher:     output_data, output_ui = get_output_data(obj, input_data_all)
10:15:39.283 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
10:15:39.283 [Warning] ComfyUI launcher:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
10:15:39.284 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
10:15:39.285 [Warning] ComfyUI launcher:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
10:15:39.285 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 901, in generate
10:15:39.286 [Warning] ComfyUI launcher:     latent = torch.zeros([batch_size, 4, height // 8, width // 8])
10:15:39.287 [Warning] ComfyUI launcher: TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, but found element of type str at pos 0
10:18:33.088 [Warning] ComfyUI launcher: Traceback (most recent call last):
10:18:33.088 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
10:18:33.089 [Warning] ComfyUI launcher:     output_data, output_ui = get_output_data(obj, input_data_all)
10:18:33.090 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
10:18:33.090 [Warning] ComfyUI launcher:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
10:18:33.091 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
10:18:33.092 [Warning] ComfyUI launcher:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
10:18:33.092 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 901, in generate
10:18:33.093 [Warning] ComfyUI launcher:     latent = torch.zeros([batch_size, 4, height // 8, width // 8])
10:18:33.094 [Warning] ComfyUI launcher: TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, but found element of type str at pos 0
10:18:38.667 [Warning] ComfyUI launcher: Traceback (most recent call last):
10:18:38.668 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
10:18:38.669 [Warning] ComfyUI launcher:     output_data, output_ui = get_output_data(obj, input_data_all)
10:18:38.669 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
10:18:38.670 [Warning] ComfyUI launcher:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
10:18:38.670 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
10:18:38.671 [Warning] ComfyUI launcher:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
10:18:38.671 [Warning] ComfyUI launcher:   File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 901, in generate
10:18:38.672 [Warning] ComfyUI launcher:     latent = torch.zeros([batch_size, 4, height // 8, width // 8])
10:18:38.673 [Warning] ComfyUI launcher: TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, but found element of type str at pos 0

**Comment by mcmonkey4eva** [comment]
This appears to be a ComfyUI error?

What exactly were you doing in Swarm when this occurred? Were you using a custom comfy workflow, or the default Generate tab (ie autogenerated workflows)? What were your parameter(s)?
A screenshot of the UI when the error occurs would probably suffice to answer all of the important questions
