### ISSUE TITLE
How to Swarm?

### ISSUE THREAD

**Issue by markrmiller** [Stability-AI/StableSwarmUI#101]
Is there a trick to make this thing swarm?

I've got a StableSwarmUI on one machine, and a ComfyUI on another machine.

I'm using the batch image folder tool.

Both backends are up and happy.

If I kick off the job, everything goes to the local node, GPU is at 0% on the remote ComfyUI node.

If I disable the local backend, everything goes to the remote ComfyUI node. If I disable the remote node and enable the local mode, everything back to local.

Enable both, everything to the local node.

Uh...I have failover I guess! Now how do I swarm and use both of these nodes at the same time?!

**Comment by mcmonkey4eva** [comment]
I, uh, oops. Forgot to use the line of code that makes it, yknow, do the important part. Fixed! Sorry!

**Comment by zhenlyzheng** [comment]
i have no idea where can i install the customer's nodes?  who can tell me the way can solve this issue?i have downloaded the workflow, and loaded in  swarm,nodes i don't down are red. barely  all of red nodes are red.

**Comment by mcmonkey4eva** [comment]
Please open your own issue or ask on the discord  https://discord.gg/q2y38cqjNw  rather than reusing this old unrelated thread
