### ISSUE TITLE
Error Config UI

### ISSUE THREAD

**Issue by Matizack** [Stability-AI/StableSwarmUI#102]
![Screen Shot 2023-09-13 at 11 51 25 PM](https://github.com/Stability-AI/StableSwarmUI/assets/83611699/913c7d9c-01ee-4aec-9e91-55bc6b756de3)

**Comment by mcmonkey4eva** [comment]
First of all... please set your terminal background to black, that hurts to look at.

Second: as the message says:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/57ff4e5b-4d62-4b16-8648-117a582ceb56)
set LogLevel in settings to debug and try again - it should show full debug logs for comfy which will hopefully clarify what went wrong
