### ISSUE TITLE
Help with Backend please.

### ISSUE THREAD

**Issue by BotLifeGamer** [Stability-AI/StableSwarmUI#105]
Can someone please explain how to get a backend working. I have multiple gpu's but it says you need to add backends when I try it gives error.

[Init] Initializing backend #3 - Swarm-API-Backend...
15:37:34.369 [Error] Final error (8) while initializing backend #3 - Swarm-API-Backend, giving up: Connection refused - is the backend running, or is the address correct? (HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:7802))

**Comment by mcmonkey4eva** [comment]
You definitely shouldn't have a swarm-api-backend on localhost, ever.

Generally the standard backend to use is ComfyUI Self-Start.

**Comment by BotLifeGamer** [comment]
The git says you need to make a backend. I Have 2 comfy self-starts one with gpu id 0 and the other with gpu id 1 but that doesn't do anything.

**Comment by mcmonkey4eva** [comment]
You don't need to manually make a backend, there's an option to automatically install and configure one for you during the installation menu. If you're lost and mixed up config, just delete the swarm folder and redo the installer

**Comment by BotLifeGamer** [comment]
> Can someone please explain how to get a backend working. I have multiple gpu's but it says you need to add backends when I try it gives error.
> 
> [Init] Initializing backend #3 - Swarm-API-Backend... 15:37:34.369 [Error] Final error (8) while initializing backend #3 - Swarm-API-Backend, giving up: Connection refused - is the backend running, or is the address correct? (HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:7802))

I got it working now thanks for the replies. I had to enabled Comfyui sampler and Scheduler and it worked great. I can create 2 1024x1024 images at once now which is good. That was my misunderstanding cause I thought it worked on one image at a time. So now I can create 2 images off one prompt at the speed it would take to use 1 gpu to create 1 image.
