### ISSUE TITLE
Browser output files on MacOS

### ISSUE THREAD

**Issue by kltdwrds** [Stability-AI/StableSwarmUI#108]
Is the local dotnet server's `/Output/raw/` folder mountable / available in MacOS Finder?

Would love to browse the generated files via Finder + sync folder to cloud while in "Generate Forever" mode.

cheers!

**Comment by mcmonkey4eva** [comment]
Yes, it's a standard file system folder. You can also change it to any path you'd like under Server -> Server Configuration (eg if you have a synced images folder already, you can replace the output path to go straight there).

**Comment by kltdwrds** [comment]
Gotcha!  I don't see `Output/raw` anywhere in the file system -- any idea where it would live?

I'm using `./launch-macos.sh` to launch, and i've looked closely in `StableSwarmUI` folder.  Native Finder search also returns nothing.

**Comment by mcmonkey4eva** [comment]
the Output folder is inside the swarm folder

**Comment by kltdwrds** [comment]
Not for me -- I've only a `Data` folder.

I definitely have "save images" enabled, and I can the images them across different `./launch-macos.sh` runs.  

<img width="1418" alt="Screenshot 2023-09-20 at 2 32 01 PM" src="https://github.com/Stability-AI/StableSwarmUI/assets/5615037/408621b5-96cc-43d8-9c3b-9841875d8c25">
<img width="1407" alt="Screenshot 2023-09-20 at 2 31 48 PM" src="https://github.com/Stability-AI/StableSwarmUI/assets/5615037/d8ff6692-5716-457a-8650-659364b28a69">
<img width="783" alt="Screenshot 2023-09-20 at 2 29 12 PM" src="https://github.com/Stability-AI/StableSwarmUI/assets/5615037/31afca43-6ca0-4fc0-b852-ba103ad00d28">
<img width="489" alt="Screenshot 2023-09-20 at 2 32 40 PM" src="https://github.com/Stability-AI/StableSwarmUI/assets/5615037/0012bca2-8e78-495d-a3fb-f440337d33fd">

**Comment by mcmonkey4eva** [comment]
This would seem to imply that you've modified your output dir in server settings?

**Comment by mcmonkey4eva** [comment]
Or that you haven't been generating images in swarm yet

**Comment by kltdwrds** [comment]
> This would seem to imply that you've modified your output dir in server settings?
I did not modify -- I'm using the fresh install default of `/Output/raw/*`

> Or that you haven't been generating images in swarm yet
I've generated 100s of images i would like to access in Finder and sync to the cloud -- they are defintiely being persisted _somewhere_ because I can access them in SwarmUI across sessions, run with `./launch-macos.sh`

Any other ideas?  I'm a full-stack engineer and would be happy to help debug / submit a PR if you have any leads, i'm mainly versed in python/node/web apps...can't say i've ever seen a native `dotnet` server running on Mac haha

**Comment by mcmonkey4eva** [comment]
I'm not really sure what to tell you tbh? It's something either (A) related to your setup or (B) very specific to Mac (ie mac somehow inexplicably redirecting that one folder in particular but not others? 0.o)

On Windows and Linux in standard installs it's literally just right there in the main folder between the others
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/4bdd3286-1ad9-4229-9da3-ec4bd9ca279a)
