### ISSUE TITLE
extra_model_paths.yaml doesn't seem to work

### ISSUE THREAD

**Issue by PineKia** [Stability-AI/StableSwarmUI#109]
Hi,

I have successfully got a stand alone install of comfyUI to pick up the paths to my Automatic 1111 models folder.  But when I use SwarmUI and place the same yaml from my ComfyUI install to the location where this file is in SwarmUI:

\SwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\extra_model_paths.yaml

It does not load the models from the paths inside the yaml file

**Comment by mcmonkey4eva** [comment]
You need to configure model paths for swarm in the GUI, under Server -> Server Configuration.
This will automatically propagate the settings to all backends (or at least after restarting swarm it will)
