### ISSUE TITLE
Using StableSwarmUI on Windows with ComfyUI on Linux breaks when models are nested in directories

### ISSUE THREAD

**Issue by arathald** [Stability-AI/StableSwarmUI#112]
ComfyUI is failing with this error when it's running on Linux and gets a request from StableSwarmUI on Windows. These machines have a common model mapping (Comfy is running on WSL2, the reason StableSwarmUI is still on Windows native may be a bug report for later 😄). I believe the root cause is that Stable is sending a path with a backslash (`\`) character in it, which Comfy on a posix system treats as invalid. Because both Windows and *nix systems tolerate forward slashes (`/`) as path separators, it seems like file paths should always be normalized to forward slashes when they're sent to another machine.

(This isn't blocking me, it was easy enough to hack a fix into the Comfy node)

```got prompt
Failed to validate prompt for output 9:
* CheckpointLoaderSimple 4:
  - Value not in list: ckpt_name: 'SDXL\copaxVividXL_v2.safetensors' not in (list of length 65)
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}```

**Comment by mcmonkey4eva** [comment]
`it seems like file paths should always be normalized to forward slashes when they're sent to another machine.` i firmly agree - tell comfy that, it's comfyui that's sensitive to slash format, not swarm.
In fact if you install swarm on the relevant OS and like it with Swarm-API-Backend, it will always autoconvert slashes locally.

The ComfyUI backend in Swarm will do its best to convert to the format seen on the remote system, by checking the Comfy API for slashes when it loads and using whichever slash format it sees. If you didn't have foldered models when you launched and added them later, it might break, but a restart should fix that.
If that's not the case you might just need to update Swarm?

**Comment by arathald** [comment]
This does appear to be resolved after a couple of restarts of both servers, but I've had the same set of models for a couple of weeks and folders for over a month, so nothing is new in that regard. Is the format prediction you mention cached in any way? I may have confused it by a backend at the same address changing formats. 

> tell comfy that, it's comfyui that's sensitive to slash format, not swarm.
I might agree with you if the call got to their filesystem layer, but you passed an invalid option into their web APIs and failed validation still in the UI layer: they provide a list of models to choose from and you injected something not on their list. To the extent that there's any kind of API contract between you, StableSwarmUI definitely appears to be the one who violated it.

That said, my original suggestion wouldn't work either for enumerated inputs, but it does seem reasonable to check to make sure you're not passing in something you know the backend server won't consider valid (and in a case like this, it would be trivial to massage the path into the format the backend wants, with no guessing required).

**Comment by arathald** [comment]
I spent a little more time looking into the path handling code in StableSwarmUI, and I agree it *should* get the correct path on restart, though last night StableSwarmUI was stubbornly hanging on to linux style path separators across several restarts when I switched ComfyUI back to windows for a benchmark, and I ended up having to hack in the reverse of my previous patch in ComfyUI. I added the code I discussed above and some extra logging to my local copy. 

I do think there's some bug here, or else an opportunity to be much less fragile, but it looks like my approach is failing in the same way: when the model list from the server isn't loaded properly for whatever reason. I'll send along more information if I see a repro or a PR if I want to help make things a little more robust here (though I have way more interesting projects to work on both inside and outside StabilityUI 😄).

I know the whole codebase is a bit rough in places right now and my weird OS-switching corner case isn't a high priority, but it's coming along super well, keep up the great work and thanks for your contributions to the community!

**Comment by mcmonkey4eva** [comment]
`I might agree with you if the call got to their filesystem layer,` ... You might agree... with yourself? What?

Swarm by default always sends in `/` but will switch to `\` if it detects that comfy is using `\`, because comfy errors out if it expects `\` and receives a `/`.

I added a debug log, so if you set LogLevel in Server Config to Debug, it will output in console (among many other bits of debug) a line like `Comfy model folder format: \ ... forward slash: 0 (), back slash: 71 (OfficialStableDiffusion\sd_xl_base_1.0.safetensors, OfficialStableDiffusion\sd_xl_refiner_1.0.safetensors, OfficialStableDiffusion\v1-5-pruned-emaonly.safetensors)`

If all goes well, on Linux you should see only entries under 'forward slash' and none under back slash, and on Windows none for forward and a lot for back.

If the debug is correct, but there's model name errors still - then there might be code somewhere that's missing the format application.

If the debug shows 0 & 0, there might be an issue in comfy with loading models?

If the debug has a positive number in both, then... well I have many many questions, but we can start with posting the debug and explaining the setup and we can think about it from there.

**Comment by arathald** [comment]
No, agree with it being an issue on ComfyUI's side (maybe the quote didn't show up for you?). I had to do some gymnastics with their code to make it work, but like I said, I think this is a pretty extreme corner case.

... That's a really good question, a single forward slash would trigger all-forward slash. alas, though 
```
# running on windows
22:49:43.037 [Debug] Comfy model folder format: \ ... forward slash: 0 (), back slash: 65 ( ... )

# running on linux
23:13:37.212 [Debug] Comfy model folder format: / ... forward slash: 65 ( ... ), back slash: 0 ()
```
I'll leave it in debug mode so I can catch what's going on if this happens again, but seeing as I'm getting ~10% better performance on WSL, I probably won't run across this again, at least not until dynamo works on windows or I move to another framework.  Appreciate the time!
