### ISSUE TITLE
Backend does not save

### ISSUE THREAD

**Issue by JanJanJAnJanJanJanJanJanJanJanJanJan** [Stability-AI/StableSwarmUI#113]
As the title suggests, whenever i restart my SwarmUI, i get prompted with entering a backend because there isnt one. I tried reinstalling but i doesnt seem to work. Everytime i close the console and according tab it prompts me again. 
<img width="1728" alt="Bildschirmfoto 2023-09-23 um 00 05 30" src="https://github.com/Stability-AI/StableSwarmUI/assets/138667368/19b43f7e-5ba0-4d3b-8e10-2a27c3218a8a">

**Comment by mcmonkey4eva** [comment]
In what way are you closing swarm? The proper method is to hit CTRL+C in the terminal window. If you click the `X` on the console window that should work too, but a couple people have had weird things happen when they do that.

Could you please
- Open a terminal in the swarm folder
- Launch swarm via terminal
- open the page, configure and save a backend
- close swarm (CTRL+C)
- Post the full logs from start to end of the run here

**Comment by JanJanJAnJanJanJanJanJanJanJanJanJan** [comment]
I used to close it via the X. Now i did as requested:
<img width="1192" alt="Bildschirmfoto 2023-09-24 um 15 57 57" src="https://github.com/Stability-AI/StableSwarmUI/assets/138667368/2dcca4d0-ca50-4f00-8dd1-8f11abb34ece">

The only error left now is this:
<img width="332" alt="Bildschirmfoto 2023-09-24 um 16 02 02" src="https://github.com/Stability-AI/StableSwarmUI/assets/138667368/74ee1b27-2679-4a79-9bc2-05d86c48b625">

**Comment by mcmonkey4eva** [comment]
oo, you're on a mac, yeah that's probably why the terminal closing is different.

Model not found probably means you moved models around while testing or something? not sure, usually ignorable on its own unless there's anything actually misbehaving from it.

**Comment by londonlost** [comment]
This is happenign to mine as well, also on mac
