### ISSUE TITLE
The comfyUI translation plugin cannot be applied in stableswarmUI |  关于 comfyUI翻译插件无法应用在stableswarmUI

### ISSUE THREAD

**Issue by bubbl000** [Stability-AI/StableSwarmUI#117]
https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation 
我在comfyUI中安装了这个插件，单独运行时是可以翻译的
**I installed this plugin in comfyUI and it translates when run alone**
![image](https://github.com/Stability-AI/StableSwarmUI/assets/108770692/aef84ec4-4878-490a-a678-232611b9936a)
如果是用stableswarmUI则无法应用该插件（软件功能可以正常运行但是无法翻译）
**If you are using stableswarmUI, the plugin cannot be applied (the software functions work properly but cannot be translated)**
![image](https://github.com/Stability-AI/StableSwarmUI/assets/108770692/3c05b96a-08a8-4c58-84f8-4a8e16a2c21f)
我需要用网页插件才能翻译该软件很麻烦，有什么办法可以让comfyUI的插件应用到stableswarmUI
**I need to use the web plugin to translate the software is very troublesome, is there any way to apply the comfyUI plugin to stableswarmUI**

**Comment by bubbl000** [comment]
The plug-in cannot be installed through ComfyUI Manager

**Comment by hben35096** [comment]
Same problem

**Comment by mcmonkey4eva** [comment]
I created a PR @ https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/pull/89 that fixes this

**Comment by KarryCharon** [comment]
@mcmonkey4eva Merged, thanks!
