### ISSUE TITLE
Question: launch in different browser

### ISSUE THREAD

**Issue by drago87** [Stability-AI/StableSwarmUI#119]
How can i make StableSwarmUI use a different browser then the usual one for windows.
Or how do i prevent it from starting the browser in the first place.

**Comment by arafatx** [comment]
To prevent browser starting go to:

`Server->Server Configuration -> LaunchMode -> None`

<img width="419" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/4420157/0ba12230-f550-4e11-995b-ff3d8cf24ca3">


If you are looking to change different browser, you can change this code:

`https://github.com/Stability-AI/StableSwarmUI/blob/master/src/Core/Program.cs`

Look at the line `160`

Or I think it's better to run it on `Electron.NET` that might be implemented later.

**Comment by mcmonkey4eva** [comment]
Yeah ^ just changing LaunchMode in server config is best.

the `electron` placeholder is indeed there as I intend to implement Electron.NET - I took a crack at it earlier but it had a lot of unexpected complications that I didn't have time to try to figure out.
(Which, yknow, if anyone out there has experience in electron.net and wants to make a PR that would be extremely welcome!)

**Comment by drago87** [comment]
ty for the help

**Comment by drago87** [comment]
ty
