### ISSUE TITLE
Syntax issues with prompt in v0.5.6

### ISSUE THREAD

**Issue by suede299** [Stability-AI/StableSwarmUI#123]
“added initial experimental regional prompting support (ComfyUI only), works with an initial dirty/simple syntax in the prompt like a photo of a catdog <region:0,0,1,0.5> a photo of a cat <region:0,0.5,1,0.5> a photo of a dog"
Does CLIPTextEncode in comfyui support this syntax originally? Where can I see a list of all available syntaxes? Like the one mentioned here, it's not even mentioned on comfyui's github readme page.

**Comment by mcmonkey4eva** [comment]
This is not a comfy feature, it's a Swarm feature - a list of related syntax features is here https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Basic%20Usage.md#more-than-text-playing-with-prompts
do note it's brand new / experimental
