### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Ramam001** [Stability-AI/StableSwarmUI#125]
Make readme simple and more detailed, make sure to add comfyui usage in your readme please
It's not easy for noobs, provide a video if possible,

I've 4gv vram laptop will it work on it?

**Comment by mcmonkey4eva** [comment]
ComfyUI usage is outside the scope of the readme - it's used in swarm as a backend, but that installs itself, and using the UI half of it isn't necessary to use swarm (swarm has a much friendlier UI), and is better documented elsewhere anyway.

All you gotta do is follow https://github.com/Stability-AI/StableSwarmUI#installing-on-windows and install it and click the obvious options that tell you to click them and it will install itself, load itself, download models itself, etc. as long as you checkmark to allow it to do those things as it goes. Then once you have the main UI open... select a model at the bottom, type a prompt in the middle, hit enter, enjoy.



re 4GiB VRAM laptop: it depends on the laptop tbh? Some small-but-modern nvidia cards should be fine. Outdated cards or AMD will probably not go well. You can technically run SD on CPU but it is very very slow.
