### ISSUE TITLE
ComfyUI workflows do not seem to be influenced in generate tab

### ISSUE THREAD

**Issue by LargoUsagi** [Stability-AI/StableSwarmUI#126]
Primitive input fields do not seem to be impacting the ComfyUI custom workflows.

Changing any value that is not in the advanced options has no impact on generation.

It would also be nice if there was a generally way to use the `SwarmUI:` prefix or other naming conventions to show and hide primitives that are not intended to be tuned.

**Comment by mcmonkey4eva** [comment]
Oh, yikes, that's a bad one - a recent commit accidentally caused the primitive inputs to all get ignored. Fixed!

**Comment by mcmonkey4eva** [comment]
Re primitive show/hide - Bit confused why you have primitives that aren't meant to be tweaked? My theory for the separation is primitives are generally things separated for tweaking, and regular node inputs are more generally hidden.

If you have a case where that theory doesn't hold, please post a separate issue to track it (and post what you're doing that needs the unique handling)

**Comment by LargoUsagi** [comment]
So I have created a few workflows where I would want to ensure a large number of things use a constant, and those are kept in sync, I may want to tune them at some point, but for general use of the workflow they will rarely if ever change.

IE image to image upscaling, 1x output is 30 seconds, 2x 2-3 minutes, 4x can take a half hour, the 1x refined SDXL output may be something I want to keep, but not have the slider front and center, I can always go into the advanced tab and tweak it there.

I was looking at this UI as a way to expose some workflows on my LAN to people who may not be as familiar with what each of those sliders do and seeing a scale slider set to 2x and going more is better and cranking it to max and then wondering why the image never comes out.  Beats the hell out of making a SPA and simple backend to pass calls to ComfyUI's API.

![image](https://github.com/Stability-AI/StableSwarmUI/assets/2375152/c345d08b-6646-4b6e-8d4f-ef42f4cd7cf4)

I would like to move those to the advanced section to allow for a cleaner UX.

**Comment by mcmonkey4eva** [comment]
That makes a lot of sense actually -- could you please post a new issue to track that?

**Comment by LargoUsagi** [comment]
It has been done.  Thanks for all of the effort here, this is really a great tool and as an abstraction layer to the workflows in comfy and the models directly I can see how valuable this is going to be.  Just wait for some one to ask for a way to hook this into jupyter notebooks to execute those like the comfy workflows. 😄 

Is there a contribution guide to read for this, I could probably take a crack at implementing a bit of what I asked for in the issue tracker.

**Comment by mcmonkey4eva** [comment]
contribution guide is basically a placeholder atm, but - just write PRs, make sure they match up to an issue that's already been posted, try your best to match existing code formatting/style, and don't be afraid to ask when you're unsure the best way to do something (either here on github or on the discord)
