### ISSUE TITLE
Allow for hiding controls from ComfyUI Workflow

### ISSUE THREAD

**Issue by LargoUsagi** [Stability-AI/StableSwarmUI#127]
The current behavior of presenting all nodes and primitives in the UI is fast and useful but being able to select a ComfyUI workflow and have specific things not show up as tunable input would be useful for presenting workflows to untrained end users.

I have multiple primitives in my workflows for things that need to be kept in sync and would all need updating at the same time from the development of the workflow, such as scaling factors or multiples for upscaling.

The current solutions I can propose would be:

- Only show components on the UI with a `SwarmUI:` prefix and filter out the "SwarmUI:" from the input section.
- Continue with current behavior and add a `SwarmHidden:` prefix to hide input that is used for non user tunable
- Building on the first suggestion have the `SwarmUI:` prefix present in the normal input section and add a `SwarmAdvanced:` prefix for exposing to the advanced section to allow a better UX for general and power users.  The advantage of this compared to the prior two suggestions is now all items in the list are opted into, and you can expose specific fields in any control as an "advanced" option and any field as a general option.

**Comment by mcmonkey4eva** [comment]
The new `SwarmInput` nodes are perfect for this
