### ISSUE TITLE
Add UI Syntax for clamping int and float parameters

### ISSUE THREAD

**Issue by LargoUsagi** [Stability-AI/StableSwarmUI#128]
Adding syntax to the prefixes that would allow for clamping the range of the number inputs to the end user would be useful due to some parameters having valid ranges that an end user may not know or may not be useful such as config strength over a certain point, or how high of a image to image upscale percentage you may want to allow.

**Comment by mcmonkey4eva** [comment]
The relevant plan here is I'd like to add a configuration UI for reusable comfy workflows so you can configure values in a more advanced way than just primitive titles - range limits would definitely be a part of this menu

**Comment by mcmonkey4eva** [comment]
This is covered now by the new (still in dev but functional) "SwarmInput" nodes system, which allows you to fully define custom swarm input parameters in a comfy workflow.
