### ISSUE TITLE
Allow for prompt syntax with comfyUI prompt and string input's

### ISSUE THREAD

**Issue by LargoUsagi** [Stability-AI/StableSwarmUI#129]
The syntax described here https://github.com/Stability-AI/StableSwarmUI/discussions/11#discussioncomment-7057501 would be useful on the comfy workflow prompt input as it would allow for large batch generation across a farm of GPU's on a specific range of desired outputs and having each generated image have its associated metadata properly embedded into the image.

For example I have been building a complex workflow to generate consistent art and style for TTRPG games and it would be nice to fire off that workflow with a prompt like this

```
<random: young, adult, old, mature, ancient> <random: male, female> <random: elf, half-elf, human, dwarve, gnome, halfling, half-orc> <random: fighter, wizard, sorcerer, alchemist, villager, ranger, hunter, druid, warrior, witch, artificer, rouge, paladin, barbarian, monk, cleric, warlock> standing in <random: medieval market, castle, town square, alley, meadow, forest, jungle, tundra> during the <random: morning, day, evening, night>
```

And then look at each output image and see a prompt like
```
adult male elf druid standing in town square during the evening
```
With the rest of the metadata including the workflow and the other tunables.

**Comment by mcmonkey4eva** [comment]
I believe `<random:>` should work even when using a custom comfy workflow (as long as you have the main Prompt input linked right and you're on the generate tab)

**Comment by LargoUsagi** [comment]
I will test again but I do not believe it was working

**Comment by LargoUsagi** [comment]
You are correct I must have made a typo when I tried this earlier, but it would be great to add the imputed prompt to the metadata so I could go to the workflow and leverage that as a starting point in the future.

![image](https://github.com/Stability-AI/StableSwarmUI/assets/2375152/a29bdff6-256c-4b74-afaf-ba7f79fd4eec)

Currently it only has the string literal entered into the generate prompt that is connected to the workflow.

**Comment by mcmonkey4eva** [comment]
It has both prompts visible in your screenshot there?

**Comment by LargoUsagi** [comment]
Well this is proof I need to sleep. I am going to close this.  Sorry for the noise.

**Comment by mcmonkey4eva** [comment]
lol, no worries
