### ISSUE TITLE
Expanding settings toggles them on

### ISSUE THREAD

**Issue by Dream-Cypher** [Stability-AI/StableSwarmUI#131]
Hello,
I have noticed that if I expand a setting in the ui (such as "Variation Seed" or "Refiner", the setting is enabled, even if I have not set any values.  This causes an error with some settings that are not yet implemented, If I forget to turn them off (Scorers, for example).

Would it be possible to not have them auto-enable when just exanding them, but require actually activating the toggle?  Or maybe there is an option I'm just missing.

Thanks

**Comment by beltonk** [comment]
+1

This is something I find bit annoying and difficult to undo.
I'm always itchy to expand and take a look what's inside a section, to make sure there is nothing I want to touch, then I collapse them, not realizing some of the features are toggled on automatically.

Possible to decouple expand/collapse and enable/disable toggle? Or put it as an option?

**Comment by mcmonkey4eva** [comment]
I've been unsure about how to make the UX for this quite right - minimal clicks to handle things while still being clear in behavior.

I've at this point just given up and gone ahead and disentangled them - it's now two separate controls.
Also if you have a closed-but-enabled group there's an extra bit of highlight to draw attention if you go looking for what's been accidentally activated.
