### ISSUE TITLE
Swarm-API-Backend Error: No images were generated (all refused, or failed).

### ISSUE THREAD

**Issue by LargoUsagi** [Stability-AI/StableSwarmUI#132]
Configuring another swarm install on a remote computer on the same network I can connect and have a remote backend show as available, but I cannot submit any comfyui workflow jobs to it.

![image](https://github.com/Stability-AI/StableSwarmUI/assets/2375152/49423b65-1ef4-464a-b8d2-81dbe20121c3)

**Comment by LargoUsagi** [comment]
It does appear that I can submit requests for regular generation, the comfyui does not seem to work directly either.

**Comment by mcmonkey4eva** [comment]
Check the logs on the remote Swarm instance

Also make sure both swarm copies are up-to-date
