### ISSUE TITLE
Intall page blank

### ISSUE THREAD

**Issue by marcuskaufmann** [Stability-AI/StableSwarmUI#134]
I followed Linux instructions and am stuck at the install page since its blank

**Comment by mcmonkey4eva** [comment]
Bit lacking in information to diagnose this-

What does the console window show?
When you say "blank" do you mean it doesn't load? Or...?
What browser are you using, what Linux distro, ...?

**Comment by marcuskaufmann** [comment]
Oops. This bug can be closed. For some copy & paste reason the directories name became ''$'\n''StableSwarmUI' which wasn't obvious visible to me but caused the problem.
