### ISSUE TITLE
When queuing generations across multiple models, generate them in order of model.

### ISSUE THREAD

**Issue by ataylorm** [Stability-AI/StableSwarmUI#137]
Let's say that I want to generate 10 images with a prompt in 5 different models.  It will generate 1, switch model, generate, switch model, etc.  This is very inefficient.  It would be much better to generate all 10 on a model, then switch the model and generate all queued for that model, etc.  This reduces model loading time significantly.

**Comment by mcmonkey4eva** [comment]
Can you specify more about the context of what you're doing here? Is this using the Grid Generator, or API, or rapidly sending gens manually, or...?

**Comment by mcmonkey4eva** [comment]
If you meant GridGen usage, the way to do that is just order things correctly to avoid that - the above commit ^ completes something that's been on the todolist a while anyway, automatic reordering (it will know to process the model axis last - and has a heuristic tracker for most relevant parameters eg lora/vae/etc)

**Comment by ataylorm** [comment]
This will be great for Grid's.  Would be nice if it did it on regular generates as well.  So let's say I have a prompt and I want to get 10 images from 3 models, I queue them up one after the other.  It would be nice if it did them in the order I queue, but instead it does one from this model, then changes model and does one, then changes model and does one.  This adds a lot of processing time.

**Comment by mcmonkey4eva** [comment]
If you queue generations manually it is heavily biased to maintain the order you used, and secondarily biased towards avoiding model changes if it can. What you're describing is the opposite of how it's intended to work.

I did a quick test in my local copy to make sure - I queued 5x `a cat` on SDXL base, then 5x on SDv1, then 5x on a random community model, all in quick succession.
It generated in exactly the order I gave.

If you're getting different results, please explain your setup / what exactly you're doing to get the counterproductive ordering.
