### ISSUE TITLE
SD Prompt Reader Node not working

### ISSUE THREAD

**Issue by drago87** [Stability-AI/StableSwarmUI#139]
[SD Prompt Reader Node](https://github.com/receyuki/comfyui-prompt-reader-node#sd-prompt-reader-node)
I have only tried the SD Parameter Generator node and it gives this error on the swarm backend

```
[Error] invalid/empty output data from ComfyUI server: {
    "text": [ "custom", "SDv2 768px", 512, 768, 15, 0.8, 12, 3 ]
}
```
i am using this workflow
[9-16.json](https://github.com/Stability-AI/StableSwarmUI/files/13198516/9-16.json)
and it is not generating eny images

**Comment by mcmonkey4eva** [comment]
Opened a PR that fixes it: https://github.com/receyuki/comfyui-prompt-reader-node/pull/12

**Comment by mcmonkey4eva** [comment]
That PR was pulled so once you update that extension you should be good to go
