### ISSUE TITLE
No shorcut

### ISSUE THREAD

**Issue by OtakuFra** [Stability-AI/StableSwarmUI#141]
Hi guys, thank you for this tool, i love it
As i've mentionned it in the tittle there's no shorcut and clicking on make-shorcut.bat doesn't work neither.

**Comment by mcmonkey4eva** [comment]
Are you on windows? (That only works on windows, not linux/mac)

Do you maybe have an unusual Desktop folder? That saves the shortcut to `%userprofile%\Desktop\StableSwarmUI.url`, so if you eg have OneDrive replacing your desktop that might cause it to go missing (in which case you may have to copy the shortcut from that directory to the hacked one)

**Comment by OtakuFra** [comment]
Hi, sorry for the delay, yes, I'm on window 11, and I've installed swarmUi on my second hard drive. There's no shortcut in desktop folder, one drive or any other.

**Comment by mcmonkey4eva** [comment]
You've checked specifically the path `%userprofile%\Desktop`? (You can copypaste that exactly into file explorer's address bar and hit enter)

for the record you can always create one manually by right clicking on the `launch-windows.bat` file and clicking "Create Shortcut" in the file menu
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/d04cd0a7-6172-47ef-a4bf-c05a34b5adc2)
