### ISSUE TITLE
DotNet SDK is required also for Windows OS

### ISSUE THREAD

**Issue by Harvester62** [Stability-AI/StableSwarmUI#142]
While installing StableSwarmUI on my laptop running Windows 10 Pro 64bit, I realized that one component was missing and reading the error messages in the console and the documentation in this repository, I understood that I did also need to install DotNET SDK 7. In fact, after doing it the installation started properly.

I would recommend to add this requirement to the Windows installation instruction. Thank you.

**Comment by mcmonkey4eva** [comment]
The `install-windows` file in the readme automatically installs dotnet for you (using `winget`, which windows autoinstalls on both Windows 10 and 11 as long as you haven't blocked windows updates)
