### ISSUE TITLE
License

### ISSUE THREAD

**Issue by green-anger** [Stability-AI/StableSwarmUI#143]
This is very likely a silly question with an obvious answer, but I'd like to clarify it nevertheless.

Does the non-commercial license apply only to the software itself? Does it mean all outputs (generated images) are sole property of the person/company using the software?

**Comment by mcmonkey4eva** [comment]
Correct on both counts, yes.

The software license is for the software only, does not affect your output images. (It also is likely to change once Swarm is out of alpha, probably to MIT or something).

Any models you use are subject to whichever license the models have.
Your images are your own (though be careful what you use if you're trying for commercial usage - eg a model trained on Disney's style is naturally not a good idea to use in a commercial setting).
