### ISSUE TITLE
Add manual installation instructions for Windows

### ISSUE THREAD

**Issue by green-anger** [Stability-AI/StableSwarmUI#147]
Currently there's only install script available [in here](https://github.com/Stability-AI/StableSwarmUI#installing-on-windows).

Since all image generation software uses Python, I usually create a separate conda env for each and download and setup everything manually to have better control over the process. I'd like to do the same with Swarm.

I followed the script, but there are still pieces of the puzzle I cannot find where to fit in.

**install-windows.bat**

```bat
winget install Microsoft.DotNet.SDK.7 --accept-source-agreements --accept-package-agreements
```
Installed it from [here](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)

```bat
winget install --id Git.Git -e --source winget --accept-source-agreements --accept-package-agreements
```
I assume it's standard git, it was installed from [here](https://git-scm.com/download/win) long time ago.

```bat
git clone https://github.com/Stability-AI/StableSwarmUI
cd StableSwarmUI
```
Done

```bat
.\make-shortcut.bat
```
One of the reasons why I don't like automated scripts, more often than not it has something I don't need - skipped.

```bat
.\launch-windows.bat --launch_mode webinstall
```
Let's see what's inside.

**launch-windows.bat**

```bat
rem Microsoft borked the dotnet installer/path handler, so force x64 to be read first
set PATH=C:\Program Files\dotnet;%PATH%
```
Can we do this manually once? AFAIK Windows adds new paths to the end of the PATH env variable.

```bat
rem For some reason Microsoft's nonsense is missing the official nuget source? So forcibly add that to be safe.
dotnet nuget add source https://api.nuget.org/v3/index.json --name "NuGet official package source"
```
Can this also be done only once from the terminal?

```bat
rem Building first is more reliable than running directly from src
dotnet build src/StableSwarmUI.csproj --configuration Release -o src/bin/live_release
```
Build every time in the launch script? I have never worked with C#, but I assume it'll be skipped if nothing has changed. Can it be done once manually after every code update?

```bat
rem Default env configuration, gets overwritten by the C# code's settings handler
set ASPNETCORE_ENVIRONMENT="Production"
set ASPNETCORE_URLS="http://*:7801"
```
Are these some standard C# variables? Can it be changed to something custom in the code so that it didn't get overwritten every time? At the worst I assume these lines can be added to a custom launcher.

```bat
dotnet src\bin\live_release\StableSwarmUI.dll %*
```
Couldn't find the official MS docs, but found [here](https://stackoverflow.com/a/19913062) that _%*_ propagates the launcher parameters which presumably converts it to

```bat
dotnet src\bin\live_release\StableSwarmUI.dll --launch_mode webinstall
```
Again, I have zero experience in C#, this just looks weird without an executable and with a single dll. Apparently it is what it is, no need to dive deep into this.

❗ **Important**

I'd like to use a pre-installed Comfy portable version, one of the assets taken from [here](https://github.com/comfyanonymous/ComfyUI/releases). Is it possible? What extra steps should be taken to make Swarm work with it?

**Comment by mcmonkey4eva** [comment]
ngl you're overcomplicating needlessly. You're spending a massive amount of thought and effort towards what could've been just... download and run the thing. And delete the desktop shortcut file you don't want.

The default comfy install uses a local conda. If you don't want it, just don't select to not install comfy during the install, and then once you get to the main interface, go to Server -> Backends and add a ComfyUI Self Starting with the path to your pre-existing install.

Some of the command line settings are redundant, yes, but there's no side effects from doing them -- the env vars and all are naturally local to the script, the build call takes a couple seconds. The dll is just slightly more convenient to use than exporting to .exe.

**Comment by green-anger** [comment]
`you're overcomplicating needlessly`

How exactly? I'm used to installing this kind of s/w manually, as mentioned I need more control over the process. All other popular image generation s/w provide such instructions:
- [a1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-NVidia-GPUs#manual-installation)
- [InvokeAI](https://github.com/invoke-ai/InvokeAI#command-line-installation-for-developers-and-users-familiar-with-terminals)
- [Comfy](https://github.com/comfyanonymous/ComfyUI#manual-install-windows-linux)

You could have said you didn't want to spend time on it, that'd be clearer.

`You're spending a massive amount of thought and effort towards what could've been just... download and run the thing`

Not at all. For me this is natural, I don't even think about, just prepare everything manually once and then use my own launcher effortlessly. "Just download and run" a non-stable alpha is not my way, I want to know what it does on my machine.

I did spend some effort on writing the original post indeed, just didn't expect it'd be neglected in such a way. Hopefully other people will find it more useful.

`And delete the desktop shortcut file you don't want`

I prefer to not install something I don't need or want.
