### ISSUE TITLE
Windows comfyui install bug (path cutnpaste)

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#148]
There are multiple problems with installing on windows, with an existing comfy install.

I eventually gave up and just told it to install a fresh copy, so I dont know ALL the bugs. but one I do know about:

When it asks you for the location of the existing comfyui, a normal thing to do in windows is go to file explorer, click on the thing, and select (copy as path)

but the installer fails on that and complains about "does not end in py".

Yall need to automatically strip off  ""  enclosing windows paths.

**Comment by mcmonkey4eva** [comment]
Eh, sure, why not -- it now automatically trims stray quotes
