### ISSUE TITLE
model card misreports SDXL type

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#150]
I downloaded the latest AnimagineXL from
https://civitai.com/models/122533?modelVersionId=133462

The autogenerated card says it is type "SDXL 0.9 Base"
But the writeup at civitai, very specifically says it is "SDXL 1.0 Base"

**Comment by mcmonkey4eva** [comment]
This is a mistake in that model, not swarm -- the model type is determined by either (A) ModelSpec metadata -- https://github.com/Stability-AI/ModelSpec - or (B) by autodetection from model content for legacy models.

ModelSpec is a mandatory component of "SDXL 1.0". Any model with the same tensor architecture layout, but lacking ModelSpec, is in fact an SDXL 0.9 model. If the model author used SDXL 1.0 but removed the ModelSpec metadata from their uploaded model, they broke spec and did therefore in fact upload what is technically an SDXL 0.9 model.

Swarm makes it easy to fix that though -- just click the hamburger menu next to the model, and click "Edit Metadata", and change the Architecture from 0-9 to 1: `stable-diffusion-xl-v1-base`. This will automatically add correct modelspec metadata to the model file.
