### ISSUE TITLE
Clearer error message for issues like enabled invalid scoring parameter

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#151]
I had a stableswarmui setup working, but it started giving me
"Something went wrong while generating images."

I installed a NEW ONE in a NEW directory.
still got "Something went wrong while generating images."

nothing on the server console output, no nothing.

used anonymous brower, and that was clean.

So, there needs to be at minimum some "clear all your settings" button, if it isnt going to tell me what is actually wrong.

I'll leave my regular browser in broken mode if you want to ask me more stuff.

**Comment by mcmonkey4eva** [comment]
To clear browser cache: Control+F5

To reset params: Top right -> Quick Tools -> Reset Params to Default

If you have unexplained errors, either
A: Go to Server -> Server Configuration, set LogLevel to Debug. This will log any server issues more explicitly.
or B: Control+Shift+I to open your browser console, in case of client UI-side errors.

**Comment by mcmonkey4eva** [comment]
That indicates you had enabled the Scoring parameter (under advanced)

**Comment by ppbrown** [comment]
Huh!  Yup, that was it. 
I have no idea how that could have got set???  
I thought i left allthe advanced stuff alone :-(

**Comment by ppbrown** [comment]
Would be nice then, to either have a popup, "cant reach Scoring server", or better yet...
"Cant reach scoring server.. turning off scoring".
