### ISSUE TITLE
rgthree-comfy Bypasser nodes

### ISSUE THREAD

**Issue by drago87** [Stability-AI/StableSwarmUI#154]
Would if be possible to add support for the [rgthree-comfy](https://github.com/rgthree/rgthree-comfy) Bypasser nodes?
I have made a issue on [rgthree-comfy](https://github.com/rgthree/rgthree-comfy/issues/56#issue-1985583244) side

**Comment by mcmonkey4eva** [comment]
I made a PR that fixes that: https://github.com/rgthree/rgthree-comfy/pull/57
Tiny little one-line fix

**Comment by mcmonkey4eva** [comment]
Was pulled
