### ISSUE TITLE
Folder structure for controlnet question

### ISSUE THREAD

**Issue by Mikec78660** [Stability-AI/StableSwarmUI#155]
I can't figure out how to get control nets working with SD 1.5. When I put 1.5 control nets into the control net folder it thinks they are SDXL control nets and doesn't let me use them with SD 1.5 models. I have tried making a sd-1 folder and putting all the control net folders in it but still get recognized as SDXL for some reason. Can you tell me how I should be separating SDXL and SD1.5 controlnets?

**Comment by Mikec78660** [comment]
Actually just figured out you can edit the meta-data from the UI. Changed it to sdv1 and now it works. It is set up in the json file but it didn't get read for some reason.

**Comment by mcmonkey4eva** [comment]
Can you give me a link to the controlnet model that was misdetected? I'd like to fix that for future users
