### ISSUE TITLE
refiner running when not enabled

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#156]
When watching the preview image for generation, I see first a purple bar growing left to right.. and then a green bar growing left to right.
doesnt that mean that the 2nd stage refiner thingie is running?
But I dont have refiner toggle enabled, so seems like a bug.

**Comment by mcmonkey4eva** [comment]
No - one bar is the full workflow, the other is the current stage (in normal usage only the Sampler uses the current-stage bar, but sometimes other nodes make use of it)
