### ISSUE TITLE
refiner model selection options

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#157]
This is a 2-in-1 request. 
Right now, I THINK if you enable refiner, but leave the refiner model unchecked, it defaults to the base model used.
If so, at minimum it would be nice for the help message to say that.

But I think it would be better still to have an explicit "use base model" option. Because if you want to save the settings in a preset... it doesnt have a way to override a manually set one, to a "use base model" again.

**Comment by mcmonkey4eva** [comment]
Implemented
