### ISSUE TITLE
Invalid value for parameter Prompt Images

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#158]
In Generate tab, after choosing an image file, it shows the filename without path.
Then, after entering prompt and simple inference setting, click Generate, it says,

"Invalid value for parameter Prompt Images: Invalid image-list value for param Prompt Images - 'C:\fakepath\xxxx.png' - must be a valid base64 string - got 'C:\fakepat...'"

Appears to be the image filename is not correctly captured, or not converted to base64 properly. ComfyUI does not have such problem. Same generate without image would not an issue.

**Comment by mcmonkey4eva** [comment]
0.o - that error is definitely not normal. Can you show me some details of what you're doing?
What browser are you using, and how are you are setting the image?

**Comment by beltonk** [comment]
I tried both Chrome and Firefox, it happens the same.
I just click "Choose file" button and pick any image (tried many but the same problem), the picture is shown in the image box. Then no matter how simple settings it is, it just prompts the above error when I click "Generate".

**Comment by beltonk** [comment]
After some tracing, I think the issue is related to the frontend handling the Image Prompt (Image List). The Image value just contain the filename, while the code expects image base64 data.

And I found some JavaScript script error too, as attached:
<img width="826" alt="Screenshot 2023-11-14 at 21 29 31" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/47bd7260-149b-40cc-8862-f25465cb6689">

**Comment by beltonk** [comment]
I tried to change PromptImages to Image type instead of List<Image>, by modifying T2IParamTypes.cs, ImageBatchToolExtension.cs & WorkflowGenerator.cs, then the error go away.

First I received this error that I haven't seen before: "Invalid data: Model type must be stable-diffusion-xl-v1-base for ReVision (currently is stable-diffusion-v1)", and realized that is for ReVision.
Then I change the SDXL base 1.0 no vae model, it works perfectly.

Sorry that I didn't know there are assumptions, before clicking the "?" tooltip...

I'm not sure it is working correctly actually by this way, and not fixing the root issue with frontend HTML. By the way, what's the reason to use List<Image> while the file control only allows single file selection?

**Comment by mcmonkey4eva** [comment]
I'm still confused. What choose file button?

The _prompt images_ parameter has custom handling and is not a visible parameter unless you've muck with the internal parameter config or something.

Prompt Images (ReVision/IPAdapter) are configured by dragging an image to the prompt box.

**Comment by beltonk** [comment]
This "Choose file" button and the file box. I tried drag & drop, and result in the same pop-up error:
"Invalid value for parameter Prompt Images: Invalid image-list value for param Prompt Images - 'C:\fakepath\xxxx.png' - must be a valid base64 string - got 'C:\fakepat...'"

<img width="353" alt="Screenshot 2023-11-15 at 00 16 30" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/aec03994-2ba0-4dba-bfe2-40d3f66130b5">

**Comment by beltonk** [comment]
You mean Prompt Images is hidden by default? How should I make it work then? I'm confused...
More importantly, how to make it work as supposed to be?

<img width="1455" alt="Screenshot 2023-11-15 at 02 30 55" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/b619d5df-31df-48bd-ac3f-e826fe1ca849">

**Comment by mcmonkey4eva** [comment]
Yes, it works with ReVision and supports multiple images. As I said earlier, you use it by dragging images into your prompt box.

**Comment by mcmonkey4eva** [comment]
`First, we need to enable Advanced Option, then enable the Revision option.` no you don't.

`how do we suppose users could know that they could drag and drop input images to the text prompt` it tells you on the prompt box itself:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/2b714c94-9ab3-4a98-a515-0a6f4753cf22)

`And if Prompt Images won't work when it is forced to be enabled, why we make it an option?`
The internal parameter exists because that's how it shares data between the UI and server. And also is needed for API users.
The advanced parameter configuration is for people who want to muck with the raw parameter settings and know what they're doing.

`By the way, is 10 MB limt for the input images somewhat low?` I had to create a 2048x2048 whitenoise png and paste it 3 times to test the limit. I've never actually hit that before, even dumping tens of (non-whitenoise ie sane filesize) images.
But, regardless, I've bumped it up to 100MiB, so should be properly impossible to hit now.

**Comment by beltonk** [comment]
Right, you got your point again. Just when I enable ReVision, I need to be aware that the text prompt (else where away from ReVision), has a tip for us to drag an image. Or assume ReVision will be automatically enabled after dragging & dropping image one by one to the text prompt.

Thank you, at least I understand how it works for now, maybe it is just me not smart enough to get it right XD
