### ISSUE TITLE
[Feature Request] Can add denoise and CLIPSetLastLayer->stop_at_clip_layer to default Generate Tab workflow?

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#159]
As titled, to customize Denoise & Clip Skip without custom workflow.
Custom workflow won't support Lora, etc...

**Comment by mcmonkey4eva** [comment]
"denoise" is called "Init Image Creativity". ClipSkip, I can add

**Comment by mcmonkey4eva** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/96876d37-04ac-43a8-bbda-6e626348caf3)
added CLIP Stop At Layer under Advanced Sampling

**Comment by beltonk** [comment]
Thank you for the quick response and action! Really Appreciate!
