### ISSUE TITLE
Comfy custom workflow

### ISSUE THREAD

**Issue by QwertyITA** [Stability-AI/StableSwarmUI#16]
When using a custom workflow and setting the models from there, it then says if I press "Generate image" in the "Generate" tab, that there isn't a model selected.

![Screenshot from 2023-07-31 23-48-00](https://github.com/Stability-AI/StableSwarmUI/assets/88203115/354800c7-3307-41f8-b86e-0a89a4c22d4e)
> Workflow that I'm using (above)

![Screenshot from 2023-07-31 23-47-39](https://github.com/Stability-AI/StableSwarmUI/assets/88203115/cd847b80-a922-4ec8-8696-3afdf0d63758)
> Error message

**Comment by mcmonkey4eva** [comment]
You need to link swarmui's model folder with the one you're using -- go to Server -> Settings, there's a model path option.

(And then from there, make sure you actually select the relevant model in the generate tab model list as well)
