### ISSUE TITLE
Better Data Path checking upon launch

### ISSUE THREAD

**Issue by Vooperino** [Stability-AI/StableSwarmUI#161]
Hello there!
Is it possible to create a proper file checking for the `/path/to/Data` because as of right now it check if the directory is created or not, but does not have a proper check if the Data directory is empty for sample then booting up SSUI (StableSwarmUI) it does give an error out
`
10:46:02.559 [Error] Error saving settings file: System.IO.IOException: The file '/StableSwarmUI/Data' already exists.
`
and then does this
`
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/StableSwarmUI/Data/Users.ldb'.
`

My suggestion is to possible to add if the required files do exist or simply have an a file validation check on this past

**Comment by mcmonkey4eva** [comment]
I'm very confused here - what happened? This looks like you have a file named `Data` instead of a folder?
