### ISSUE TITLE
textfiles

### ISSUE THREAD

**Issue by drago87** [Stability-AI/StableSwarmUI#162]
is it possible to add or change information in the generated text file? i would like to add information about loras

**Comment by mcmonkey4eva** [comment]
To image metadata? What information are you looking at add? Metadata by default includes a list of lora & weights in it. Do you want just a personal text note field you can use, or...?

**Comment by drago87** [comment]
Personal text would work if you can take information from the comfyui nodes. I have noticed that it have problem reading loras from some special nodes

**Comment by mcmonkey4eva** [comment]
oh, for custom comfy workflows, node are only listed in metadata directly if you have them toggled on in the Generate view

**Comment by drago87** [comment]
Ok dident know that

**Comment by mcmonkey4eva** [comment]
You can also add random unconnected extra nodes at will like so:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/a74f6fa1-5a69-45a3-aae5-8a5910c3f80a)

And then just mark em enabled:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/f778f20b-8f38-4a28-a3d9-01b09b930b46)

And that will go in metadata. This example is just an empty text box so you can tack in any handwritten metadata you want.
