### ISSUE TITLE
WSL folders for models not working

### ISSUE THREAD

**Issue by xlyric** [Stability-AI/StableSwarmUI#163]
Hi, 

I work on Windows but I have models on the Wsl system 
in the configuration I configure the folders  "\\\wsl.localhost\Ubuntu-22.04\home\yyyy\stable-diffusion-webui_2.1\models"
and work in the confiuiWorkflow editor

but the application StableSwarm create a windows folder : StableSwarmUI\wsl.localhost\Ubuntu-22.04\home\yyyy\stable-diffusion-webui_2.1\models

and in fact not working in the generate tab 
"Invalid value for parameter Model: Invalid model value for param Model - '' - are you sure that model name is correct?" 

Cordialy

**Comment by xlyric** [comment]
PI. 
the work around is to mount the folder

**Comment by mcmonkey4eva** [comment]
I've pushed a commit that should recognize paths in that format - I don't have an easy way to test it offhand, so please let me know if it works

**Comment by xlyric** [comment]
Hi, 

it's work.

thanks a lot again.
