### ISSUE TITLE
base level metadata

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#164]
I uploaded one of my generations, with just the pure front-end, to civitAI, and was surprised it picked up NOTHING about creation info.
Would be nice if, when using the plain non-custom-workflow generator, it saved the first-run generation info in standard format, in the metadata.
Just the basics like model name, seed, and the rest of the standard stuff please?
Saves a bit of time when uploading to civitai.

Please note that I'm using the user defaults. So, image format = JPG, and "save metadata" IS checked already.

given that, technically, i suppose this is a bug report rather than a feature request.

**Comment by ppbrown** [comment]
probably related to this, is if I view an image in history, it shows it in the center panel, anmd offers button to "reuse parameterss".
But if I press it.,. it then pops up, "No parameters to copy!"

**Comment by ppbrown** [comment]
the history one seems to work, if I change to .PNG instead of jpeg.
So i figure either you need to update the "save metadata" to also put it in the jpeg, or you need to have an auto-disable (with popup or something) for "save metadata" if format is jpg

**Comment by mcmonkey4eva** [comment]
Oh, woops, my bad - I updated the code for for jpeg metadata is saved to be a bit closer to how auto webui does it (to be more often detected by external programs) but forgot to update the reading to do the same.

I've updated it now to recognized jpegs clearly too.

re civitai, that's primarily a matter of civitai adding recognition for the metadata - should probably make a feature request to them.

Alternately, it's theoretically possible to add a "metadata format" option that lets you emit in fake-auto-webui format to trick external software that doesn't recognize swarm metadata to parse it anyway.

**Comment by ppbrown** [comment]
for civitai: I don tknow how specifically they do it. but I did a comparison of what comfy /stableswarm saves (using an external exiftool thing).. and it uses exif DIFFERENTLY for the two formats. 
In one, it saves it as "Parameters", and in the other, it saves it as "User Data", I think?
That doesnt seem appropriate to me.

Maybe civit is already looking in both jpg and png, but its looking for the same exif name?

**Comment by mcmonkey4eva** [comment]
I went ahead and submitted the suggestion to civitai myself: https://feedback.civitai.com/submissions/6556764e01b92ee15f1efe5f

**Comment by ppbrown** [comment]
well.. unfortunately, i cant see your post.
however, civitai already has a working jpg info reader, that presumably is whatever A1111 writes.

Take a look at the exif info in
https://civitai.com/images/862136

then also download, and pretend to make an image post, using that image.

civit automatically picks up the info from the jpg

**Comment by mcmonkey4eva** [comment]
The post wasn't visible immediately, as civitai's feedback site goes through moderation before being public. It's visible now.

I'm well aware they have a system to read auto webui metadata inplace. Thus the suggestion that they add support for Swarm's metadata as well.

**Comment by ppbrown** [comment]
oh very cool.
I added my vote for it.
