### ISSUE TITLE
grid generation count wrong

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#165]
whenever I start the grid tool, and select, lets say 6 models to render a prompt.. it will claim there are initially 7 current generations.
its always +1

**Comment by mcmonkey4eva** [comment]
The +1 is the processing of the grid itself.

**Comment by ppbrown** [comment]
IMO, this is is not useful to the user; who will most likely only want to know about the number of images queued remaining. Its misleading.
