### ISSUE TITLE
IPAdapter: Make ViT-H models reliably work

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#166]
Which ControlNet pre-processor should I use for SDXL IP Adapter?
Should I download one for myself? And which directory I should put it?

**Comment by mcmonkey4eva** [comment]
IP-Adapter isn't a controlnet, it's separate -- drag an image into your Prompt box to use ReVision/IPAdapter/other image-prompt techniques as relevant. Options will appear on the left, including IP-Adapter model selector (if you have a comfy backend with one installed).

You can use the old repo <https://github.com/laksjdjf/IPAdapter-ComfyUI> or the new one <https://github.com/cubiq/ComfyUI_IPAdapter_plus> - either way just open a terminal to `StableSwarmUI/dlbackend/comfy/ComfyUI/custom_nodes` and run eg `git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus` (or install Comfy Manager and use that to install it).
(Note: I only just now added support for the new cubiq repo, so make sure to update swarm first if using that one)

You'll need the models inside `custom_nodes/ComfyUI_IPAdapter_plus/models` from https://huggingface.co/h94/IP-Adapter/tree/main
[SDXL IPAdapter](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl.safetensors)
[SD1.5 IPAdapter](https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus_sd15.safetensors)
(Note: don't use the ViT-H ones, use the regular ones).

The plan for the future fwiw is for that to all be automated away.
Currently, only the CLIPVision model download is automated.

**Comment by beltonk** [comment]
Thank you for the update! The basic IP Adapter model works now.
May I know what's the reason not to use ViT-H ones?
Actually I would like to use Ip Adapter Face models, but none of them work

**Comment by mcmonkey4eva** [comment]
I see their ViT-H work is expanding and the native model support is getting ignored (odd choice imo but whatever), I'll see about implementing reliable support for those.

**Comment by mcmonkey4eva** [comment]
Okay, ViT-H support is implemented, it should autodetect and apply. Note that it will take a few minutes on the first run to download the ViT-H Vision model (you can see progress in the console logs).
(You can instead download it manually and store it as `Models/clip_vision/clip_vision_h.safetensors` if you prefer)

**Comment by beltonk** [comment]
Appreciate. Working perfectly now!
