### ISSUE TITLE
any colab or kaggle notebook?

### ISSUE THREAD

**Issue by jjiikkkk** [Stability-AI/StableSwarmUI#167]
any colab or kaggle notebook?

**Comment by mcmonkey4eva** [comment]
Yes - https://github.com/Stability-AI/StableSwarmUI/tree/master/colab

Though note Google really doesn't like colab being used for WebUIs.

**Comment by jjiikkkk** [comment]
colab and kaggle do not accept cloudflare tunnels

**Comment by mcmonkey4eva** [comment]
That's what worked at the time I made that notebook a few months back.

If you can recommend an option that works to switch to, I'll add it
