### ISSUE TITLE
Error Message: "No images were generated (all refused, or failed - check server logs for details)."

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#170]
Swarm Web UI: "Error: No images were generated (all refused, or failed - check server logs for details)."
Terminal: "No images were generated (all refused, or failed)."

I encountered these messages quiet often, because I'm trying a lot of new stuff and experiments. I have no clue what's wrong without checking the text logs

Would the error message be further enhanced to show more details in the UI? or is there way to show both SwarmUI & Comfy debug/error messages in the console?

**Comment by mcmonkey4eva** [comment]
Go to server -> server configuration and change `LogLevel` to `Debug` to show full raw output in the console window.
There are plans to expose this information more clearly in the future, but that's the way for now
