### ISSUE TITLE
Multiple ControlNet Support

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#171]
Is there any plan to support multiple ControlNet models (up to 3)?

**Comment by mcmonkey4eva** [comment]
At the moment the only way is a custom comfy workflow, but you're right that should be added. I had an idea of how to do that (change Image Prompt to have an input-detail configuration thingy, so you could select init/revision/ipadapter/controlnet and specify sub-details from there on a per-image basis) but haven't gotten around to trying to impl it yet

**Comment by beltonk** [comment]
Look forward to the enhancement!
I could live with custom workflow as workaround. Thank you for your advice.

**Comment by mcmonkey4eva** [comment]
Oh, update here: there's multiple controlnet parameter groups now, under advanced (as a placeholder for until the proper interface described above is built), just check "advanced" and use group "controlnet two" and "three"
