### ISSUE TITLE
Error when using OpenPose

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#172]
This error pops up whenever I use OpenPose. It does not interrupt the generation however.

22:57:11.358 [Error] invalid/empty output data from ComfyUI server: {
    "openpose_json": [
        ["{\n    \"people\": [\n        {\n            \"pose_keypoints_2d\": [\n                247.36735026041663,\n                118.81460181872052,\n                1.0,\n                275.75506468613946,\n                219.46195296446484,\n                1.0,\n    ..."
    ]

22:59:24.406 [Error] invalid/empty output data from ComfyUI server: {
    "openpose_json": [
        ["{\n    \"people\": [\n        {\n            \"pose_keypoints_2d\": [\n                247.36735026041663,\n                118.81460181872052,\n                1.0,\n                275.75506468613946,\n                219.46195296446484,\n                1.0,\n    ..."
    ]
}

Missing if-then-else case handling in "private async Task<Image[]> GetAllImagesForHistory(JToken output, CancellationToken interrupt)" I believe?

**Comment by mcmonkey4eva** [comment]
This is a "valid error" (the node is outputting random data that Swarm does not expect or want and didn't ask for), but it should probably be remapped to Debug rather than an Error since it's not a "real problem" in practice

**Comment by mcmonkey4eva** [comment]
It's now tracked as debug, unless Comfy gives no recognized output at all, *then* it becomes an error
