### ISSUE TITLE
History & Metadata about negative prompt not correct when preset is used

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#174]
{value} is not properly replaced by the input prompt in negative prompt, {value} seems always empty after replace.

No issue with positive prompt where {value} is inserted to the preset prompt correctly.

Not sure if the negative prompt for generation is actually correct.

**Comment by beltonk** [comment]
By the way, when multiple preset are chosen, it intelligently combine all keyboards from various presets:

e.g. photographic + cinematic + enhance:

prompt: breathtaking cinematic film still cinematic photo {value} . 35mm photograph, film, bokeh, professional, 4k, highly detailed . shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy . award-winning, professional, highly detailed

However, there are "." appearing in the final prompt, is it expected?

**Comment by beltonk** [comment]
I checked that Import From Generate Tab in ComfyUI, the negative prompt does not carry the input text prompt.
Possibly replacing {value} by prompt input text in negativeprompt didn't happen.

**Comment by mcmonkey4eva** [comment]
Testing, and I can't replicate either issue, seems to be working as intended:

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/95cb0826-66dd-4075-81e1-56b016c59bb4)

Those `.`'s showing up sounds like you just have `.` written in your prompt texts?

**Comment by beltonk** [comment]
My misunderstanidng here... I wrongly assumed that the positive prompt text will also go to the negative prompt created by the preset to emphasize what we want to exclude.

For combined prompt, and the dots:

I think the dots come from the preset, as a shown:

<img width="649" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/674c23a7-0981-4a57-a451-2c22810b74b9">
<img width="649" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/f2eb1e42-6d3f-46f8-8c7e-c54bcc679ade">
<img width="649" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/20547646-f249-4d54-8244-0bc8e79948f5">

Say for example I sellect all three of them with the following positive & negative prompts, the combined prompt will become:

Positive Prompt: a man, realistic 
Negative Prompt: a boy, glasses, beard

Combined Prompts:
<img width="1041" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/76521d16-454e-4a90-896d-eaad0a27248a">

**Comment by beltonk** [comment]
the way they combine is not somewhat predictable straightforwardly, and the results might be out of expectation.
Also not sure if those dots affect the final output.

**Comment by mcmonkey4eva** [comment]
Yes the dots are because you pot dots in the prompt preset. They will have relatively minimal impact - it goes into the model but the model doesn't pay too much attention.
How were you expecting them to combine, if not the way they do?

**Comment by beltonk** [comment]
to clarify they are official presets, I never added those dots since imported,

I assume simply concating prompts with commas would be good enough, combine words from presets to form a phase could yield different meanings.

**Comment by beltonk** [comment]
honestly, presets are not supposed to be used together, as they may have contradicting and repeating prompt text. It will never be perfect. Just the current way to combine them is “interesting” (together with official presets) they simply don’t look correctly functioning

**Comment by mcmonkey4eva** [comment]
Combining presets works better if you have *different things* in the presets. For example you might have an "LCM QuickGen" preset that adds the LCM LoRA, sets the steps and cfg scale. And then you have a style preset with modifies the prompt, and then a negative-style preset that adds a negative prompt, maybe a preset that enables&configures refiner upscale, ... etc. would all stack together perfectly.
