### ISSUE TITLE
[Feature Request] Could you please consider adding Start & End Control Step for IP Adapter?

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#175]
If IP Adapter is employed in the entire generation process, the overall image is highly impacted.

Would you please adding something like: Starting Control Step & Ending Control Step?

Starting Control Step would be the key to preserve the quality of image generation, and apply the IP Adapter at the last stage.

Without that, we can never generate good results in A1111 webui, something like Osato28 did in his example:
https://github.com/Mikubill/sd-webui-controlnet/issues/2208#issuecomment-1821438246

**Comment by beltonk** [comment]
I'm a bit confused... I remember you said IP Adapter is not actually ControlNet, and dragging a picture to the text prompt will show up the ReVision/IP Adapter section.

Do you mean now I can additionally expand ControlNet and make use of the new ControlNet Start & End? If this is the case, would it be cleaner to put everything about IPAdapter inside ControlNet like A1111, or consistently keep them in ReVision section?

**Comment by mcmonkey4eva** [comment]
I completely glossed off the IP Adapter part of the post, sorry.
No, IP Adapter is not controlnet. I added the controlnet start/stop parameters. These are unrelated to IPAdapter, which has no such option.
