### ISSUE TITLE
[Support] What's the equivalent feature of ControlNet "Reference-only Control" in SwarmUI?

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#176]
There is a new "reference-only" preprocessor months ago, which work really well in transferring style from a reference image to the generated images without using Controlnet Models: https://github.com/Mikubill/sd-webui-controlnet/discussions/1236

Is there equivalent feature of such "Reference-only Control" in SwarmUI?

**Comment by beltonk** [comment]
Newer "reference_adain" and "reference_adain+attn" processors:
https://github.com/Mikubill/sd-webui-controlnet/discussions/1280

**Comment by mcmonkey4eva** [comment]
ReVision/IPAdapter are the modern versions.

There's a custom comfy node made by comfy himself lol for ReferenceOnly if you want it: <https://github.com/comfyanonymous/ComfyUI_experiments/blob/master/reference_only.py>

I could import to a proper feature in swarm if there's a reason to use it over the other options?

**Comment by beltonk** [comment]
Hmm, I'm not sure how to explain, but I see different effects for each of them.

Reference-Only seems to me more easy, promising, adopting Latent Diffusion architectural approach, may be more close to Comfy structural approach? I like its simplicity, effectiveness and less prone to create artifacts. 

ReVision/IPAdapter took some time to tune them to the best, slightly more advanced usage, but may require some trial & errors.

Not sure how much better for newer "reference_adain" and "reference_adain+attn" processors: https://github.com/Mikubill/sd-webui-controlnet/discussions/1280

**Comment by mcmonkey4eva** [comment]
So the comfy node doesn't even actually work apparently.

Gonna close this as "upstream from swarm" ie someone has to implement it properly in Comfy before it can be implemented into swarm

**Comment by mcmonkey4eva** [comment]
Update: after followup in another thread recently, Reference Only is available now!

> I've enabled `ReferenceOnly` via comfy's experiment code (slightly adapted), with a new `Use Reference Only` param under ReVision (ie drag an image to prompt box and it will be included as an option)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/4f5df1f2-9412-4fa0-b8ce-0ffdefedff27)
