### ISSUE TITLE
Custom nodes with ComfyUI - javascript files not deployed?

### ISSUE THREAD

**Issue by chrisgoringe** [Stability-AI/StableSwarmUI#180]
This got raised on my custom node - https://github.com/chrisgoringe/cg-use-everywhere/issues/58 - and it looks like it's a case of the .js files not being deployed in StableSwarm. I don't use the swarm, so I don't even know if this makes sense :)

**Comment by mcmonkey4eva** [comment]
The files are deployed, under a sub-path `/ComfyBackendDirect/` - this works fine as long as you correctly use relative paths, but will break if you use absolute paths, or relative paths that jump up too many levels - which these imports https://github.com/chrisgoringe/cg-use-everywhere/blob/main/js/use_everywhere.js#L1 do look to have too many `../` on them?

**Comment by chrisgoringe** [comment]
Thanks. I think the issue is that with a vanilla comfy install there are more entries in the path, so different numbers of ../ work.

I'll look into it. This ticket can be closed :)
