### ISSUE TITLE
Inference ignores LoRAs

### ISSUE THREAD

**Issue by Zombie-Dude** [Stability-AI/StableSwarmUI#182]
When adding LoRAs to a prompt, they are ignored. Embeddings on the other hand are respected. LoRAs and Embeddings all show up in the panel so, paths are correct.

**Comment by mcmonkey4eva** [comment]
the standard way to use LoRAs is via the lora selection UI, not in the prompt - however in prompt should still work. Can you please post some more info about this? Ideally screenshots of your UI showing (1) the metadata of a generated image (2) the prompt (3) the lora menu with the relevant lora visible

**Comment by Zombie-Dude** [comment]
Of course, i use the the LoRAs via selection panel and reference/use trigger words in the prompt. The LoRAs show up in metadata window but they seem to be ignored during inference. I used the same prompt and LoRAs directly in A1111 and they work there.
![Screenshot_2](https://github.com/Stability-AI/StableSwarmUI/assets/108645898/f2cf21d7-433c-4eb3-9823-795287a883e8)

**Comment by Zombie-Dude** [comment]
Here what i would expect to see. Made in A1111 with identical settings and seed.
![Screenshot_1](https://github.com/Stability-AI/StableSwarmUI/assets/108645898/6bc5c956-8310-4960-974d-3c7972f39249)

**Comment by mcmonkey4eva** [comment]
Oh, you're using the auto webui backend... uh. I strongly recommend switching to the comfy backend for reliability/featureset/performance reasons.

**Comment by Zombie-Dude** [comment]
Ugh, but the learning curve.....so volatile.

**Comment by mcmonkey4eva** [comment]
The above commit miiiight fix the issue? Not sure. Don't test auto webui backend much.

`Ugh, but the learning curve.....so volatile.` see that's the nice part - you don't have to learn Comfy's noodles. This is half the point of swarm. You can just use the clean main swarm interface. Comfy is just the backend.

**Comment by Zombie-Dude** [comment]
WOAH! Excellent work! You fixed it!
![Screenshot_3](https://github.com/Stability-AI/StableSwarmUI/assets/108645898/4d513bdd-34ec-4a27-ab32-44d7ada66b19)
