### ISSUE TITLE
easy dotnet for ubuntu 

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#183]
for ubuntu (22, anyway), you dont have to go through all that wierd "install from microsoft" stuff. You can just do

sudo apt install dotnet7

and you get everything needed.

**Comment by mcmonkey4eva** [comment]
Ubuntu 22 is one of five hundred possible Linux variants.
... I'm also not sure what that package is, the standard package on ubuntu is `dotnet-sdk-7.0`.

But either way, install instructions link to Microsoft docs cause it's their problem to document whatever the current correct way for every distro is and not mine.
