### ISSUE TITLE
[Support] SVD supports Apple Silicon?

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#185]
I followed the setup according to the SVD flow in the Feature Announcement. It seems to work correctly, however, after generation, only the image is generated, but no webp / video. There is no any animated image or video generated in Output folder as well.

Does it work for Apple M1 Max? I cannot manage to have it work in ComfyUI, it says
"Error occurred when executing KSampler: Conv3D is not supported on MPS". I was using https://comfyanonymous.github.io/ComfyUI_examples/video/workflow_image_to_video.json

Are they the same issue? I have added "export PYTORCH_ENABLE_MPS_FALLBACK=1" in launch-macos.sh. and using latest PyTorch nightly build

**Comment by mcmonkey4eva** [comment]
This is an issue upstream from Swarm - in Comfy, or in Torch.

There are relevant sounding comfy issues on the topic: https://github.com/comfyanonymous/ComfyUI/issues/2044 https://github.com/comfyanonymous/ComfyUI/issues/2050

**Comment by beltonk** [comment]
Thank you, I was aware too, just failed to compile with the PR 114183 at my first attempt.
I retried and fixed some dependencies issues then SVD works now for both SwarmUI & ComfyUI.

What I did was:
pip install git+https://github.com/pytorch/pytorch@refs/pull/114183/head

**Comment by ioskar-code** [comment]
I got another question. Getting this error on my M1 Ultra studio. Any ideas? OsX Ventura
![IMG_8872](https://github.com/Stability-AI/StableSwarmUI/assets/61546963/d90060ae-3bb7-477d-b52e-92e42a53ddb5)

**Comment by soederpop** [comment]
@beltonk i tried the above, but am having dependency issues with torchvision / torchaudio.  how did you get around this?
