### ISSUE TITLE
Image History: arrow keys to quick-scroll

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#187]
Possible to switch between images in history, with simply just the arrow keys or mouse clicks, just like what it works in Batch preview?

My imagination:
Clicking a thumbnail in Image History may pops up the image with best fit and metadata, instead of opening it to the center pane, may also show all those options including (Edit Image, Upscale 2x, Star, Reuse Parameters). "View in History" can become "View in the Gen Page" instead. I think "View in the Gen Page" may not be used frequently if a handy image gallery browser is already there.

Cool to have the image carousel with sliding thumbnails.

**Comment by mcmonkey4eva** [comment]
I'm confused if this is a feature request for arrow keys to work, or you're just not aware that there's an Image History tab at the bottom?

**Comment by beltonk** [comment]
When I opened an image from the Image History tab, the image cannot be cycled, need to click to open one by one.
What I describe is similar to the batch fit view, seeing large image, and slide to the next or the previous.

**Comment by mcmonkey4eva** [comment]
ref https://github.com/Stability-AI/StableSwarmUI/commit/1aa641f989b45f13426335290659c577a3b14902 and https://github.com/Stability-AI/StableSwarmUI/commit/810827c2c04f00d4df2229113df117ac0a50abe6
it should now behave as you expect, allowing you to use arrow keys to scroll through images in history in main view & expanded (fullscreen) view
