### ISSUE TITLE
[Feature Request] Gen Tab Param Presets

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#189]
Would be super cool to have custom parameter presets. Perhaps, one of them are default/init settings, espeically handy for beginners.

I think the current workaround is to save workflow in Comfy Workflow Editor, and Load back to the Gen Tab. I guess it should be one step away from implementing this feature, if we put it Gen Tab Preset = SwarmUI Workflow - Prompts?

**Comment by mcmonkey4eva** [comment]
Yes that'd be the Presets button at the bottom?

**Comment by beltonk** [comment]
Would be more intuitive to put in on the left Gen Tab pane...
