### ISSUE TITLE
Space issue

### ISSUE THREAD

**Issue by JustZyad** [Stability-AI/StableSwarmUI#192]
Hey there,
When I installed stableswarmui in my D drive it took a lot of space in my C drive, and when I generate an image it takes about 10 gigs of space in C drive but it goes back to normal when I turn it off.
With that being said, if I try to make any adjustment ( like making the image larger or try to make a video ) it gives me an error and I’ll have to rest all backends.
Is there any solution to this problem?

**Comment by mcmonkey4eva** [comment]
Swarm itself doesn't use anything outside its own folder, though it does depend on Microsoft DotNET 7 and Git, either of which may end up installing core files wherever it puts those, you might be able to install them manually instead to force a different path.

Any usage that appears while generating and disappears after is some form of temporary storage, not in Swarm itself but probably in the Comfy backend's underlying python libs?

re ` it gives me an error and I’ll have to rest all backends.` i'd have to know the specifics of _what error_ exactly to be able to respond to that
