### ISSUE TITLE
View Dropdown Box in Logs Page is so shy to stay open

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#194]
It keeps disappearing itself once I open the dropdown menu for less than one second. Almost not possible to change view mode (log level).

**Comment by mcmonkey4eva** [comment]
Ooh, that bug manifested in a much less noticeable way in the browsers I've tested (Firefox flickers a little, Chrome doesn't react at all). Fixed.

**Comment by beltonk** [comment]
Thanks! The fix works for Chrome on my Mac.
