### ISSUE TITLE
For ComfyUI_Dave_CustomNode, the content is not displayed

### ISSUE THREAD

**Issue by bubbl000** [Stability-AI/StableSwarmUI#195]
The contents of the extension in swarmui are not displayed, the options are not displayed, and the right-click menu is not displayed.
I don't know if I should direct this question to the plugin author or swarmui.
Here is a comparison of the comfyui and swarmui interfaces，What should be done about this problem
comfyui：
![image](https://github.com/Stability-AI/StableSwarmUI/assets/108770692/3d8b96e3-d040-469b-a43d-b29a579fdb4b)

swarmui：
![image](https://github.com/Stability-AI/StableSwarmUI/assets/108770692/f67264aa-8a48-4b40-8366-68b56e0da029)

**Comment by mcmonkey4eva** [comment]
That'd be an issue with the relevant extension to fix - I tried googling the name, and only found this https://github.com/Davemane42/ComfyUI_Dave_CustomNode which was archived 8 months ago?
