### ISSUE TITLE
Setting a mask image and then removing it bugs the UI

### ISSUE THREAD

**Issue by Shadetail** [Stability-AI/StableSwarmUI#197]
Trying to generate anything after removing the mask image doesn't work and instead returns an error:
Invalid value for parameter Mask Image: Invalid image value for param Mask Image - 'null' - must be a valid base64 string - got 'null'
Note that disabling initialization image completely is a workaround, but it means inability to use initialization image, so better workaround is F5 refreshing the UI.

**Comment by mcmonkey4eva** [comment]
Ooh, good catch, fixed
