### ISSUE TITLE
Ability to rename presets

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#200]
It would be *really* nice to be able to rename, and move presets.

When I first discovered presets, I had no idea it was possible, and very much desirable, to have folders of presets.
So I made a whole bunch of them at the top level.

But when I wanted to then organize them, I went back to my old ones.. resaved them...
andthen had to manually go back and delete the old ones as well?

This might not be as annoying a thing, if the preset browser wasnt as limited as it is.

**Comment by mcmonkey4eva** [comment]
Yep lol the duplicating was a bit silly - fixed, it actually renames as you expect now.

**Comment by ppbrown** [comment]
Well.. but sometimes you want to dup. Hopefully you added an option for that?

**Comment by mcmonkey4eva** [comment]
Sure, added
