### ISSUE TITLE
cant get it to work.

### ISSUE THREAD

**Issue by HrithikkShinde** [Stability-AI/StableSwarmUI#21]
Cant install through the shortcut file and when i run from the launch file and move to the end of setup page nothing happens .

![image](https://github.com/Stability-AI/StableSwarmUI/assets/72643846/2fb9d880-0e80-432e-9cdb-07bfca062a3e)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/72643846/3e20fcd4-3751-4257-b88f-dcca47dc5756)

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-src\bin\live_release\StableSwarmUI.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

im gettting that error . anyone knows how to fix it ? i have dotnet installed and path is correct too. i have also tried to reinstall it , but nothing works.

**Comment by mcmonkey4eva** [comment]
Your second screenshot appears to show it working?

**Comment by rajeewa47** [comment]
anyone find a way to fix this?

**Comment by mcmonkey4eva** [comment]
Try:
`dotnet nuget add source https://api.nuget.org/v3/index.json --name "NuGet official package source"`
in a command prompt

**Comment by hmhesse** [comment]
Hi, I have the same problem - I can only start it directly with the "launch-windows.bat", but after generating the image, the error "Failed to read output file..." comes up and no image is displayed.. .
Is there already a solution? Thanks

**Comment by mcmonkey4eva** [comment]
Yall please open separate issue posts, this thread is @HrithikkShinde  's launching issue

**Comment by hmhesse** [comment]
... it's the same problem and has something to do with access rights.

**Comment by mcmonkey4eva** [comment]
Please open a separate issue.

**Comment by yesbroc** [comment]
> ![Screenshot 2023-08-05 025018](https://user-images.githubusercontent.com/22423750/258533758-70d52768-7ecb-4ae8-8132-8d5e5124d538.png) anyone find a way to fix this?

fixed this by adding winget to path, should be in```"C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.20.1881.0_x64__8wekyb3d8bbwe\"```

**Comment by pennyvc** [comment]
I'm having same issue, keeps failing at unable to find dotnet even though it knows its installed and it's on path.

**Comment by mcmonkey4eva** [comment]
The original poster hasn't replied and others keep trying to hijack, so... Ima just close+lock this.

Anyone who has an issue, please open your own thread for it.
