### ISSUE TITLE
StableSwarmUI won't install

### ISSUE THREAD

**Issue by mgsnell** [Stability-AI/StableSwarmUI#210]
As a result of you response to my problem I identified yesterday " Can't install rembg" #209, I deleted everything, re-downloaded the install-windows batch file and attempted to install StableSwarmUI, but a some point the installation failed (see attached), I used all the default settings and even tried installing a second time with the same results.

mgsnell
![2023-12-19_08-37-57](https://github.com/Stability-AI/StableSwarmUI/assets/49707336/f24883f4-158c-45ea-856b-fd9b7149c3d5)

**Comment by clemensv** [comment]
+1

**Comment by naifcen** [comment]
I had the same issue, I fixed it by going to this location: \...\StableSwarmUI\dlbackend\tmpcomfy\  you will find a folder called: 'ComfyUI_windows_portable' change it to : 'ComfyUI_windows_portable_nightly_pytorch' to match the error you are facing. Also, I had another issue that the installation for some reason are looking for this folder in this path: 'I:\StableSwarmUI\StableSwarmUI\dlbackend\tmpcomfy\ComfyUI_windows_portable_nightly_pytorch'  while my path doesn't contains double StableSwarmUI folders as showing above, so I had to match that also. and it worked.

**Comment by mgsnell** [comment]
Thanks naifcen for sharing your experience and fixes. Unfortunately, even with the information you provided, it still doesn't work. During the install I encountered several other complaints about missing folders and thanks to your examples was able to work through them. However even after a successful installation (after many folder missing fixes) I cannot generate any content. Hopefully the Author will be able to fix this soon.

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/Stability-AI/StableSwarmUI/commit/e08382f92ee77aea3a1954ab3469541ee10eeddd , delete the swarm folder and rerun the installer and it should be good
