### ISSUE TITLE
[Linux] ComfyUI Backend missing imageio_ffmpeg

### ISSUE THREAD

**Issue by Xeroderma** [Stability-AI/StableSwarmUI#211]
I installed StableSwarmUI and added an existing and working ComfyUI installation to it. 
When it starts up the ComfyUI-Backend, i see an error in Terminal:

16:32:00.062 [Warning] ComfyUI-3 on port 7822 stdout: Traceback (most recent call last):
16:32:00.063 [Warning] ComfyUI-3 on port 7822 stdout:   File "~/Programs/ComfyUI/nodes.py", line 1813, in load_custom_node
16:32:00.063 [Warning] ComfyUI-3 on port 7822 stdout:     module_spec.loader.exec_module(module)
16:32:00.063 [Warning] ComfyUI-3 on port 7822 stdout:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
16:32:00.063 [Warning] ComfyUI-3 on port 7822 stdout:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
16:32:00.063 [Warning] ComfyUI-3 on port 7822 stdout:   File "~/Programs/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/__init__.py", line 1, in <module>
16:32:00.063 [Warning] ComfyUI-3 on port 7822 stdout:     from . import SwarmRemBg, SwarmSaveAnimationWS
16:32:00.064 [Warning] ComfyUI-3 on port 7822 stdout:   File "~/Programs/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/SwarmSaveAnimationWS.py", line 5, in <module>
16:32:00.064 [Warning] ComfyUI-3 on port 7822 stdout:     from imageio_ffmpeg import get_ffmpeg_exe
16:32:00.064 [Warning] ComfyUI-3 on port 7822 stdout: ModuleNotFoundError: No module named 'imageio_ffmpeg'

Looked into my Linux installation (Debian 11) and a package with the same name and it's python version is already installed.
I wonder if that has something to do with me using ComfyUI by using the venv of an Automatic1111 installation.

When i try to generate an image i get this error "No images were generated (all refused, or failed - check server logs for details)."
I assume its because of the first error while loading the Backend.

**Comment by mcmonkey4eva** [comment]
If you really want to intentionally use a weird alt venv? Then:
```
source ./venv/bin/activate
python3 -s -m pip install imageio-ffmpeg opencv-python-headless rembg
```
this will ensure all secondary libs are installed directly in the venv (the `-s` is the key on that)


Alternately if you just let the installer make its own venv, it will also automatically manage it + ensure all packages are installed properly
