### ISSUE TITLE
MacOS install

### ISSUE THREAD

**Issue by wjblock13** [Stability-AI/StableSwarmUI#212]
Ran through the instructions for Mac. Brew installs dotnet 8.0.0. When I run ./launch-macos I get an error saying it can't find dotnet7. I'm sure I'm missing something simple. I even followed the directions at the end of the error and manually installed dotnet (but I assume not in the place it's looking).

Apologies if this is a stupid question, but any help would be appreciated. Would love to help out with the project in anyway and I'm a big fan and user of ComfyUI. 

BTW: <insert home dir here> is a placeholder I substituted for my actual home directory.

MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  StableSwarmUI -> /Users/<insert home dir here>/StableSwarmUI/src/bin/live_release/StableSwarmUI.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.68
You must install or update .NET to run this application.

App: /Users/<insert home dir here>/StableSwarmUI/src/bin/live_release/StableSwarmUI.dll
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (arm64)
.NET location: /opt/homebrew/Cellar/dotnet/8.0.0/libexec/

The following frameworks were found:
  8.0.0 at [/opt/homebrew/Cellar/dotnet/8.0.0/libexec/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=arm64&rid=osx-arm64&os=osx.14

**Comment by mcmonkey4eva** [comment]
(I don't have a mac so the following is secondhand from googling around)

It seems like you'll have to first `brew uninstall dotnet` (per <https://stackoverflow.com/questions/76706036/how-to-install-multiple-dotnet-versions-using-brew> apparently brew does not reliably support installing different versions, and swarm is temporarily on 7 for a safe/slow upgrade cycle before bumping to the new 8)
And then use https://dotnet.microsoft.com/en-us/download/dotnet/7.0

One of these two, I think the arm one for you?
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/ba281a36-22d6-4f62-b7bd-170b3d354fc3)


cc @jorge-campo who wrote the mac instructions and might be able to give better advice

**Comment by wjblock13** [comment]
That did the trick! Thank you for the quick response.

**Comment by AimoneAndex** [comment]
Now it is saying no dotnet8.But brew will download you dotnet9.And no solution for me.Anyone knows how to solve it?

**Comment by mcmonkey4eva** [comment]
@AimoneAndex  This is the ancient stability ai version of the repo from last year, use the current repo https://github.com/mcmonkeyprojects/SwarmUI

**Comment by AimoneAndex** [comment]
> [@AimoneAndex](https://github.com/AimoneAndex) This is the ancient stability ai version of the repo from last year, use the current repo https://github.com/mcmonkeyprojects/SwarmUI

OK，thank you.I will have a try.
