### ISSUE TITLE
upscale 2x button actualy refine image?

### ISSUE THREAD

**Issue by rendomnet** [Stability-AI/StableSwarmUI#213]
I'm new to stablediffusion but as I understand in stableswarmui if i click on upscale 2x button next to my generated image it will upscale and refine this image using currently selected model? also how can I stop this process.

**Comment by mcmonkey4eva** [comment]
Correct, that's what it does. It's kinda just a convenience option that will probably be removed once the Image Editor is complete.

You can stop any generation at any time by clicking the red `X` button next to the `Generate` button (ie, the _Interrupt_ button).
