### ISSUE TITLE
Use all avaible GPU´s

### ISSUE THREAD

**Issue by tomatos666** [Stability-AI/StableSwarmUI#216]
Hi,
i use StableSwarmUI with 2 GTX970.
But i have the problem that StableSwarm use only one graficcart, not both.
Where can i modify this?

**Comment by mcmonkey4eva** [comment]
- open the UI
- go to the `Server` tab
- go to the `Backends` sub-tab
- You'll see an existing ComfyUI Self-Starting backend there - there's a button at the top to add another, so click that
- give the new backend the same start script (`dlbackend/comfy/ComfyUI/main.py`), disable `AutoUpdate` on it, and set `GPU_ID` to `1` (ie the second GPU, as ID 0 is the first)
- Hit save and wait for it to load
- then go generate a big batch of images and make sure they're all in use

**Comment by nix-wolf** [comment]
An easy way to use multiple gpus is to use accelerate launch --multi-gpu
--num_processes 2 app.py

It says that here
https://github.com/huggingface/accelerate

**Comment by mcmonkey4eva** [comment]
Having a monitor attached isn't an issue, no.

Can you screenshot your backends page, and your server resource usage while generating?

**Comment by tomatos666** [comment]
Hello, here the screenshot.
![1](https://github.com/Stability-AI/StableSwarmUI/assets/15941205/42303731-dddd-4fa2-a211-7ce34253a349)
![2](https://github.com/Stability-AI/StableSwarmUI/assets/15941205/cb1164ea-09e2-44ab-984c-9036895078fe)

**Comment by tomatos666** [comment]
Hello, you hve seehing the Screenshot?

**Comment by mcmonkey4eva** [comment]
Oh! You have *three* GPUs, not two, that might be relevant - check the `Server Info` tab to see which IDs are assigned to each (This is also where you should look at resource usage as it has more relevant information displayed).

Also, what are you generating to test? Bear in mind you need to generate at least 2, probably more, images at a time to actually use multiple GPUs.
