### ISSUE TITLE
Ctrl Scroll Up/Down to increase/decrease the size of the brush

### ISSUE THREAD

**Issue by suonnon** [Stability-AI/StableSwarmUI#218]
I think using Ctrl (or Commnand on Mac) + Scroll Up/Down to increase/decrease the size of the brush would help user work faster when using the Unified Canvas, instead of using '[' or ']'

**Comment by mcmonkey4eva** [comment]
"Unified Canvas" is what invokeai calls their image editing canvas. Swarm doesn't go for the fancy naming and just calls it the image editor.

-----

The feature you described literally already exists.

Did you perhaps means to submit this as a request to InvokeAI, ie asking them to copy the way Swarm works? lol
