### ISSUE TITLE
Installation Issue - Cannot Install

### ISSUE THREAD

**Issue by rlewisfr** [Stability-AI/StableSwarmUI#219]
I have tried multiple times to install this UI on my Windows 11 machine without success.  Every time I run the install-windows.bat file, and make my way through the installer, when I reach the Comfy UI install step, I am greeted with the following terminal error:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.08
23:48:39.229 [Init] === StableSwarmUI v0.6.1.0 Starting ===
23:48:39.285 [Warning] You do not seem to have DotNET 8 installed - this will be required in a future version of StableSwarmUI.
23:48:39.285 [Warning] Please install DotNET SDK 8.0 from https://dotnet.microsoft.com/en-us/download/dotnet/8.0
23:48:39.308 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
23:48:39.315 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
23:48:39.315 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
23:48:39.316 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
23:48:39.316 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
23:48:39.317 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
23:48:39.318 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
23:48:39.357 [Init] Parsing command line...
23:48:39.364 [Init] Loading settings file...
23:48:39.365 [Init] No settings file found.
23:48:39.366 [Init] Re-saving settings file...
23:48:39.376 [Init] Applying command line settings...
23:48:39.470 [Init] Prepping options...
23:48:39.543 [Init] Loading models list...
23:48:39.550 [Init] Loading backends...
23:48:39.552 [Init] Loading backends from file...
23:48:39.553 [Init] Prepping API...
23:48:39.554 [Init] Backend request handler loop ready...
23:48:39.555 [Init] Prepping webserver...
23:48:40.031 [Init] Scan for web extensions...
23:48:40.033 [Init] Readying extensions for launch...
23:48:40.033 [Init] Launching server...
23:48:40.034 [Init] Starting webserver on http://localhost:7801
23:48:40.065 [Init] Program is running.
23:48:40.576 [Init] Launch web browser to install page...
23:48:41.293 [Warning] You do not seem to have DotNET 8 installed - this will be required in a future version of StableSwarmUI.
23:48:41.294 [Warning] Please install DotNET SDK 8.0 from https://dotnet.microsoft.com/en-us/download/dotnet/8.0
23:48:42.627 [Info] Creating new admin session for ::1
23:48:55.575 [Init] [Installer] Installation request received, processing...
23:48:55.576 [Init] [Installer] Setting theme to dark_dreams.
23:48:55.577 [Init] [Installer] Configuring settings as 'just yourself' install.
23:48:55.578 [Init] [Installer] Downloading ComfyUI backend... please wait...
00:08:59.379 [Init] [Installer] Downloaded! Extracting... (look in terminal window for details)

7-Zip (a) 23.01 (x86) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:
1 file, 1452281017 bytes (1386 MiB)

Extracting archive: dlbackend\comfyui_dl.7z
--
Path = dlbackend\comfyui_dl.7z
Type = 7z
Physical Size = 1452281017
Headers Size = 343550
Method = LZMA:25 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 2485
Files: 27050
Size:       5079998857
Compressed: 1452281017
00:10:05.047 **[Error] [WebAPI] Error handling API request '/API/InstallConfirmWS' for user 'local': Internal exception: System.IO.IOException: Access to the path 'E:\StableSwarmUI\dlbackend\tmpcomfy\ComfyUI_windows_portable' is denied.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at StableSwarmUI.WebAPI.BasicAPIFeatures.InstallConfirmWS(Session session, WebSocket socket, String theme, String installed_for, String backend, String stability_api_key, String models, Boolean install_amd) in E:\StableSwarmUI\src\WebAPI\BasicAPIFeatures.cs:line 158
   at StableSwarmUI.WebAPI.API.HandleAsyncRequest(HttpContext context) in E:\StableSwarmUI\src\WebAPI\API.cs:line 114**

```
The install interface will not complete the install, it just leaves me on the following:

```
Sending...
Installation request received, processing...
Setting theme to dark_dreams.
Configuring settings as 'just yourself' install.
Downloading ComfyUI backend... please wait...
Downloaded! Extracting... (look in terminal window for details)
Step 2/5
```

The overall install can never be completed.

1. I have tried to run the install in 2 different locations, 2 separate drives;
2. I have run the install as Administrator to see if that could clear an access issue;
3. An annoying note:  every time I run this install, it goes to grab the ComfyUI install package even though I have already downloaded it.  And on my stupid slow internet, that is not an insignificant item.

Any thoughts?

**Comment by rlewisfr** [comment]
Ok, so I ran the process a couple more times after manually installing .NET 8 but was still getting the same error.  Since the batch file ran without problem, I started to suspect the front web UI.  So I switched over to MS Edge from Brave (my new goto browser) and tada! it worked.  Must be something in the Brave security features that was preventing the api call from going through.

However, now that the install has been completed via Edge, I can start the front end web ui on Brave.  I will need to do further testing to see if it suffers any additional issues.

**Comment by kwame-wallace** [comment]
Hi All, the exception seems to be caused by a race condition in **BasicAPIFeatures.cs**, when the folder 
"dlbackend/tmpcomfy/ComfyUI_windows_portable" is locked by "another process" and the code it trying to move it with: 

Directory.Move("dlbackend/tmpcomfy/ComfyUI_windows_portable", "dlbackend/comfy");

_Access to the path 'E:\StableSwarmUI\dlbackend\tmpcomfy\ComfyUI_windows_portable' is denied.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)_

A guess is that the "another process" is 7za.exe, Explorer.exe, anti-virus,  or something else.

**Comment by mcmonkey4eva** [comment]
7za is necessarily completed before that's ran, explorer shouldn't touch it... an antivirus, potentially.

In the event that is the cause, via the above commit, future installs now will retry with a 5 and then 15 second delay before giving up, so if an antivirus locks up the folder for less than 20 seconds, the installer will just wait for that to finish then move it and move on.
Longer than 20 seconds it will still throw an error as usual.
