### ISSUE TITLE
Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by gunnarsal** [Stability-AI/StableSwarmUI#22]
I can get an output using COMFY workflow but when i click us this flow in generate tab and run it again, i get the following errors 

<img width="1201" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/129676685/98fd254c-f72a-4718-aca3-0178bb8d055e">
What am I missing?

**Comment by hben35096** [comment]
The same goes for me

**Comment by mcmonkey4eva** [comment]
Should already be fixed, just update.
