### ISSUE TITLE
Issue: "Hidden" model folders aren't displayed

### ISSUE THREAD

**Issue by ManOrMonster** [Stability-AI/StableSwarmUI#222]
Automatic1111 allows "hiding" a model folder by putting a dot in front of the folder name, so that any models within do not show up in the "all" display. For instance, if you have a folder called ".naughty-stuff" in your "lora" folder, the thumbnails within will not show up in the "all" display.

All of my model folders are named like that because I don't want most models in my "all" display since it's pretty much useless when you have hundreds of them. However, this UI does not display the folders at all in the model selection display.

I haven't found a way to correct this in the settings.

**Comment by mcmonkey4eva** [comment]
Are you sure your model paths are configured in the Swarm Server Settings? Swarm doesn't have any form of built in "hiding" like this.

**Comment by ManOrMonster** [comment]
> Are you sure your model paths are configured in the Swarm Server Settings? Swarm doesn't have any form of built in "hiding" like this.

Yes, I'm sure.

For example, here's a list of several folders in my lora directory. Notice how "lcm" is the only one without a leading dot in the folder name. You can also see the path at the top:
<img width="700" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/3925151/a3d632de-c23d-4ba3-b8f3-a67b159f3a0f">


In the UI, see how LCM is the only folder listed under LoRAs on the left (the models shown are in the root of my lora folder which is why they appear on the right):

<img width="700" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/3925151/0c0f6f85-6b3d-41ca-bfef-fd4c0b075abf">

Here are my settings:

<img width="700" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/3925151/6d6c670f-f2ee-4840-b6d4-001e5b65e43b">

**Comment by mcmonkey4eva** [comment]
... Well, I was wrong, 8 months ago the very first version of the model list code before swarm was even public I for some reason excluded dot folders. I have no memory of doing this https://github.com/Stability-AI/StableSwarmUI/commit/ed836b0a521c1b625a05e92bdb7cc440da95c03c#diff-9b0a91314e7e616cfb42195a4501192278fc7d192ba5c74d8e92cabae5b8c198R29
Maybe I was thinking of `.git` folders? idek.
Removed - dotfolders should show from.
