### ISSUE TITLE
Number of Advanced features in UI went from 37 to 1. 

### ISSUE THREAD

**Issue by CodeAlexx** [Stability-AI/StableSwarmUI#223]
In the front end the advanced setting checktab has 37 on my last use. I went into ComfuUI and loaded a workflow for hi - res rendering, used the work flow and upon going back to the frontend, it now shows just one. How do I get the other 36 back without having to re-install it? In the screen shot it just says 1 in the advanced settings. I hate to install it over and over because the installer always loads the stability default checkpoint of 6 gigs!-- 
<img width="337" alt="Screenshot 2024-01-20 012430" src="https://github.com/Stability-AI/StableSwarmUI/assets/49142369/298063e9-0cec-49af-8832-7e5533a75768">

**Comment by mcmonkey4eva** [comment]
- no need to reinstall generally
- the installer only downloads the model if you leave that checked, you can just uncheck it
- other settings aren't _gone forever_ they're just hidden if irrelevant
- if you've enabled a comfy workflow you can disable it at any time:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/dcbf09ab-5e4b-46a2-b2aa-e6191afe7235)

**Comment by CodeAlexx** [comment]
<img width="809" alt="Screenshot 2024-01-20 085937" src="https://github.com/Stability-AI/StableSwarmUI/assets/49142369/bead783e-1b4f-475d-bd70-5ec9b4a71e70">

There are no workflows set. I cannot use anything if I don't have access. I tried different models, different lora's --  models. If they are hidden as you say -- however -- I need them for new prompts.

**Comment by mcmonkey4eva** [comment]
Sooomething's bugged there. You have parameters hidden but not for any clear reason. Try force-refreshing (CTRL+F5) or try Quick Tools (top right corner) -> Reset Params To Default

**Comment by CodeAlexx** [comment]
those options did not work, however i tried another option. I have a workflow with like 80+ nodes, I imported to generation tab once it was loaded -- went back to generation tab, refreshed-- nothing -- I went back to the comfy workflow tab removed it from there. then went back to generation tab and the 37 advanced numbers showed back. kinda like the remove workflow from the main screen is broke. Swarm now is my main driver for generation but still gotta go to auto1111 for the 3 items i mention last week, Conrolnet, ipadapter and animated diff. just loving it this thing called swarm

**Comment by mcmonkey4eva** [comment]
ControlNet is fully natively supported - though you'll want https://github.com/Fannovel16/comfyui_controlnet_aux to have more preprocessor options.

IP Adapter is supported in the main UI if you install https://github.com/cubiq/ComfyUI_IPAdapter_plus

AnimateDiff is currently unavailable outside of comfy workflows, though SVD is supported natively
