### ISSUE TITLE
Can't figure out how to close image editor

### ISSUE THREAD

**Issue by ManOrMonster** [Stability-AI/StableSwarmUI#224]
After generating an image and clicking "Edit Image", an image editor comes up, and I can't figure out how to close it. Maybe I'm overlooking something, but I don't see any obvious way to do it.

**Comment by mcmonkey4eva** [comment]
Image editor is a preview feature not yet quite ready to go - it just don't have a close button atm, but refreshing the page will send it away

**Comment by gonzalu** [comment]
THANK YOU! I have been going MAD CRAZY to get rid of it :D ... I promise to stay away from it during Alpha LOLOL 

Cheers,
