### ISSUE TITLE
Edit Image - missing features/suggestions

### ISSUE THREAD

**Issue by Ovahlord** [Stability-AI/StableSwarmUI#225]
So I've been lately using the edit image features to fine-tune several images and while working with it, I think there are two things that are worth getting added:

1. Close button. That one is pretty obvious. As of right now, you cannot close the image editing window and have to reload the whole page to get back to regular image generation. So a close button would help to get back to regular image generation

2. Inverting Masks. When dealing with high complexity images where you only want to tweak tiny details, it is worth having a invert mask button so that the whole mask gets inverted. I think a fitting place for such an option would be the right click context menu where the delete layer option is located.

**Comment by mcmonkey4eva** [comment]
These are both already in the plans. Image Editor is a preview feature, not yet fully ready. There's a lot more planned than just that.
