### ISSUE TITLE
Linux Installation Issue

### ISSUE THREAD

**Issue by mirojs** [Stability-AI/StableSwarmUI#227]
Hello,

Just tried to make the installation and the server was up and running. But error occurred () upon clicking "Yes, I'm sure (Install Now)" button in the browser: [Error] [WebAPI] Error handling API request '/API/InstallConfirmWS': Invalid request method: GET

6:27:13.933 [Init] === StableSwarmUI v0.6.0.0 Starting ===
06:27:14.053 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
06:27:14.063 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
06:27:14.064 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
06:27:14.064 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
06:27:14.064 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
06:27:14.064 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
06:27:14.065 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
06:27:14.133 [Init] Parsing command line...
06:27:14.134 [Init] Loading settings file...
06:27:14.149 [Init] Re-saving settings file...
06:27:14.165 [Init] Applying command line settings...
06:27:14.192 [Init] Prepping options...
06:27:14.365 [Init] Loading models list...
06:27:14.379 [Init] Loading backends...
06:27:14.380 [Init] Loading backends from file...
06:27:14.385 [Init] Prepping API...
06:27:14.386 [Init] Backend request handler loop ready...
06:27:14.388 [Init] Prepping webserver...
06:27:14.731 [Init] Scan for web extensions...
06:27:14.732 [Init] Readying extensions for launch...
06:27:14.733 [Init] Launching server...
06:27:14.733 [Init] Starting webserver on http://localhost:7801
06:27:14.820 [Init] Program is running.
06:27:47.981 [Info] Creating new admin session for 127.0.0.1
06:27:57.617 [Error] [WebAPI] Error handling API request '/API/InstallConfirmWS': Invalid request method: GET

Could anyone help on this?

Thanks in advance!

**Comment by mirojs** [comment]
BTW, from Chrome, it says: 
WebSocket connection to 'wss:/ipaddress/API/InstallConfirmWS' failed: 
makeWSRequest @ site.js?vary=0.6.0.0.GIT-3b5911bd:91

**Comment by mcmonkey4eva** [comment]
How are you running your swarm instance? It looks like you have a proxy in between that's mishandling websockets?

**Comment by mirojs** [comment]
@mcmonkey4eva Exactly! I'm running it on EC2 and use epoxy in order to access from ip address instead of localhost. Is there any way that it could go through? Thanks!

**Comment by mcmonkey4eva** [comment]
That sounds like `epoxy` is misbehaving and needs to be reconfigured or replaced. You'll have to google docs on how it works, I'm not familiar. Specifically look into websocket forwarding.

Alternate forwarding options:
- If you can just unfirewall the ec2 instance you can swap host in swarm settings to `0.0.0.0` and just connect to it directly (albeit it'll be visible to external crawlers/pingflooders that might find it)
- Ngrok or Cloudflared which are explained at https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Command%20Line%20Arguments.md and also cloudflared is used in the Colab: https://github.com/Stability-AI/StableSwarmUI/blob/master/colab/colab-notebook.ipynb (both go through a third party service, both work perfectly tho)
- apache2/nginx. If you use apache2 you need relevant mods enabled and within your virtualhost config:

For http:
```
        ProxyPass / http://localhost:7801/
        ProxyPassReverse / http://localhost:7801/
        ProxyPass / ws://localhost:7801/
        ProxyPassReverse / ws://localhost:7801/
        ProxyPreserveHost On
```
for https:
```
        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*) ws://localhost:7801/$1 [P,L]
        ProxyPass / http://localhost:7801/
        ProxyPassReverse / http://localhost:7801/
        ProxyPreserveHost On
```
 This approach also lets you use an http auth key in the config which is nice.

**Comment by mirojs** [comment]
@mcmonkey4eva Thanks for the feedback. It started to work but with two further errors:

#1: on ComfyUI
#2: Nvidia driver not found (the EC2 instance is a GPU one)

14:01:25.573 [Init] Starting webserver on http://localhost:7801
14:01:25.609 [Debug] [Load Time] Web launch took 0.04s (0.58s from start)
14:01:25.610 [Init] Program is running.
14:01:26.679 [Debug] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
14:01:26.679 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/main.py", line 76, in <module>
14:01:26.679 [Debug] ComfyUI-0 on port 7821 stderr:     import execution
14:01:26.680 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 11, in <module>
14:01:26.680 [Debug] ComfyUI-0 on port 7821 stderr:     import nodes
14:01:26.680 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 20, in <module>
14:01:26.680 [Debug] ComfyUI-0 on port 7821 stderr:     import comfy.diffusers_load
14:01:26.680 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
14:01:26.680 [Debug] ComfyUI-0 on port 7821 stderr:     import comfy.sd
14:01:26.681 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/sd.py", line 3, in <module>
14:01:26.681 [Debug] ComfyUI-0 on port 7821 stderr:     from comfy import model_management
14:01:26.681 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/model_management.py", line 118, in <module>
14:01:26.681 [Debug] ComfyUI-0 on port 7821 stderr:     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
14:01:26.681 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/model_management.py", line 87, in get_torch_device
14:01:26.681 [Debug] ComfyUI-0 on port 7821 stderr:     return torch.device(torch.cuda.current_device())
14:01:26.681 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 787, in current_device
14:01:26.682 [Debug] ComfyUI-0 on port 7821 stderr:     _lazy_init()
14:01:26.682 [Debug] ComfyUI-0 on port 7821 stderr:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
14:01:26.682 [Debug] ComfyUI-0 on port 7821 stderr:     torch._C._cuda_init()
14:01:26.682 [Debug] ComfyUI-0 on port 7821 stderr: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
14:01:26.914 [Info] Self-Start ComfyUI-0 on port 7821 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
14:01:26.915 [Info] Self-Start ComfyUI-0 on port 7821 had errors before shutdown:
ComfyUI-0 on port 7821 error: Traceback (most recent call last):
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/main.py", line 76, in <module>
ComfyUI-0 on port 7821 error:     import execution
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 11, in <module>
ComfyUI-0 on port 7821 error:     import nodes
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 20, in <module>
ComfyUI-0 on port 7821 error:     import comfy.diffusers_load
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
ComfyUI-0 on port 7821 error:     import comfy.sd
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/sd.py", line 3, in <module>
ComfyUI-0 on port 7821 error:     from comfy import model_management
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/model_management.py", line 118, in <module>
ComfyUI-0 on port 7821 error:     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/comfy/model_management.py", line 87, in get_torch_device
ComfyUI-0 on port 7821 error:     return torch.device(torch.cuda.current_device())
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 787, in current_device
ComfyUI-0 on port 7821 error:     _lazy_init()
ComfyUI-0 on port 7821 error:   File "/var/snap/amazon-ssm-agent/7628/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
ComfyUI-0 on port 7821 error:     torch._C._cuda_init()
ComfyUI-0 on port 7821 error: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by mirojs** [comment]
Yet another error just coming in:

14:23:21.251 [Error] [WebAPI] Error handling API request '/API/GenerateText2ImageWS': Invalid request method: GET
1

**Comment by mirojs** [comment]
@mcmonkey4eva Got cross this issue and got:

10:39:00.398 [Init] [Installer] Enabling ComfyUI...
10:39:00.399 [Init] [Installer] Downloading model from 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors'... please wait...
10:39:00.401 [Init] Initializing backend #0 - ComfyUI Self-Starting...
Cloning into 'sd-dynamic-thresholding'...
10:39:00.563 [Info] Self-Start ComfyUI (Git Pull) exited properly.
remote: Enumerating objects: 369, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 369 (delta 100), reused 99 (delta 92), pack-reused 257
Receiving objects: 100% (369/369), 1.00 MiB | 28.47 MiB/s, done.
Resolving deltas: 100% (184/184), done.
10:39:09.720 [Info] Saving backends...
10:39:14.576 [Info] Self-Start ComfyUI (Install rembg) exited properly.
10:39:16.546 [Info] Self-Start ComfyUI (Install opencv-python-headless) exited properly.
10:39:17.193 [Init] [Installer] Model download complete.
10:39:17.193 [Init] [Installer] Downloading model from 'https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors'... please wait...
10:39:19.592 [Info] Self-Start ComfyUI (Install imageio-ffmpeg) exited properly.
10:39:19.610 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
10:39:37.398 [Init] [Installer] Model download complete.
10:39:37.557 [Info] ComfyUI backend 0 shutting down...
10:39:37.557 [Info] Shutting down self-start ComfyUI (port=7821) process #1844...
10:39:37.613 [Info] Self-Start ComfyUI-0 on port 7821 exited properly from disabling.
10:39:38.094 [Init] [Installer] Installed!
10:39:45.192 [Info] Creating new admin session 'local' for 127.0.0.1


Upon selecting the models, however, it's stalled there, Any clue on what could done to proceed? Thanks.

**Comment by mirojs** [comment]
BTW, from the web UI, it's saying "Backends are still loading on the server..."

**Comment by mirojs** [comment]
@mcmonkey4eva It's permission issue and working now like a charm! Thanks for helping out!

**Comment by danaxsax** [comment]
> @mcmonkey4eva It's permission issue and working now like a charm! Thanks for helping out!

actually not true!

**Comment by mcmonkey4eva** [comment]
This is the old Stability AI repo from half a year ago. You need the modern independent repo https://github.com/mcmonkeyprojects/SwarmUI
