### ISSUE TITLE
Install mode launch-linux.sh CLI does not work

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#230]
Please make a web interface for the install phase, that actually works for CLI tools.

When trying to install on a headless linux server, the install-linux.sh works fine. But then it gets to the special Install mode for
launch-linux.sh, and it cant complete.

There are multiple potential text mode CLI browers in linux that get auto-launched, some of which being "links", and "elinks".

elinks gets further than links, but neither can get all the way to the actuall "go do the install" bit.
Please either change the HTML, or provide a scripted method to do that install phase.

**Comment by mcmonkey4eva** [comment]
Launch with whatever arg is relevant to forward the server for your environment https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Command%20Line%20Arguments.md

Such as `--host 0.0.0.0` or use cloudflared (see the colab notebook https://github.com/Stability-AI/StableSwarmUI/blob/master/colab/colab-notebook.ipynb which uses cloudflared).

Then you can interact with it from your desktop environment
