### ISSUE TITLE
How to use multi gpu 

### ISSUE THREAD

**Issue by AlexNikMak** [Stability-AI/StableSwarmUI#231]
Hi!
Sorry if this question is already answered.
I have 3 gpus in 1 system. I would like to combine their compute power and generate 1 picture faster or mach bigger resolution. I have seen something similar, but there gpus working on different images.

**Comment by mcmonkey4eva** [comment]
Guide is @ https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Using%20More%20GPUs.md

You can't use multiple GPUs for one image - if that was implemented it would end up being slower than just letting one GPU work through the same task, from all the time wasted passing data back and forth.

**Comment by rbychn** [comment]
So wait, if I want to try animatediff with comfyUI backend, it will only use 1 GPU even if I have more and select the MultiGPU - Use All?

**Comment by mcmonkey4eva** [comment]
Yes, _one animatediff video_ will use only one backend for the entire video. You can however do _two animate diff videos_ at the same time using two GPUs.
