### ISSUE TITLE
randomize in primitive node

### ISSUE THREAD

**Issue by areslp** [Stability-AI/StableSwarmUI#239]
I'm using the Prompt Styler node, I want to randomize the env prompt when I generate images.
The comfyui node is listed as beblow.
![image](https://github.com/Stability-AI/StableSwarmUI/assets/100579/39e5e8f3-a328-4c5f-a303-1485f70ab209)
Does it work in "generate tab"?

**Comment by mcmonkey4eva** [comment]
I don't think that exact thing will translate properly to the gen tab? Not sure, can try.

You can do prompt styling in swarm's interface directly via Presets and randomization via the `<random:>` prompt tag or via wildcards. You can do `<preset:<random:p1, p2, p3>>` even if you want
