### ISSUE TITLE
Install SDK

### ISSUE THREAD

**Issue by enochianborg** [Stability-AI/StableSwarmUI#240]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.201-windows-x64-installer

Install a version of sdk in order to windows-install.bat to function.  This was not present on my machine so it was required to install prior to doing the functions in the .bat

Request this to install the latest version from the .bat file and continue install.

C:\Users\My-machine\StableSwarmUI>launch-windows
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'nuget' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'build' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'src\bin\live_release\StableSwarmUI.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
Press any key to continue . . .

**Comment by enochianborg** [comment]
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=win-x64&os=win10 was also needed in next step.

**Comment by mcmonkey4eva** [comment]
Use the installer in the readme https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-windows it will install all requirements for you

**Comment by enochianborg** [comment]
I did use the install on windows bat file and it exits after installing the files, but it does not move forward without these additional steps, The initial installer.bat does not install what is needed regarding .net which are required for the run-windows.bat to actually go forward.  Otherwise I would not have initiated this thread.

https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=7.0.0&arch=x64&rid=win-x64&os=win10  Correction: it wants the .net7 sdk and the previous.

**Comment by enochianborg** [comment]
Also I just installed these and ran again "install-windows.bat" and it moved forward.  So these instructions do solve this issue.  For anyone experiences this same road block in the future.  This is an issue if sdk 7 is not installed on the system prior to running install-windows.bat for this project.    I am hoping this can be added to the .bat file to check if installed if not then install sdk 7 etc.

**Comment by mcmonkey4eva** [comment]
The installer script does in fact already install .net sdk 7 for you.

**Comment by enochianborg** [comment]
If it had, we would not be having this conversation.  It did not.  I had to do it manually.

**Comment by enochianborg** [comment]
None the less.  I had to do it manually and these are the instructions to do that in case anyone else also has to do the same and hits a roadblock as I did.

**Comment by enochianborg** [comment]
I am glad that it is already there in the .bat installer thank you for pointing that out.  But it did not work or didn't execute for whatever reason and this solves the issue.   I appreciate your skills. thank you for being a dev!  Your work is awesome!  keep on developing awesome works!  We all thank you!!
