### ISSUE TITLE
Request: New setting to pass the actual Init Image resolution to custom ComfyUI workflow

### ISSUE THREAD

**Issue by mozthefox** [Stability-AI/StableSwarmUI#243]
This issue is based on discussion #242 👍🏻

When using a custom workflow to create an image upscale workflow, then using the Generation tab to upscale an image via **Init Image**, it seems Swarm doesn't send the image's actual resolution to the workflow, instead it sends over a resized resolution.

In the discussion topic example above, the test image I've been using is 1152x869 (an SDXL 4:3 image created by Swarm). When this image is sent to **Init Image** and then to the custom workflow, by clicking Generate, the debug logs report the image as being only 658x512. Using a 1024x1024 image as the Init Image doesn't work either. It reports the resolution as 512x512. This doesn't happen if you upload the image directly to the Load Image node in the editor and use the custom workflow directly to upscale.

This issue is especially annoying when you have created the image using one of the supplied aspect ratios in Swarm, yet this isn't passed to the custom workflow you want to use. Is it caused because I was using the larger SDXL sizes?

Is it possible fix this issue or perhaps add a setting in Swarm to send the actual image resolution of the Init Image to the custom workflow?

Many thanks,
James

**Comment by mcmonkey4eva** [comment]
This is a perfect demonstration of _why_ there's automatic resizing btw:
`the test image I've been using is 1152x869 (an SDXL 4:3 image created by Swarm)`
If that image was sent in raw (unresized), it'd be erroneous - all images must have pixel sizes as a multiple of 8 to encode properly in the VAE, which of course `869` is not. At best you get it silently rounded away in the background, or at worst you get a fatal error and the workflow can't process at all, depending on which nodes follow.

**Comment by mozthefox** [comment]
Ahhh apologies...I meant 1152x**896**, my bad! 😬

As I mentioned in my original post, I also tried it with the default SDXL image size of 1024x1024. When Swarm sent this Init Image to the custom workflow it resizes it down to 512x512, for some reason.

**Comment by mcmonkey4eva** [comment]
With the new `SwarmInputImage` node, you can take a custom image input, and choose whether or not to autoresize it with the `auto_resize` toggler on the node
