### ISSUE TITLE
Img2Img soupport / (Comfy ui workflow / extension manager )

### ISSUE THREAD

**Issue by Lolagatorade** [Stability-AI/StableSwarmUI#245]
Currently when using img2img the following error is presented:

```
[Info] User local requested 1 image with model 'stable_cascade_stage_c.safetensors'...
20:34:25.545 [Error] Internal error processing T2I request: System.IO.InvalidDataException: ComfyUI errored: {
  "error": {
    "type": "prompt_outputs_failed_validation",
    "message": "Prompt outputs failed validation",
    "details": "",
    "extra_info": {}
  },
  "node_errors": {
    "10": {
      "errors": [
        {
          "type": "exception_during_inner_validation",
          "message": "Exception when validating inner node",
          "details": "tuple index out of range",
          "extra_info": {
            "input_name": "samples",
            "input_config": [
              "LATENT"
            ],
            "exception_message": "tuple index out of range",
            "exception_type": "IndexError",
            "traceback": [
              "  File \"/home/deadbolt/Downloads/CASC/StableSwarmUI/dlbackend/ComfyUI/execution.py\", line 475, in validate_inputs\n    r = validate_inputs(prompt, o_id, validated)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
              "  File \"/home/deadbolt/Downloads/CASC/StableSwarmUI/dlbackend/ComfyUI/execution.py\", line 458, in validate_inputs\n    if r[val[1]] != type_input:\n       ~^^^^^^^^\n"
            ],
            "linked_node": [
              "10",
              0
            ]
          }
        }
      ],
      "dependent_outputs": [
        "9"
      ],
      "class_type": "SwarmKSampler"
    }
  }
}
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in /home/deadbolt/Downloads/CASC/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 224
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in /home/deadbolt/Downloads/CASC/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 690
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in /home/deadbolt/Downloads/CASC/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 241
```

It is a feature that is available and i am sure theres a way to get it to work but for now there is no intuitive way to ammend or add the img2img functionality to comfyui. Most likley it can be avoided if extensions or comfyui manager is implemented to add missing nodes or whatever it is called i am not too familiar with comfyui's internal workings but being able to modify them in an easy understandable way would be of great benefit in addition to being able to properly import and use workflows so far havent figured a way to download missing nodes from imported workflow.

**Comment by mcmonkey4eva** [comment]
Could you be more specific about what you're doing here?

I can see you're using Cascade, beyond that I have no idea.

**Comment by Lolagatorade** [comment]
> Could you be more specific about what you're doing here?
> 
> 
> 
> I can see you're using Cascade, beyond that I have no idea.

Img2img. Worked fine with other models but refuses to work on cascade. The error I posted was what resulted from attempting to load it

**Comment by mcmonkey4eva** [comment]
That's... not specific at all still. Do you have a custom workflow? Are you using the gen tab? What parameters? What... anything???

**Comment by Lolagatorade** [comment]
> That's... not specific at all still. Do you have a custom workflow? Are you using the gen tab? What parameters? What... anything???

Everything is stock. Any parameter I did change i eventually changed back to default to double check. Can give a retry just wondering if it's been successful with everyone else? Or it's a one time cause because I can try to install it from scratch and not the one click install

**Comment by mcmonkey4eva** [comment]
If you have no parameters set, you cannot generate anything. You definitely have some parameters set - maybe a model? a prompt? etc???

**Comment by Lolagatorade** [comment]
> If you have no parameters set, you cannot generate anything. You definitely have some parameters set - maybe a model? a prompt? etc???

Whatever came out as default I only set up comfyui backend during initial install and then messed with the sliders and values for the batch, cfg ect. Works fine for txt to img . Ille send a more extensive analysis next time I use the program.

**Comment by Lolagatorade** [comment]
You may close the issue. Spontaneously started to work last time i attempted. not sure what the prior error was all about
![image](https://github.com/Stability-AI/StableSwarmUI/assets/42100725/988b9713-cdd7-4ca3-abd0-6cf42fb9f85b)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/42100725/bae1750f-dfcb-441b-96bb-92e3dc50680e)
