### ISSUE TITLE
Feature request: Booru tag autocompletion

### ISSUE THREAD

**Issue by neggles** [Stability-AI/StableSwarmUI#247]
*ominously* hello, mr. monkey. I want ~~to play a game~~ to make a feature request 😸 

It would be great to have support for booru tag autocompletion from tag list CSV files a la [a1111-sd-webui-tagcomplete](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete); from the looks of things most of the infrastructure needed to make that work is already in place (for the various `<segment:>` etc autocomplete popups) so I suspect it wouldn't be too hard?

The tag list files are in [tags/ inside the auto1111 extension repo](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/tree/main/tags) and updated semi-regularly, so (especially given some of the content) I wouldn't expect you to rehost them, but it would probably be a good idea to support the CSV format they use.

thanku mcmonkey/team ❤️

**Comment by Joopz0r** [comment]
To add to this I also enjoy the [https://github.com/Physton/sd-webui-prompt-all-in-one](url) addon because of the Keyword Grouping / One-Click Keyword Addition, you can go through it and build a prompt.

**Comment by mcmonkey4eva** [comment]
Added! See docs here: https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Autocompletions.md

**Comment by elbee2048** [comment]
> Added! See docs here: https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Autocompletions.md

I get a 404 error when using this link. I can't find anywhere how to do it.

**Comment by AshtakaOOf** [comment]
> I get a 404 error when using this link. I can't find anywhere how to do it.

Please move to https://github.com/mcmonkeyprojects/SwarmUI, StableSwarmUI is deprecated.
The documentation you're looking for is here [mcmonkeyprojects/SwarmUI/docs/Features/Autocompletions.md](https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Features/Autocompletions.md).
