### ISSUE TITLE
Segment lora

### ISSUE THREAD

**Issue by jordanjay29** [Stability-AI/StableSwarmUI#248]
It'd be great if a lora could be added directly to a segment sequence or we could choose which sampler passes a lora could apply to  (e.g. first, refiner, nth segment). 

At the moment, I'm having to convert every generation workflow over to the comfy tab, break out the lora from the main sequence (or manually add it) and attach its clip and model attributes to the right nodes manually if I want a different (set of) lora(s) to take effect on a segment, like a face.

**Comment by mcmonkey4eva** [comment]
You can now do eg `a photo of a cat <segment:face> a happy dog <lora:mydoglora>` and the `mydoglora` will only apply to the `segment:face` processing
