### ISSUE TITLE
Not finding my models

### ISSUE THREAD

**Issue by DIYMSG** [Stability-AI/StableSwarmUI#249]
It's not recognizing my models.. https://i.imgur.com/Z2rQG1K.png

It finds only this model for some reason. I tried creating symlinks inside model folder and changing the path in the settings didn't work either ( I set path to A:/models).

**Comment by MoreColors123** [comment]
Been playing around for nearly an hour now... it doesn't matter what I set as the root folder or checkpoint folder, it doesn't find anything. How am i supposed to set this up? I have a folder E:\Models\ with subfolders "checkpoints", "Lora" etc., but it doesn't matter where i put those, it doesn't find them... I think i tried every possibitlity.

**Comment by DIYMSG** [comment]
> Been playing around for nearly an hour now... it doesn't matter what I set as the root folder or checkpoint folder, it doesn't find anything. How am i supposed to set this up? I have a folder E:\Models\ with subfolders "checkpoints", "Lora" etc., but it doesn't matter where i put those, it doesn't find them... I think i tried every possibitlity.

If you are still having problems I can try to help on discord

**Comment by MoreColors123** [comment]
Thank you but I made symlinks like with other UIs before. Shouldn't be so hard though. I wonder what the problem was.

**Comment by mcmonkey4eva** [comment]
Note that if you change the model folder settings atm that won't automatically reload yet, ie you'll need to restart swarm
