### ISSUE TITLE
Deleting images in the UI?

### ISSUE THREAD

**Issue by Mikec78660** [Stability-AI/StableSwarmUI#25]
Am I missing something or is there no way to delete images from the UI?

On a side note I really like the different views, Thumbnails, cards etc.
Also really love the multiple GPU support! It was better than the multiple tab approach you need to take with some other projects.

**Comment by mcmonkey4eva** [comment]
That was on the TODO list as a future problem (since you can just go into the folder and delete it by hand anyway), but since you're asking, I went ahead and added a button for it now
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/256c27c0-902a-4373-b106-fc2b5ee291fe)

**Comment by Mikec78660** [comment]
Super, thank you.
