### ISSUE TITLE
Non functional after initial install/run on (GNU Linux) on Beta release. "dotnet: command not found"

### ISSUE THREAD

**Issue by Lolagatorade** [Stability-AI/StableSwarmUI#251]
Following a fresh full install ( due to updater causing the following issue ) the application works as expected on linux and will launch. After killing it ctrl+c on terminal the successive attempt to start the program results in the following: 

launch-linux.sh: line 12: dotnet: command not found
launch-linux.sh: line 19: dotnet: command not found

commented the lines out because i thaught maybe it is a windows feature that somehow got into the start script resulting in:

launch-linux.sh: line 13: syntax error near unexpected token `fi'
launch-linux.sh: line 13: `fi'

Either way set it back to default and still wouldnt start.

Running this on manjaro/arch linux whatever the latest update is for it on kernel 6.7.7-1 nvidia 1060 ect

![image](https://github.com/Stability-AI/StableSwarmUI/assets/42100725/285ce403-45aa-462b-9eab-1cb4c4af451e)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/42100725/31891825-5f90-4ebb-a73f-75ecfcb94115)

After reboot same issue and the installer also spits out a dotnet error:
sh update-linuxmac.sh                                                                                                                             127 ✘ 
Already up to date.
update-linuxmac.sh: line 20: dotnet: command not found

![image](https://github.com/Stability-AI/StableSwarmUI/assets/42100725/24391e49-e588-4596-8118-b005f3422009)

**Comment by Lolagatorade** [comment]
Update i "fixed it" by installing the dotnet sdk using: https://github.com/dotnet/core/issues/4322#issuecomment-594152294

Noted it may be a good idea to ammend the linux-macos installer to check and install the dotnet package as for me it didnt check if it was present and errored out with the prior explination

please close issue if this is not a true issue i am kinda a newbie for all this stuff i just think the philosophy of this project is for it to be foolproof and no need of troubleshooting.

![image](https://github.com/Stability-AI/StableSwarmUI/assets/42100725/a820f279-5034-4659-85b6-a4f85e1517e5)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/42100725/d67d4ab5-af82-4962-8fee-f3e9839897ca)

**Comment by mcmonkey4eva** [comment]
Pushed a commit to the install script to strongly ensure aspnet is included on linux if you use the script

**Comment by Lolagatorade** [comment]
> See the manual install on linux notes in the readme: https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#alternate-manual-linux-install
> 
> Specifically the note of:
> 
> > Some users [have said](https://github.com/Stability-AI/StableSwarmUI/pull/6) that certain Linux distros expect aspnet-runtime to be installed separately
> 
> 
> 
> seems to be the one affecting you there

Excellent that worked and was exactly what was needed. Maybe something can be implemented into the installer to run a check to verify before finishing the install? For general user experience in a perfectionist viewpoint. Although not sure if it's worth the time and effort since it was a pretty easy fix.

**Comment by Lolagatorade** [comment]
> Pushed a commit to the install script to strongly ensure aspnet is included on linux if you use the script

Actually, now that I looked into it that link you gave me is specific for arch Linux users because endeavor OS, Artix OS, and manjaro are all Arch. This might not be an issue with the Ubuntu those packages might already come in the distribution.
