### ISSUE TITLE
Windows Defender detects the install_windows.bat file as a trojan virus

### ISSUE THREAD

**Issue by dcbravos** [Stability-AI/StableSwarmUI#252]
Hi, I was triyng to install SwarmUI in my Laptop with Windows 11 and Windows Defender as antivirus, and I got this:

<img width="388" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/51930707/f867d325-5e3c-4320-8570-575632781647">

I'm using the [direct link](https://github.com/Stability-AI/StableSwarmUI/releases/download/0.6.1-Beta/install-windows.bat) from this github repository.

Windows defender does not detect the virus if I cat the file on Linux and copy/paste the content into another.

I know, I can override Windows Defender but I think this should be reviewed.

Thanks in advance.

**Comment by dcbravos** [comment]
It's rare, but even my browser (Edge) detects the file when I download it.

<img width="296" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/51930707/a2ed38e5-e20a-4d83-a75a-2d744abc90ee">

I hope this is an issue just for me.

**Comment by mcmonkey4eva** [comment]
If it helps I also added a manual install guide to the readme https://github.com/Stability-AI/StableSwarmUI/commit/a65ad7fa37b2c626fd9f72ffa7919381b8cc3632
