### ISSUE TITLE
Feature request: region visualization

### ISSUE THREAD

**Issue by arcusmaximus** [Stability-AI/StableSwarmUI#256]
(I don't know if this is on your todo list already - if it is, feel free to close)

Regions are currently added through the image editor's selection tool. This has the following disadvantages:
- As a new user, I didn't find it very obvious that you have to click "Edit Image" to add regions. It gets more confusing when you just started the UI and the image editor isn't even available yet - you have to generate a dummy image just so you can define the regions for the image you actually want to make.
- After you've defined a region and removed your selection, you can no longer tell where the region is, let alone adjust it. (Tweaking the cluster of numbers in the prompt and imagining the result doesn't count)

I would suggest the following:
* Extend the "No image loaded" state to show a blank canvas that automatically adapts to the selected resolution/aspect ratio. After generating an image, it should be possible to close it and go back to this state.
* Move the "Add Region" button from the image editor to below this canvas/the generated image.
* When the button is clicked, display a message that the user may now drag a rectangle on the canvas/generated image. Change the mouse cursor to show we're in this state, and change the "Add" button to a "Cancel" button. Maybe even respond to an Esc keypress.
  * Alternatively, just add a default region for the user to then adjust.
* Region rectangles are permanently visible. They can be resized by dragging on their edges, moved by dragging on an icon in one corner, and deleted by clicking an icon in another corner.
* Region prompts can be typed directly in the region rectangles. The global prompt no longer shows these or their \<region\> tags.
  * Alternatively, show the region rectangles in different colors (or with different numeric labels) and have matching colored/numbered prompt fields below the global prompt. This would make it slightly harder to associate regions with prompts, but would work better for overlapping regions and long prompts.

**Comment by mcmonkey4eva** [comment]
Yes the image editing tools are an early preview, not yet complete, so the awkward limitations there are a temporary issue until that's developed further.
