### ISSUE TITLE
X-only tiling?

### ISSUE THREAD

**Issue by nbs** [Stability-AI/StableSwarmUI#259]
I'd love to be able to specify only to do the seamless tiling on the X-axis only. If you need a use case, think backgrounds for things like a platformer game, something horizontally scrollable but doesn't try to put the ground in the sky as to be Y-tileable too.

Thanks!

**Comment by mcmonkey4eva** [comment]
This is an interesting feature request and a cool idea, however I'm not sure how to actually achieve it in practice - internally tiling comes down to setting pytorch Conv2d padding mode to `circular`, and they don't appear to have any form of "x_circular but y none" type of options, nor any obvious way to inject that short of... maybe totally replacing the Conv2d code with alternate code that call's a custom pad?

**Comment by nbs** [comment]
Thanks for your response! I've heard as much, from asking around the sdnext repo.

I think InvokeAI is the only project that has figured out an implementation:

![image](https://github.com/Stability-AI/StableSwarmUI/assets/615352/fd48ea55-1585-4e1b-9f24-67777ed85991)

https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/backend/stable_diffusion/seamless.py

Of course I'd prefer to use Swarm though.

The dream is actually to axis-tile AND upscale at the same time, as seen in this longstanding issue in AUTO1111 there's a few of us wanting it:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3590

I imagine this is very low on the priority list but thanks for your consideration nonetheless!

**Comment by mcmonkey4eva** [comment]
Oh, yep, they do exactly what I was thinking - injecting and replacing the conv2d code with an alternate handler

**Comment by mcmonkey4eva** [comment]
the seamless tileable param now has X-Only and Y-Only options

**Comment by nbs** [comment]
Huge! Thank you so much. Haven't been able to test it yet but will let you know if I run into anything. Thanks again.
