### ISSUE TITLE
Some Bugs about Upscale and LoRa

### ISSUE THREAD

**Issue by cerarslan** [Stability-AI/StableSwarmUI#26]
Hello, sir, it's me again. Upscale part is not showing up in 'generate tab', in additionally the 'upscale 2x' part distorts the image badly. Also we still can't adjust the LoRa weights. I added the ss.
![FireShot Capture 040 - Image Generation - StableSwarmUI - localhost](https://github.com/Stability-AI/StableSwarmUI/assets/76444259/bb9bdfa6-3c36-494e-98ac-72ac65cf83f8)
![FireShot Capture 039 - Image Generation - StableSwarmUI - localhost](https://github.com/Stability-AI/StableSwarmUI/assets/76444259/c837d2c5-7f8a-4de7-8d51-dd6084ec7258)

**Comment by mcmonkey4eva** [comment]
The LoRAs menu doesn't work for custom workflows, only the default workflow generator - also don't directly muck with it in the advanced tab, use the LoRAs menu if you're going to use the workflow generator.
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/1be4f204-113d-49ce-a75e-47223d057012)

The Load Upscale Model should show up if-and-only-if you have more than 1 upscale model available (ie there's anything to choose from).

If you use the Generate tab without custom workflows, there's upscaling options under the Refiner group
