### ISSUE TITLE
ROCm support

### ISSUE THREAD

**Issue by TerryNachtmerrie** [Stability-AI/StableSwarmUI#260]
Does it exist? Although I pick the AMD option during install, StableSwarm will install CUDA-libraries and once everything is installed I end up with a ComfyUI message telling me I don't have Nvidia drivers installed.

There are no other messages, probably because everything installs just fine.

Running Ubuntu 22.04 with ROCm 5.7 on a Radeon RX6800XT and an Intel I7-12700k. Other gui's including a stand-alone ComfyUI work fine.

**Comment by mcmonkey4eva** [comment]
Yes, you just have to do it manually (ie install rocm pytorch compatible with your AMD card into the comfy backend) for the moment pending the automatic installer being set up to work properly -- track this issue for that https://github.com/Stability-AI/StableSwarmUI/issues/23
