### ISSUE TITLE
How to use Swarm on remote linux machine?

### ISSUE THREAD

**Issue by ptits** [Stability-AI/StableSwarmUI#261]
Most software use gradio links and --share option
How to access Swarm on remote machine without ngrok, cloudflare or port forwarding?
I installed it with no problem but could not access it

**Comment by mcmonkey4eva** [comment]
Gradio is one network share service (that is exclusive to gradio webservers), Cloudflared (with a 'd' on the end) is a different service that works the same way -- just use cloudflared.

The notebook version of swarm automatically installs and uses cloudflared https://github.com/Stability-AI/StableSwarmUI/tree/master/colab

**Comment by ptits** [comment]
hmmm I checked number of steps to start using Cloudflared, may be I miss something but --share flag sounds a way simplier

Before you get started
Before you use Cloudflare Tunnel, you'll need to complete a few steps in the Cloudflare dashboard: you need to add a website to your Cloudflare account. Note that today it is possible to use Tunnel without a website (e.g. for private routing), but for legacy reasons this requirement is still necessary:

[Add a website to Cloudflare](https://support.cloudflare.com/hc/en-us/articles/201720164-Creating-a-Cloudflare-account-and-adding-a-website)
[Change your domain nameservers to Cloudflare](https://support.cloudflare.com/hc/en-us/articles/205195708)
Installing cloudflared
Downloads are available as standalone binaries, a Docker image, and Debian, RPM, and Homebrew packages. You can also find releases [here](https://github.com/cloudflare/cloudflared/releases) on the cloudflared GitHub repository.

**Comment by mcmonkey4eva** [comment]
Whatever docs you're reading aren't relevant.

Just install the cloudflared binary appropriate to your OS, then launch swarm with the flag `--cloudflared-path (shove the binary you used here)`. Again check the notebook version if you're confused, it does it all:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/07fb878c-ed62-47f1-99fa-d9c777389f7b)

**Comment by ptits** [comment]
Whatever docs you're reading aren't relevant. - it was direct link from Swarm Docs Advanced Usage

I will investigate more for Ubuntu options, thanks

Collab is not good for many reasons

**Comment by mcmonkey4eva** [comment]
Colab is not necessary to use, but looking at how the notebook does it makes it clear how to do it yourself in your own env.

`it was direct link from Swarm Docs Advanced Usage` oh, yike, updated docs to be clearer there
