### ISSUE TITLE
Needs to be re-installed everytime i use it

### ISSUE THREAD

**Issue by yjyrfh** [Stability-AI/StableSwarmUI#264]
Iam using win 10 on a local setup, i use the program without a issue but when i close and re open my browser it shows the install ui wizard.i check my models folder and nothing is in it,i run through the install setup again and it works fine until i close out of my browser.

**Comment by mcmonkey4eva** [comment]
... huh? That doesn't sound right. Is it possible you've somehow installed it in an environment where it can't write files (but also somehow isn't exploding with errors in the process)?

**Comment by yjyrfh** [comment]
Iam gonna pretend i never posted this question,i was clicking the launch-windows.bat and not the swarm desktop shortcut to launch it.ooops sorry
