### ISSUE TITLE
An error is reported when ComfyUI is installing

### ISSUE THREAD

**Issue by g123413927** [Stability-AI/StableSwarmUI#266]
![1](https://github.com/Stability-AI/StableSwarmUI/assets/86763326/09226940-b465-438e-adde-322535caea2e)
<img width="1091" alt="2" src="https://github.com/Stability-AI/StableSwarmUI/assets/86763326/4894c036-e1e4-4bb4-b038-08f044bc5255">

**Comment by mcmonkey4eva** [comment]
That looks like your network connection crashed while downloading the comfy file -- can probably just restart swarm and try it again, making sure you're on as stable of a connection as you can be first.
