### ISSUE TITLE
Mac Comfy warning at startup

### ISSUE THREAD

**Issue by Bavoch** [Stability-AI/StableSwarmUI#267]
22:34:13.325 [Info] Self-Start ComfyUI (Git Pull) exited properly.
22:34:13.353 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
22:34:13.924 [Info] Creating new admin session 'local' for ::1
22:34:15.686 [Info] Self-Start ComfyUI-0 on port 7821 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
22:34:15.686 [Info] Self-Start ComfyUI-0 on port 7821 had errors before shutdown:
ComfyUI-0 on port 7821 error: Total VRAM 32768 MB, total RAM 32768 MB
ComfyUI-0 on port 7821 error: Set vram state to: SHARED
ComfyUI-0 on port 7821 error: Device: mps
ComfyUI-0 on port 7821 error: VAE dtype: torch.float32
ComfyUI-0 on port 7821 error: Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
ComfyUI-0 on port 7821 error: Adding extra search path checkpoints /Users/Bavoch/StableSwarmUI/Models/Stable-Diffusion
ComfyUI-0 on port 7821 error: Adding extra search path vae /Users/Bavoch/StableSwarmUI/Models/VAE
ComfyUI-0 on port 7821 error: Adding extra search path vae /Users/Bavoch/StableSwarmUI/Models/VAE
ComfyUI-0 on port 7821 error: Adding extra search path loras /Users/Bavoch/StableSwarmUI/Models/Lora
ComfyUI-0 on port 7821 error: Adding extra search path loras /Users/Bavoch/StableSwarmUI/Models/Lora
ComfyUI-0 on port 7821 error: Adding extra search path loras /Users/Bavoch/StableSwarmUI/Models/LyCORIS
ComfyUI-0 on port 7821 error: Adding extra search path upscale_models /Users/Bavoch/StableSwarmUI/Models/ESRGAN
ComfyUI-0 on port 7821 error: Adding extra search path upscale_models /Users/Bavoch/StableSwarmUI/Models/RealESRGAN
ComfyUI-0 on port 7821 error: Adding extra search path upscale_models /Users/Bavoch/StableSwarmUI/Models/SwinIR
ComfyUI-0 on port 7821 error: Adding extra search path upscale_models /Users/Bavoch/StableSwarmUI/Models/upscale-models
ComfyUI-0 on port 7821 error: Adding extra search path upscale_models /Users/Bavoch/StableSwarmUI/Models/upscale_models
ComfyUI-0 on port 7821 error: Adding extra search path embeddings /Users/Bavoch/StableSwarmUI/Models/Embeddings
ComfyUI-0 on port 7821 error: Adding extra search path embeddings /Users/Bavoch/StableSwarmUI/Models/embeddings
ComfyUI-0 on port 7821 error: Adding extra search path hypernetworks /Users/Bavoch/StableSwarmUI/Models/hypernetworks
ComfyUI-0 on port 7821 error: Adding extra search path controlnet /Users/Bavoch/StableSwarmUI/Models/controlnet
ComfyUI-0 on port 7821 error: Adding extra search path controlnet /Users/Bavoch/StableSwarmUI/Models/ControlNet
ComfyUI-0 on port 7821 error: Adding extra search path clip_vision /Users/Bavoch/StableSwarmUI/Models/clip_vision
ComfyUI-0 on port 7821 error: Adding extra search path clip_vision /Users/Bavoch/StableSwarmUI/Models/clip_vision
ComfyUI-0 on port 7821 error: Adding extra search path clip /Users/Bavoch/StableSwarmUI/Models/clip
ComfyUI-0 on port 7821 error: Adding extra search path unet /Users/Bavoch/StableSwarmUI/Models/unet
ComfyUI-0 on port 7821 error: Adding extra search path gligen /Users/Bavoch/StableSwarmUI/Models/gligen
ComfyUI-0 on port 7821 error: Adding extra search path custom_nodes /Users/Bavoch/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
ComfyUI-0 on port 7821 error: Adding extra search path custom_nodes /Users/Bavoch/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes
ComfyUI-0 on port 7821 error: OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
ComfyUI-0 on port 7821 error: OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/

**Comment by mcmonkey4eva** [comment]
This would an issue with https://github.com/comfyanonymous/ComfyUI 's Mac support so please report there
