### ISSUE TITLE
comfy-install-linux.sh calls for NVIDIA even if AMD is selected during setup.

### ISSUE THREAD

**Issue by JRKilroy** [Stability-AI/StableSwarmUI#269]
Line 18 of the comfy-install-linux.sh
python3 -s -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121

**Comment by mcmonkey4eva** [comment]
Yes, yes it does. Tracked in https://github.com/Stability-AI/StableSwarmUI/issues/23

PRs welcome if you can test to make sure it works exactly correct on an AMD card + has an if check behave same-as-before on nvidia. There's an arg passed into the script for switching on it's just not used yet cause i haven't been able to test

**Comment by JRKilroy** [comment]
Thank you for the prompt response.  I was able to get my install up and running on AMD in linux, But the script was not my friend.  
I didn't keep great troubleshooting records, but here was my experience with most of the swearing removed (swearing is common side effect of Ubuntu for me):

- download install-linux.sh, runs without error.
- Walk through manual configuration in UI (dark, comfyui, SDXL), start install.
- Wait for downloads and install scripts to complete.  Notice Cuda driver install in script terminal.
- "no Nvidia GPU" error on the server.
- futz around, manually install torch, delete and reinstall, no luck.
- Read through launchscripts/comfy-install-linux and find cuda driver install; change out for ROCM.
- delete old dlbackends folder.
- run the updated comfy-install-linux.sh
- Find out it creates the dlbackground in the launchtools directory when run from there (duh).
- try running the comfyui self starting option in the backend tab.  still creates the directory in launchtools.
- manually copy the comfyui script from launchtools up to the StableSwarmUI directory and run on the CLI from there.
- Script finishes using ROCM
- From the backend tab, manually point to the startup script in dlbackends/ComfyUi/main.py
- Everything starts, so go to bed and come back tomorrow. :)
