### ISSUE TITLE
Hardcoded local folder generation for image saving

### ISSUE THREAD

**Issue by jordanjay29** [Stability-AI/StableSwarmUI#270]
Similar to #19, I noticed there doesn't seem to be an option or way to override the creation of a `local` folder (much like one can the default `raw` folder), even when a custom output directory is specified. 

I've even tried to override it by prefixing my output path with `/../` to no avail. 

I'm either missing something or this would be a preferable feature to have for organization. I swap between multiple GUIs and would like one place to find my generated outputs.

**Comment by mcmonkey4eva** [comment]
The solution to your issue is just use the solution to the issue you linked? Toggle off the `AppendUserNameToOutputPath` server setting
