### ISSUE TITLE
Allow use of the extra_model_paths file for custom model paths in Server Configuration

### ISSUE THREAD

**Issue by regiellis** [Stability-AI/StableSwarmUI#271]
Currently, the server configuration lacks flexibility in specifying custom model paths. It would be nice to accommodate diverse setup scenarios in which the extra_model_paths file is used exclusively for setups. To give you an example, I wrote a CLI in python to clone a "BASE" comfy install with "standard" custom_nodes that I use and install for every comfy deployment. All my models are centralized in a single external "MODEL" directory, allowing me to pseudo sandbox potential breakage from custom nodes by only installing them to
that local instance model folder in a new clone directory.

Having the ability to define both a local model base folder as well as referring extra_model_paths would help.

**Comment by mcmonkey4eva** [comment]
I believe if you have `extra_model_paths.yaml` in the comfy root dir that'll just work

Your models folder should just be set in the swarm Server Configuration tab though
