### ISSUE TITLE
[BUG] "Generate" button doesn't do anything

### ISSUE THREAD

**Issue by bkosowski** [Stability-AI/StableSwarmUI#273]
In short, the "Generate" button doesn't trigger the generation process.

My set up is very simple. I installed the system through:
```
git clone https://github.com/Stability-AI/StableSwarmUI.git
 .\update-windows.bat
 .\launch-windows.bat
```

I know that the installation has been successful, together with all the requisites, because:
[start-log.txt](https://github.com/Stability-AI/StableSwarmUI/files/14720671/start-log.txt)

The only settings I changed are the directories for models and output dir:
![swarm-directories](https://github.com/Stability-AI/StableSwarmUI/assets/4819024/4847a456-0b4c-4b82-a800-ca4847b5a888)

I see that the backend is running, both in the logs and in the tab:
![swarm-backend](https://github.com/Stability-AI/StableSwarmUI/assets/4819024/07277614-8e60-4f76-b8bf-9409aa2acc1f)

I then chose a SD1.5 model (DeamShaper v8), wrote a simple prompt "A cat running down the street", clicked "Generate", and... nothing happens. The console is silent. The UI is silent. Nothing is happening.
The last entries in the console are these:
```
10:40:52.112 [Init] Launching server...
10:40:52.112 [Init] Starting webserver on http://localhost:7801
10:40:52.135 [Init] Program is running.
Already up to date.
10:40:52.548 [Info] Self-Start ComfyUI (Git Pull) exited properly.
10:40:52.554 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
10:40:52.641 [Init] Launch web browser...
10:40:52.907 [Info] Creating new admin session 'local' for ::1
10:40:55.664 [Init] Self-Start ComfyUI-0 on port 7821 started.
```

I'm running Windows 11, the system is up to date.
There may be some Windows setting I need to change?

Also, from what I've seen in the picture explaining StableSwarmUI features, my UI looks different right after the installation. This is mine:
![swarm-t2i](https://github.com/Stability-AI/StableSwarmUI/assets/4819024/a3cca0ff-90d4-4fcd-bba7-f8250b37fe89)
I don't have Core parameters with Images, Seeds, Steps, Resolution, etc.

I made to separate clean installations. Each time, it's the same.

I am willing to debug this on my machine. But I don't know where to start.

**Comment by mcmonkey4eva** [comment]
Should follow the installer: https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-windows

**Comment by bkosowski** [comment]
> Should follow the installer in the readme: https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-windows

But why? I followed the official install guide from the Readme: https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#alternate-manual-windows-install

Also, the only difference in running the bat from the first link is the command line parameter to the launch bat:
```
.\launch-windows.bat --launch_mode webinstall
```
which is not mentioned in the manual install. Even if I run it like that, the result is the same.

**Comment by mcmonkey4eva** [comment]
It's been a couple months -- it's possible a fresh install now will just magically fix, uh, whatever this issue was (it doesn't even really make sense tbh, I have no idea how that happened, for you to be just entirely missing all but a few parameters?).
