### ISSUE TITLE
Local install needs access to models as well?

### ISSUE THREAD

**Issue by Xyem** [Stability-AI/StableSwarmUI#274]
I have StableSwarm installed on my laptop and 3 remote ComfyUI instances and it appears I can't use StableSwarm because my laptop doesn't have access the files that the backends use (models etc.). This seems a bit antithetical to the point of having remote backends to me. Doesn't it find out which backends have which models anyway, to know which backend to schedule a request to?

**Comment by mcmonkey4eva** [comment]
You need remote _Swarm_ instances not remote comfy instances -- https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Using%20More%20GPUs.md

**Comment by Xyem** [comment]
I'm not sure how your link answers the question. It explicitly states I should be able to use ComfyUI backends instead of Swarm backends for this use.

**Comment by mcmonkey4eva** [comment]
Generally Swarm backends "just work" while comfy backends require knowing exactly what you're doing, and not doing unusual things like inconsistent model sets between backends. You _can_ use a remote comfy backend but you never _should_, and in your specific situation you _need_ to use swarm on the remote because you have inconsistent states between machines.

**Comment by Xyem** [comment]
> because you have inconsistent states between machines.

All backends have access to the same files, it's only the frontend that doesn't.

**Comment by mcmonkey4eva** [comment]
You need a swarm instance that sees the models

**Comment by Xyem** [comment]
I'll pass. This is set up in such a weird way if that is required, considering there is a custom node provided specifically for getting ComfyUI backends to report what files it knows about.

https://github.com/Stability-AI/StableSwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyCommon/SwarmInternalUtil.py
