### ISSUE TITLE
[BUG] on linux, unable to load model inside a folder

### ISSUE THREAD

**Issue by tabishz** [Stability-AI/StableSwarmUI#276]
Here is an example of error: `"details": "ckpt_name: 'l"details": "ckpt_name: 'lightning\\dreamshaperXL_lightningDPMSDE.safetensors' not in (list of length 36)",' not in (list of length 36)",`

However this model was in the folder, "lightning/dreamshaperXL_lightningDPMSDE.safetensors" models' folder, where the / is converted to \\ and attempts to load the model, which it can not find.

NAME="Pop!_OS"
VERSION="22.04 LTS"
Python 3.10.12

after moving the model outside of the sub-folder, it is able to load and work.

**Comment by mcmonkey4eva** [comment]
Does it work if you restart Swarm?

That error looks like either (A) you have mixed custom backends across different OS's not configured properly, or (B) you just added models for the first time while swarm was running and it didn't update for path format properly.

The underlying technical reason is Linux uses `/` as a folder separator, and Windows... also does, however some code in windows favors `\` instead, and comfy unfortunately uses that particular format for Windows and gets confused if you mix slash formats, so Swarm has code to autodetect which slash is in use by a backend and adapts accordingly. It should be entirely automated away but it's possible for it to go wonky.
Also on Linux it's possible to type a `\` directly into a model name, which if so will confuse the system into thinking it's running Windows, so, uh, don't do that.

**Comment by tabishz** [comment]
It is being used on Linux only the UI is accessed remotely on the same LAN.

Swarm was restarted as well, the models existing in the location from before - no new models were added to the models folder. both ComfyUI and StableSwarmUI are on Linux. So I don't think it should confuse anything with windows.

**Comment by mcmonkey4eva** [comment]
On a fresh start of swarm (before generating images),
go to Server -> Logs -> set view to Debug
(wait for comfy to launch if not already launched)
You should see a message at the bottom like this:
`2024-03-23 12:29:31.638 [Debug] Comfy backend 0 using model folder format: backslash \ due to model Cascade\stable_cascade_stage_b.safetensors`
