### ISSUE TITLE
[BUG] UI values are not set on new SwarmInputs

### ISSUE THREAD

**Issue by henrique-galimberti** [Stability-AI/StableSwarmUI#279]
Steps to reproduce:

1. Create a SwarmInput on a Custom Workfow (with some default value).
2. Attach a logger node (or use its value in something you can verify later if it's indeed using the correct value).
3. Load the Custom Workfow to the Generate tab.
4. Change the value of the SwarmInput in the Generate tab.
5. Generate an image.

The value set in the input of the Generate tab for that SwarmInput will not be used. Instead, the default value of the SwarmInput (or null if it doesn't have an value) will be used (tested with a logger node and as a text for a prompt node).

**Comment by mcmonkey4eva** [comment]
Yes sorry this is a brand new in-development feature

**Comment by henrique-galimberti** [comment]
> Yes sorry this is a brand new still-in-development feature, doesn't fully work yet

Oh, I should have known 😅

Looking forward to it, will be perfect for what I'm trying to achieve.

**Comment by mcmonkey4eva** [comment]
As of the update today - they do actually function now.
(Still not considered complete, might change still. This is part of an ongoing project, the end-goal is to be able to use these nodes and save the workflow to create fully usable friendly-mode pages for complex workflows to inexperienced users without them ever having to see the noodles)

**Comment by henrique-galimberti** [comment]
Just tested and it's working exactly as I wanted. This has become the best UI available, by far.
