### ISSUE TITLE
Sampler on Auto webui backend

### ISSUE THREAD

**Issue by eskaviam** [Stability-AI/StableSwarmUI#28]
Currently can't pick sampler for auto webui backend, please add a support to this thank you

**Comment by mcmonkey4eva** [comment]
Auto WebUI backend hasn't gotten enough love, been focused on Comfy.

Added an auto-webui Sampler param.

Long term plan is to have a single generic sampler param that automatically translates name format to be compatible with any backend (that'll require some planning on how to handle cases where some backends don't have some samplers though).
