### ISSUE TITLE
Sorting and Organization Features for LoRA / Models / Embeddings / Wildcards 

### ISSUE THREAD

**Issue by stratusxh** [Stability-AI/StableSwarmUI#282]
Most regular users have hundreds of LoRA / Models / Embeddings / Wildcards. It would be great if there was a drop-down to sort by Date Created / Name / Reverse order similar to the Image History tab. 

It would also be nice for users to be able to quickly add Stars (⭐) to remember their favorites, either a Single star system or perhaps 5 stars ranking, that could also be added as a sorting feature (Most->Least ⭐s) to quickly look through their best models. 

Also, it would be nice if the UI remembered the user's last setting, so if they prefer to sort by Date Added for example, it would default to that next time they open the UI so they can quickly see their newest downloaded models to test them out.

**Comment by mcmonkey4eva** [comment]
You can sort models listings by date now (and reverse and all). (And yes this setting persists).

For the stars thing, probably just put models into folders? This is how the image star system works, on the inside it just pushes images to a 'Starred' folder
