### ISSUE TITLE
In a grid, presets with refiner included don't take into account refiner options

### ISSUE THREAD

**Issue by andreimanu** [Stability-AI/StableSwarmUI#284]
I have one base model that I use and two different refiners. If I run the prompts separately with different refiners it works fine. So I created three presets: Base model + Refiner 1, Base model + Refiner 2, Base model with no refiner. 
I created a grid with a list of 20 different prompts and I added the three presets. All the resulting images are the same. I mean, the first image is replicated three times, as if the refiner is not taken into account. Same thing happens with refiner steps and refiner control percentage.
I get the exact same image, the exact same artifacts, as if the image is duplicated instead of recreated, though it still takes the full time to generate

Later edit:
Adding the model manually and adding the refiner models manually in the grid instead of using the presets don't seem to work either...

Laterer edit:
Even if I manually switch the refiner model manually and keep the seed it doesn't work. As long as it's a different seed I get different results, but if I keep the seed and regenerate it gives back the same image without the refiner.
First image says generation_time: 0.00 (prep) and 31.38 (gen) seconds,
Next images say 0.00 (prep) and 0.22 (gen) seconds,

**Comment by mcmonkey4eva** [comment]
Could you post screenshots of your parameters / grid / preset?

Most likely issue is one way or another you're generating with refiner turned off by accident

**Comment by andreimanu** [comment]
Sure, no problem. 
I used this prompt:
`an orange cat looking up at the camera`

These are my Core Parameters (I put seed at 1, just to have a seeded number)

![image](https://github.com/Stability-AI/StableSwarmUI/assets/5923325/3cd8d758-2f22-4122-b329-9f727913feac)

Here is the grid configuration:

![image](https://github.com/Stability-AI/StableSwarmUI/assets/5923325/52412af9-77eb-4678-9ef3-7fc957083efe)


I don't know how to add NONE or NULL or w/e for the third one to generate without a refiner, so I just added the base model again

These are the grid results:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/5923325/74c07f68-e887-4176-b7e9-7da5d9f09bf6)

First image says:
```
Image: sd_xl_base_10/dreamshaperxl_v/601/71/301/anorangecatlook/061.jpg, parameters:
prompt: an orange cat looking up at the camera, seed: 1, steps: 60, cfgscale: 7, aspectratio: 1:1, width: 1024, height: 1024, model: OfficialStableDiffusion/sd_xl_base_1.0.safetensors, refinercontrolpercentage: 0.6, refinersteps: 30, refinermodel: dreamshaperXL_v21TurboDPMSDE.safetensors, nopreviews: true, swarm_version: 0.6.2.0, date: 2024-04-01, generation_time: 2.05 (prep) and 0.23 (gen) seconds,
```

Second image says:
```
Image: sd_xl_base_10/ultraspicexltur/601/71/301/anorangecatlook/061.jpg, parameters:
prompt: an orange cat looking up at the camera, seed: 1, steps: 60, cfgscale: 7, aspectratio: 1:1, width: 1024, height: 1024, model: OfficialStableDiffusion/sd_xl_base_1.0.safetensors, refinercontrolpercentage: 0.6, refinersteps: 30, refinermodel: ultraspiceXLTURBO_v15.safetensors, nopreviews: true, swarm_version: 0.6.2.0, date: 2024-04-01, generation_time: 2.33 (prep) and 0.00 (gen) seconds,
```

Third image:
```
Image: sd_xl_base_10/sd_xl_base_10/601/71/301/anorangecatlook/061.jpg, parameters:
prompt: an orange cat looking up at the camera, seed: 1, steps: 60, cfgscale: 7, aspectratio: 1:1, width: 1024, height: 1024, model: OfficialStableDiffusion/sd_xl_base_1.0.safetensors, refinercontrolpercentage: 0.6, refinersteps: 30, refinermodel: OfficialStableDiffusion/sd_xl_base_1.0.safetensors, nopreviews: true, swarm_version: 0.6.2.0, date: 2024-04-01, generation_time: 2.30 (prep) and 0.09 (gen) seconds,
```

**Comment by mcmonkey4eva** [comment]
Yeaaah hah, so, protip: When you don't know what's going wrong, post *too much* info rather than *too little*. If you knew exactly which info to post, you wouldn't need to post it, you'd just solve it yourself.

Case in point: the parameters you *didn't* screenshot are where the issue is.
I'm betting right under your core parameters you did screenshot, just below out-of-view is:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/9320d0b8-97a0-4146-a0e5-a6622ef88689)

an unchecked Refiner group.

If you don't enable the refiner group, the refiner doesn't run.
(More precisely, the refiner only runs if the "Method", "Control", and "Upscale Method" parameters are enabled, but these are all always enabled so long as the group is. If you're using a preset to make it enable regardless, you need at least these 3 params included in the preset)

**Comment by andreimanu** [comment]
So I have to check it even if the grid is supposed to take care of it? I mean, the grid only overrides the values and not the actual group ? Also, is there any way to disable the refiner in one generation of the grid? Or should I just refine with the base model?

As for including info, as I thought the grid is the one controlling the values it didn't even cross my mind to check that parameter out, I'll redo the grids and hopefully it will work.

Damn, rookie mistake, thanks a lot for the help ^^

**Comment by mcmonkey4eva** [comment]
`Also, is there any way to disable the refiner in one generation of the grid?` with the model axis, no. If you use presets, yes. Or if you have an axis for control percentage, yes (just set to 0).
