### ISSUE TITLE
mac failed to load comfyui workflow editor

### ISSUE THREAD

**Issue by blues1112** [Stability-AI/StableSwarmUI#286]
When I tried to install Stable Swarm ui today, everything went smoothly as per the process. However, when I opened it, I found that the workflow editor couldn't load. I tried to modify the backend path but it didn't work. I am using an M1 Mac.

**Comment by blues1112** [comment]
13:52:13.190 [Init] === StableSwarmUI v0.6.2.0 Starting ===
13:52:13.212 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
13:52:13.218 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
13:52:13.218 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
13:52:13.218 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
13:52:13.218 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
13:52:13.218 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
13:52:13.219 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
13:52:13.232 [Init] Parsing command line...
13:52:13.232 [Init] Loading settings file...
13:52:13.248 [Init] Re-saving settings file...
13:52:13.257 [Init] Applying command line settings...
13:52:13.268 [Init] Prepping options...
13:52:13.355 [Init] Loading models list...
13:52:13.384 [Init] Loading backends...
13:52:13.384 [Init] Loading backends from file...
13:52:13.390 [Init] Prepping API...
13:52:13.390 [Init] Initializing backend #2 - ComfyUI Self-Starting...
13:52:13.390 [Init] Backend request handler loop ready...
13:52:13.391 [Init] Prepping webserver...
13:52:13.581 [Init] Scan for web extensions...
13:52:13.584 [Init] Readying extensions for launch...
13:52:13.584 [Init] Launching server...
13:52:13.584 [Init] Starting webserver on http://localhost:7801
13:52:13.644 [Init] Program is running.
13:52:14.145 [Init] Launch web browser...
已经是最新的。
13:52:14.207 [Info] Self-Start ComfyUI (Git Pull) exited properly.
13:52:14.245 [Init] Self-Start ComfyUI-2 on port 7821 is loading...
13:52:15.573 [Info] Creating new admin session 'local' for 127.0.0.1
13:52:17.756 [Info] Self-Start ComfyUI-2 on port 7821 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
13:52:17.756 [Info] Self-Start ComfyUI-2 on port 7821 had errors before shutdown:
ComfyUI-2 on port 7821 error: Total VRAM 16384 MB, total RAM 16384 MB
ComfyUI-2 on port 7821 error: Set vram state to: SHARED
ComfyUI-2 on port 7821 error: Device: mps
ComfyUI-2 on port 7821 error: VAE dtype: torch.float32
ComfyUI-2 on port 7821 error: Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
ComfyUI-2 on port 7821 error: Adding extra search path checkpoints /Users/taohengjun/ComfyUI/StableSwarmUI/Models/Stable-Diffusion
ComfyUI-2 on port 7821 error: Adding extra search path vae /Users/taohengjun/ComfyUI/StableSwarmUI/Models/VAE
ComfyUI-2 on port 7821 error: Adding extra search path vae /Users/taohengjun/ComfyUI/StableSwarmUI/Models/VAE
ComfyUI-2 on port 7821 error: Adding extra search path loras /Users/taohengjun/ComfyUI/StableSwarmUI/Models/Lora
ComfyUI-2 on port 7821 error: Adding extra search path loras /Users/taohengjun/ComfyUI/StableSwarmUI/Models/Lora
ComfyUI-2 on port 7821 error: Adding extra search path loras /Users/taohengjun/ComfyUI/StableSwarmUI/Models/LyCORIS
ComfyUI-2 on port 7821 error: Adding extra search path upscale_models /Users/taohengjun/ComfyUI/StableSwarmUI/Models/ESRGAN
ComfyUI-2 on port 7821 error: Adding extra search path upscale_models /Users/taohengjun/ComfyUI/StableSwarmUI/Models/RealESRGAN
ComfyUI-2 on port 7821 error: Adding extra search path upscale_models /Users/taohengjun/ComfyUI/StableSwarmUI/Models/SwinIR
ComfyUI-2 on port 7821 error: Adding extra search path upscale_models /Users/taohengjun/ComfyUI/StableSwarmUI/Models/upscale-models
ComfyUI-2 on port 7821 error: Adding extra search path upscale_models /Users/taohengjun/ComfyUI/StableSwarmUI/Models/upscale_models
ComfyUI-2 on port 7821 error: Adding extra search path embeddings /Users/taohengjun/ComfyUI/StableSwarmUI/Models/Embeddings
ComfyUI-2 on port 7821 error: Adding extra search path embeddings /Users/taohengjun/ComfyUI/StableSwarmUI/Models/embeddings
ComfyUI-2 on port 7821 error: Adding extra search path hypernetworks /Users/taohengjun/ComfyUI/StableSwarmUI/Models/hypernetworks
ComfyUI-2 on port 7821 error: Adding extra search path controlnet /Users/taohengjun/ComfyUI/StableSwarmUI/Models/controlnet
ComfyUI-2 on port 7821 error: Adding extra search path controlnet /Users/taohengjun/ComfyUI/StableSwarmUI/Models/ControlNet
ComfyUI-2 on port 7821 error: Adding extra search path clip_vision /Users/taohengjun/ComfyUI/StableSwarmUI/Models/clip_vision
ComfyUI-2 on port 7821 error: Adding extra search path clip_vision /Users/taohengjun/ComfyUI/StableSwarmUI/Models/clip_vision
ComfyUI-2 on port 7821 error: Adding extra search path clip /Users/taohengjun/ComfyUI/StableSwarmUI/Models/clip
ComfyUI-2 on port 7821 error: Adding extra search path unet /Users/taohengjun/ComfyUI/StableSwarmUI/Models/unet
ComfyUI-2 on port 7821 error: Adding extra search path gligen /Users/taohengjun/ComfyUI/StableSwarmUI/Models/gligen
ComfyUI-2 on port 7821 error: Adding extra search path custom_nodes /Users/taohengjun/ComfyUI/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
ComfyUI-2 on port 7821 error: Adding extra search path custom_nodes /Users/taohengjun/ComfyUI/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes
ComfyUI-2 on port 7821 error: OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
ComfyUI-2 on port 7821 error: OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/

**Comment by mcmonkey4eva** [comment]
https://github.com/Stability-AI/StableSwarmUI/issues/267#issuecomment-2012614802
