### ISSUE TITLE
Can't connect to LAN A1111 API

### ISSUE THREAD

**Issue by OlivioSarikas** [Stability-AI/StableSwarmUI#29]
I can call A1111 via  http://192.168.0.227:7860/  in my browser and it works perfectly. However if i put the same address into the Auto1111 SD-WebUI API By URL field it gives me this error:
[Error] Final error (7) while initializing backend #1 - Auto1111 SD-WebUI API By URL, giving up: System.NullReferenceException: Object reference not set to an instance of an object.
   at StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIAPIAbstractBackend.InitInternal(Boolean ignoreWebError) in C:\Users\multi\SwarmAI\StableSwarmUI\StableSwarmUI\src\BuiltinExtensions\AutoWebUIBackend\AutoWebUIAPIAbstractBackend.cs:line 34

**Comment by mcmonkey4eva** [comment]
Make sure you launch with `--api`

It's possible this error sourced from a webui that lacks a loaded model for some reason? In which case the above new commit should fix handling of that.

Also do note that the auto webui backend has not gotten as much love as the comfyui backend, so some things may be a bit behind when using auto as the backend.
