### ISSUE TITLE
Lora metadata and preview images not updating.

### ISSUE THREAD

**Issue by Yoldeart** [Stability-AI/StableSwarmUI#291]
After updating all my Lora metadata and preview images I cannot seem to get any of this to show up in the web ui. Refresh button doesn't help, and I've double checked that the path is correct. In both Forge and Automatic this new information appears without problem, but I much prefer using Swarm so any help would be appreciated.

**Comment by mcmonkey4eva** [comment]
- Try Utilities -> Reset All Metadata.
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/cdec34fa-8290-4aca-9183-5343995d882f)
- If that doesn't suffice, check that you have proper file permissions to the model folder and swarm's data folder. It can sometimes do weird things if it can't write to these dirs.
- Make sure your metadata/images are in a format that Swarm supports - [ModelSpec](https://github.com/Stability-AI/ModelSpec) is the main preferred metadata format, but some non-standard formats (auto webui, civitai json, matrix) are recognized as well.

**Comment by Yoldeart** [comment]
Worked perfectly, thank you very much.
