### ISSUE TITLE
[FEATURE REQUEST] Add a toggle to not switch to latest generated image

### ISSUE THREAD

**Issue by andreimanu** [Stability-AI/StableSwarmUI#297]
I usually hit a pretty large number of generations at once then go back from time to time to check what was correctly generated and star it, problem is, as it keeps generating it keeps switching to the latest image and taking me away from the one I was looking at, so now I have to go back and find it. It's a minor inconvenience, nothing too urgent. 

Would also like to ask, so I don't open another thread, for a button to star an image from the grid preview page

Thanks!

**Comment by mcmonkey4eva** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/716a0128-d365-4383-b95e-846515ce9f8e)

There is one, under the gear at the top right (ie the live batch view area)

**Comment by mcmonkey4eva** [comment]
Oh, wait, no, that's previews, not full images, you're talking about full images, my mistake

**Comment by mcmonkey4eva** [comment]
Added new checkbox for that:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/25c9d9e9-5100-4321-a082-8097880c79cb)
