### ISSUE TITLE
Can not load 1111  error unrecognized arguments

### ISSUE THREAD

**Issue by jlitz** [Stability-AI/StableSwarmUI#30]
Comfy running fine.    Keep getting errors on loading 1111 as backend.   its requests use  webui script  python file which is:

Self-Start AutoWebUI on port 7822 is loading...
usage: webui.py [-h] [--update-all-extensions] [--skip-python-version-check]
                [--skip-torch-cuda-test] [--reinstall-xformers]
                [--reinstall-torch] [--update-check] [--test-server]
                [--skip-prepare-environment] [--skip-install]
                [--do-not-download-clip] [--data-dir DATA_DIR]
                [--config CONFIG] [--ckpt CKPT] [--ckpt-dir CKPT_DIR]
                [--vae-dir VAE_DIR] [--gfpgan-dir GFPGAN_DIR]
                [--gfpgan-model GFPGAN_MODEL] [--no-half] [--no-half-vae]
                [--no-progressbar-hiding] [--max-batch-count MAX_BATCH_COUNT]
                [--embeddings-dir EMBEDDINGS_DIR]
                [--textual-inversion-templates-dir TEXTUAL_INVERSION_TEMPLATES_DIR]
                [--hypernetwork-dir HYPERNETWORK_DIR]
                [--localizations-dir LOCALIZATIONS_DIR] [--allow-code]
                [--medvram] [--lowvram] [--lowram]
                [--always-batch-cond-uncond] [--unload-gfpgan]
                [--precision {full,autocast}] [--upcast-sampling] [--share]
                [--ngrok NGROK] [--ngrok-region NGROK_REGION]
                [--ngrok-options NGROK_OPTIONS]
                [--enable-insecure-extension-access]
                [--codeformer-models-path CODEFORMER_MODELS_PATH]
                [--gfpgan-models-path GFPGAN_MODELS_PATH]
                [--esrgan-models-path ESRGAN_MODELS_PATH]
                [--bsrgan-models-path BSRGAN_MODELS_PATH]
                [--realesrgan-models-path REALESRGAN_MODELS_PATH]
                [--clip-models-path CLIP_MODELS_PATH] [--xformers]
                [--force-enable-xformers] [--xformers-flash-attention]
                [--deepdanbooru] [--opt-split-attention]
                [--opt-sub-quad-attention]
                [--sub-quad-q-chunk-size SUB_QUAD_Q_CHUNK_SIZE]
                [--sub-quad-kv-chunk-size SUB_QUAD_KV_CHUNK_SIZE]
                [--sub-quad-chunk-threshold SUB_QUAD_CHUNK_THRESHOLD]
                [--opt-split-attention-invokeai] [--opt-split-attention-v1]
                [--opt-sdp-attention] [--opt-sdp-no-mem-attention]
                [--disable-opt-split-attention] [--disable-nan-check]
                [--use-cpu USE_CPU [USE_CPU ...]] [--listen] [--port PORT]
                [--show-negative-prompt] [--ui-config-file UI_CONFIG_FILE]
                [--hide-ui-dir-config] [--freeze-settings]
                [--ui-settings-file UI_SETTINGS_FILE] [--gradio-debug]
                [--gradio-auth GRADIO_AUTH]
                [--gradio-auth-path GRADIO_AUTH_PATH]
                [--gradio-img2img-tool GRADIO_IMG2IMG_TOOL]
                [--gradio-inpaint-tool GRADIO_INPAINT_TOOL]
                [--gradio-allowed-path GRADIO_ALLOWED_PATH]
                [--opt-channelslast] [--styles-file STYLES_FILE]
                [--autolaunch] [--theme THEME] [--use-textbox-seed]
                [--disable-console-progressbars] [--enable-console-prompts]
                [--vae-path VAE_PATH] [--disable-safe-unpickle] [--api]
                [--api-auth API_AUTH] [--api-log] [--nowebui]
                [--ui-debug-mode] [--device-id DEVICE_ID] [--administrator]
                [--cors-allow-origins CORS_ALLOW_ORIGINS]
                [--cors-allow-origins-regex CORS_ALLOW_ORIGINS_REGEX]
                [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE]
                [--disable-tls-verify] [--server-name SERVER_NAME]
                [--gradio-queue] [--no-gradio-queue] [--skip-version-check]
                [--no-hashing] [--no-download-sd-model] [--subpath SUBPATH]
                [--add-stop-route] [--api-server-stop]
                [--timeout-keep-alive TIMEOUT_KEEP_ALIVE]
                [--ldsr-models-path LDSR_MODELS_PATH] [--lora-dir LORA_DIR]
                [--lyco-dir-backcompat LYCO_DIR_BACKCOMPAT]
                [--scunet-models-path SCUNET_MODELS_PATH]
                [--swinir-models-path SWINIR_MODELS_PATH]
webui.py: error: unrecognized arguments:
16:08:45.132 [Info] Self-Start AutoWebUI on port 7822 exited.

**Comment by jlitz** [comment]
Also got same error on SD Next  script

Self-Start AutoWebUI on port 7823 is loading...
usage: webui.py [-h] [--update-all-extensions] [--skip-python-version-check]
                [--skip-torch-cuda-test] [--reinstall-xformers]
                [--reinstall-torch] [--update-check] [--test-server]
                [--skip-prepare-environment] [--skip-install]
                [--do-not-download-clip] [--data-dir DATA_DIR]
                [--config CONFIG] [--ckpt CKPT] [--ckpt-dir CKPT_DIR]
                [--vae-dir VAE_DIR] [--gfpgan-dir GFPGAN_DIR]
                [--gfpgan-model GFPGAN_MODEL] [--no-half] [--no-half-vae]
                [--no-progressbar-hiding] [--max-batch-count MAX_BATCH_COUNT]
                [--embeddings-dir EMBEDDINGS_DIR]
                [--textual-inversion-templates-dir TEXTUAL_INVERSION_TEMPLATES_DIR]
                [--hypernetwork-dir HYPERNETWORK_DIR]
                [--localizations-dir LOCALIZATIONS_DIR] [--allow-code]
                [--medvram] [--lowvram] [--lowram]
                [--always-batch-cond-uncond] [--unload-gfpgan]
                [--precision {full,autocast}] [--upcast-sampling] [--share]
                [--ngrok NGROK] [--ngrok-region NGROK_REGION]
                [--ngrok-options NGROK_OPTIONS]
                [--enable-insecure-extension-access]
                [--codeformer-models-path CODEFORMER_MODELS_PATH]
                [--gfpgan-models-path GFPGAN_MODELS_PATH]
                [--esrgan-models-path ESRGAN_MODELS_PATH]
                [--bsrgan-models-path BSRGAN_MODELS_PATH]
                [--realesrgan-models-path REALESRGAN_MODELS_PATH]
                [--clip-models-path CLIP_MODELS_PATH] [--xformers]
                [--force-enable-xformers] [--xformers-flash-attention]
                [--deepdanbooru] [--opt-split-attention]
                [--opt-sub-quad-attention]
                [--sub-quad-q-chunk-size SUB_QUAD_Q_CHUNK_SIZE]
                [--sub-quad-kv-chunk-size SUB_QUAD_KV_CHUNK_SIZE]
                [--sub-quad-chunk-threshold SUB_QUAD_CHUNK_THRESHOLD]
                [--opt-split-attention-invokeai] [--opt-split-attention-v1]
                [--opt-sdp-attention] [--opt-sdp-no-mem-attention]
                [--disable-opt-split-attention] [--disable-nan-check]
                [--use-cpu USE_CPU [USE_CPU ...]] [--listen] [--port PORT]
                [--show-negative-prompt] [--ui-config-file UI_CONFIG_FILE]
                [--hide-ui-dir-config] [--freeze-settings]
                [--ui-settings-file UI_SETTINGS_FILE] [--gradio-debug]
                [--gradio-auth GRADIO_AUTH]
                [--gradio-auth-path GRADIO_AUTH_PATH]
                [--gradio-img2img-tool GRADIO_IMG2IMG_TOOL]
                [--gradio-inpaint-tool GRADIO_INPAINT_TOOL]
                [--gradio-allowed-path GRADIO_ALLOWED_PATH]
                [--opt-channelslast] [--styles-file STYLES_FILE]
                [--autolaunch] [--theme THEME] [--use-textbox-seed]
                [--disable-console-progressbars] [--enable-console-prompts]
                [--vae-path VAE_PATH] [--disable-safe-unpickle] [--api]
                [--api-auth API_AUTH] [--api-log] [--nowebui]
                [--ui-debug-mode] [--device-id DEVICE_ID] [--administrator]
                [--cors-allow-origins CORS_ALLOW_ORIGINS]
                [--cors-allow-origins-regex CORS_ALLOW_ORIGINS_REGEX]
                [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE]
                [--disable-tls-verify] [--server-name SERVER_NAME]
                [--gradio-queue] [--no-gradio-queue] [--skip-version-check]
                [--no-hashing] [--no-download-sd-model] [--subpath SUBPATH]
                [--add-stop-route] [--api-server-stop]
                [--timeout-keep-alive TIMEOUT_KEEP_ALIVE]
                [--ldsr-models-path LDSR_MODELS_PATH] [--lora-dir LORA_DIR]
                [--lyco-dir-backcompat LYCO_DIR_BACKCOMPAT]
                [--scunet-models-path SCUNET_MODELS_PATH]
                [--swinir-models-path SWINIR_MODELS_PATH]
webui.py: error: unrecognized arguments:
16:17:08.837 [Info] Self-Start AutoWebUI on port 7823 exited.

**Comment by mcmonkey4eva** [comment]
Is it... actually saying `webui.py: error: unrecognized arguments:` with nothing after it like that? wtf?

**Comment by mcmonkey4eva** [comment]
Oh my god it does too. Fixed.

ps do note that in general the auto webui backend has received less love than the Comfy backend has, so some things are more limited.

**Comment by jlitz** [comment]
so  no answer?  Cross off 1111 and SD Next   Ok  Tnx

**Comment by mcmonkey4eva** [comment]
What? It's fixed, the bug was fixed.

**Comment by jlitz** [comment]
fixed?   how so ?  same problem still exists.     I tried deleted some extensions.  will  have to work on it myself i guess.

**Comment by mcmonkey4eva** [comment]
When I closed the issue, I first replicated the problem you saw, fixed it in the code, and then linked the fix in here when I closed it.

You just need to update (double-click the `update.bat` file or run `git pull` in a command line) and it should work now.

If it doesn't work, please post updated logs of any issue you have.

**Comment by jlitz** [comment]
Thank you for you patience.  Working ok now.     What is the backend py  file for comfy?  Switching back t comfy  since 1111 is slow but  can not find the correct py.

**Comment by mcmonkey4eva** [comment]
If you used the installer, `dlbackend/ComfyUI/main.py` is the correct path.
