### ISSUE TITLE
[Feature Request] Changing Grid Generator Output Type should re-use last run

### ISSUE THREAD

**Issue by githubarooski** [Stability-AI/StableSwarmUI#301]
If I want to switch between Output Type, ie changing from `Grid Image` to `Web Page`, then it should see that I haven't changed anything and just re-build the output with the results of the most recent run, instead of re-running everything just to change the output type. Thanks!

**Comment by mcmonkey4eva** [comment]
If using "Web Page", you can modify it and retain the grid. When using other types, it doesn't store as a named grid folder compatible with web grid persistence.
While it's technically _possible_ to implement what you're asking, that would require grid images track web folder paths and all, which, they shouldn't?

If you just want to have your choice between web page and grid image quickly: use Web Page. Web page has an option to save a grid image of the current view at any time.
