### ISSUE TITLE
Mobile UI Issues

### ISSUE THREAD

**Issue by Jcwscience** [Stability-AI/StableSwarmUI#302]
I would like to access the instance on my local pc from my iPhone, but the input text fields get pushed off the bottom of the screen, and the batch preview section fills up much needed screen space. If the prompt section and generate button could be padded farther from the screen edge and the batch preview window could be closed it would mostly be useable.

**Comment by mcmonkey4eva** [comment]
Yep, this is why mobile browser support is listed as a key feature not-yet-done in the readme https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#status

I have ideas for how Swarm should all work on mobile, but haven't gotten the time to try to implement it all myself nor frankly the experience to necessarily do a good job of it, I'm hoping to get a webdev with mobile experience to come in and help with it.
