### ISSUE TITLE
[Feature Request] Add ProRes to SwarmSaveAnimationWS

### ISSUE THREAD

**Issue by githubarooski** [Stability-AI/StableSwarmUI#305]
I think your code change would be something like this
https://github.com/Stability-AI/StableSwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/SwarmSaveAnimationWS.py

            elif format == "prores":
                args += [ "-n", "-c:v", "prores_ks", "-profile:v", "3", "-pix_fmt", "yuv422p10le"]
                ext = "mov"
                type_num = 7 

but I tried adding this and it started only outputting JPEG files instead of MOV files, so clearly there is more involved with the change. 

While it's probably more common to rely on VHS to output prores, it seems like a simple enough change to support it in Swarm for the edge case that would use it. Otherwise you need to always combine SwarmSaveAnimation with VHS Video Combine

**Comment by mcmonkey4eva** [comment]
Added, though note that my browser (Firefox) wasn't willing to render it on page, so I'm not 100% confident on it, but the output video file plays in VLC so it's probably good.
