### ISSUE TITLE
Float input fields with sliders are broken

### ISSUE THREAD

**Issue by henrique-galimberti** [Stability-AI/StableSwarmUI#307]
I updated swarm and these inputs are no longer working.

![image](https://github.com/Stability-AI/StableSwarmUI/assets/68119812/ea7bf5a0-5b86-46ca-83eb-7be4a10420d6)

![image](https://github.com/Stability-AI/StableSwarmUI/assets/68119812/11301ce7-beba-4a04-b75b-1689225c6375)

![image](https://github.com/Stability-AI/StableSwarmUI/assets/68119812/fb359bf3-8613-4893-9ccd-64ea5630cdd0)

**Comment by henrique-galimberti** [comment]
Actually, any "new" input I add in my workflow doesn't work.

**Comment by mcmonkey4eva** [comment]
Ohp, true -- fixed.

Also pushed extra debug logging that will catch a screwup like that quickly hopefully.

(btw note that the SwarmInput system is still a new feature, in-progress -- connected to the "Simple" tab you can try if you enable the new "ShowExperimentalFeatures" server setting)

ps: what's up with your display theme? That looks wrong. The bar of the number slider is missing, and the format looks halfway between Dark Dreams and Modern Dark.

**Comment by henrique-galimberti** [comment]
> Ohp, true -- fixed.
> 
> Also pushed extra debug logging that will catch a screwup like that quickly hopefully.
> 
> (btw note that the SwarmInput system is still a new feature, in-progress -- connected to the "Simple" tab you can try if you enable the new "ShowExperimentalFeatures" server setting)
> 
> ps: what's up with your display theme? That looks wrong. The bar of the number slider is missing, and the format looks halfway between Dark Dreams and Modern Dark.

I'm using Dark Reader chrome extension.
