### ISSUE TITLE
Is there any way to automate the work flow?

### ISSUE THREAD

**Issue by gokulgopinathan** [Stability-AI/StableSwarmUI#309]
Say for example I have generated an image by giving a particular prompt and adjust the parameters. Now suppose if I have a list of prompt for which images to be generated based on previous parameter , isthere any way we can handle.this ? Even using the python script without ui also fine

**Comment by mcmonkey4eva** [comment]
Yes - at the bottom of the Generate tab, go to "Tools", then select "Grid Generator" from the drop down. If you just want a bunch of images, set "Output Type" to "Just Images". On the wide axis row, click the dropdown on the left and select "Prompt" (you can type to search, but prompt is at the top), then in the textbox on the right type in your prompts separated by double pipes `||`, for example `a cat || a dog || some other prompt`, then use the normal generate button which should now say "Generate Grid" to launch generation.
As you can guess from looking at the UI: You can alter any parameters you want this way, and of course do multi-axis comparison grids between different parameters.
"Prompt Replace" axis and "Preset" are both very powerful for more complexly messing with prompt on grids.

_also_ if you want you can at any time just type a `<` into the prompt box to see a list of prompt-syntax features, for example you can do `<random:x, y, z>` to randomly select between multiple different phrases inside a prompt and then just generate with the `Images` parameter set high to get a wide variety of random images.
