### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by enslaved2die** [Stability-AI/StableSwarmUI#311]
On Linux (PopOS) I cant get StableSwarm to Work, the Comfy Backend wont start because torch isnt found.

`11:24:36.232 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
11:24:36.232 [Warning] ComfyUI-0 on port 7821 stderr:   File "/opt/ai/StableSwarmUI/dlbackend/ComfyUI/main.py", line 73, in <module>
11:24:36.232 [Warning] ComfyUI-0 on port 7821 stderr:     import comfy.utils
11:24:36.232 [Warning] ComfyUI-0 on port 7821 stderr:   File "/opt/ai/StableSwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 1, in <module>
11:24:36.232 [Warning] ComfyUI-0 on port 7821 stderr:     import torch
11:24:36.232 [Warning] ComfyUI-0 on port 7821 stderr: ModuleNotFoundError: No module named 'torch'`

Im so confused when I go into the comfy ui and start the main.py it works.
I reinstalled the requirements, reinstalled pip, changed python3 to be the default python so the norma python command will use python3.

**Comment by mcmonkey4eva** [comment]
This sounds like you did not follow the install instructions in the readme: https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-linux

This can happen when the comfy backend does not have a valid self-contained venv, you can test this manually if you like via:
```
source venv/bin/activate
python -s main.py
```
