### ISSUE TITLE
Can we get downscaling, not just upscaling?

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#313]
The refiner offers scale of 1.0- (larger)

but can we get something in the UI that offers scale DOWN as well?
Woudl be nice for at least the following reasons:

1. rendering people at a distance. initial render at 1536x1536 then scale down to 1024x1024
2. doing grid renders for SDXL->SD  training image sets.

**Comment by mcmonkey4eva** [comment]
Huh, I had never thought this would be a thing you'd want to do - but, sure, why not, added.

Note from my test to verify it works: don't run XL Base as the refiner and downscale from 1024 to 512, it just makes a mess even as a refiner step, lol.

**Comment by ppbrown** [comment]
Thanks!
Probably will work best when a model optimized for downscaling is found.
Wonder how that might happen
