### ISSUE TITLE
Preset dialog gets covered by file browser input

### ISSUE THREAD

**Issue by TheLounger** [Stability-AI/StableSwarmUI#316]
### Bug
The New Preset/Edit Preset dialog seems to break the UI sometimes.
It seems to happen when toggling/enabling `Display Normally-Hidden Options?` (`preset_hidden_options_checkbox`).
When this happens, the entire preset dialog is covered by a button (`preset_input_promptimages`), and you can only press that button, requiring a page refresh to fix it.

### System
Windows 10 22H2
Dotnet 8.0.204
StableSwarmUI 9f9cfb44f133f72aae3307bad622013fdb1aab7f
Firefox 125.0.1

**Comment by mcmonkey4eva** [comment]
Ah, yep, broken in the recent redesign PR -- fixed!
