### ISSUE TITLE
Is there any custom settings available so that we can generate multiple image with same subject,

### ISSUE THREAD

**Issue by gokulgopinathan** [Stability-AI/StableSwarmUI#317]
Like if we mention cat in one prompt and generating multiple images , is there any way to retain all the cats in the image as same cat

**Comment by mcmonkey4eva** [comment]
If you drag an image file into the prompt area, that will use it as _ReVision_ input, which can also be used for _IP-Adapter_ if you have <https://github.com/cubiq/ComfyUI_IPAdapter_plus> installed. This is probably the easiest way to attempt consistency. Consistency in general is a tough topic that a lot of people have been trying different techniques with, google around about "consistent characters in stable diffusion" you'll likely find a lot of interesting approaches.
