### ISSUE TITLE
Rerunning the ComfyUI installer if ComfyUI is already installed gives errors

### ISSUE THREAD

**Issue by Muad0510** [Stability-AI/StableSwarmUI#32]
- Installed .net 7
- ran install-windows.bat, created shortcut but did not auto-run
- shortcut gives same error as mentioned in another issue
![image](https://github.com/Stability-AI/StableSwarmUI/assets/9463454/ad6e7c71-96f5-4d17-bd40-261fde3568e4)
- ran launch-windows.bat manually, went through steps, after some wait it seems to install
- on "completion" it opens main.py in VSCode and reopens the install page from the beginning 
![image](https://github.com/Stability-AI/StableSwarmUI/assets/9463454/284ea2cb-7381-4676-bc9f-b9644bfcf52c)

- running launch-windows.bat again does nothing different, opens VSCode and the install page

**Comment by Muad0510** [comment]
After going through the install steps again, without deleting anything, getting this issue
![image](https://github.com/Stability-AI/StableSwarmUI/assets/9463454/126deb91-1e33-49fd-ab00-5d927e780464)

**Comment by mcmonkey4eva** [comment]
It looks like it already extracted and install comfyui in a prior failed install, and so is now erroring when you're trying to overwrite it.

You can either
(A): install it and select "None" as the backend (and fix it after in the main interface if needed), or
(B): open the stableswarmui folder and delete the `dlbackend` folder, then redo the install and have it install comfy

**Comment by mcmonkey4eva** [comment]
Opening main.py in VS Code is weird - it's seemingly not detecting the python executable properly? A clean delete+reinstall should fix that, as it will automatically download a working python while doing that

**Comment by Muad0510** [comment]
Reinstalling python manually and re-running the .bat again solved it in the end.
Now it's running.
Although still threw issues a couple of times, reopening the install page when it seemingly have finished the install, but the models were not downloaded yet. Had to go through the steps again and make it download the models without the backend for it to properly open.

**Comment by olivierlacan** [comment]
#42 is mildly related to this issue BTW.

**Comment by mcmonkey4eva** [comment]
I imagine this issue is outdated by now, given the months of work between the alpha this was reported on and the current beta
