### ISSUE TITLE
Using ip-adapter with SD 1.5 model in Image Edit Batcher

### ISSUE THREAD

**Issue by johnbrownlow** [Stability-AI/StableSwarmUI#320]
Not sure if this is a bug of a feature request BUT...

-- using the Image Edit Batcher with image set as input to ReVision
-- using an SD1.5 model

The batcher refuses, because it isn't an SDXL 1.0 model.

The only way to make it work is to preload an image into the prompt, and then set ReVision to 0. However this then remains as part of the input to ip-adapter, which is not what I want.

I tried installing ip-adapter-sd15 as a controlnet but there is no preprocessor available. I couldn't figure out how to fix this.

So maybe either

-- automatically fall back to ip-adapter if the model isn't SDXL 1.0, or
-- have ip-adapter-sd15 available as a controlnet as well?

or I guess have the SD1.5 ip-adaptors available in the ReVision tab?

**Comment by mcmonkey4eva** [comment]
- I've updated the Image Edit Batcher tool to automatically show the ReVision area, so you don't need to shove an image to the prompt area to make it work.
- Yes for SD1 set ReVision Strength to 0. This does not affect your IPAdapter results at all.
- make sure you have an updated copy of <https://github.com/cubiq/ComfyUI_IPAdapter_plus> installed. Swarm has the ability to autoinstall this for you as of a few days ago, if you don't have any ipadapter node installed it will appear as a button in the revision box. Swarm will automatically download the IPAdapter models for you if they're missing.
- IPAdapter is not a controlnet, it is different.
- All IPAdapters work with SD1, but they can be a little weird sometimes, please report if any specific ones are failing. There's a couple that don't work with XL, which are both labeled "SD1.5 ONLY" in their names.

**Comment by johnbrownlow** [comment]
Super. Thanks so much for being so responsive.
