### ISSUE TITLE
UI error in Presets options

### ISSUE THREAD

**Issue by chopitol** [Stability-AI/StableSwarmUI#324]
I don't know if this happens only to me.

in the PRESETS section, when creating a new preset or editing an existing one.
by activating "Display Normally-Hidden Options?" It can no longer be disabled and clicking anywhere will open the window to load the "prompt Images"
The "Choose File" button will always be activated no matter where you click
The solution is in the CSS sheet
Assign to:
<label for="preset_input_promptimages" class="auto-file-label">
the value:
position: relative !important;

sorry for my bad English

**Comment by TheLounger** [comment]
Already reported in #316 and fixed, so you should update your installation 😄

**Comment by chopitol** [comment]
> Already reported in #316 and fixed, so you should update your installation 😄

I update from the update-windows.bat file
is that correct? Why does the problem keep appearing to me?
Or do I have to update it through some other command?
From already thank you very much

**Comment by mcmonkey4eva** [comment]
... well, now I'm very confused. It was recently fixed in the prior issue, I tested and confirmed at the time... but it is indeed broken again. I don't know how that happened, but, uh -- re-fixed, and re-tested to once again be fixed.

And yes update-windows.bat is the correct way to update
