### ISSUE TITLE
Basic user questions

### ISSUE THREAD

**Issue by Llin1028** [Stability-AI/StableSwarmUI#326]
The first question is——I want to use ComfyUI‘s workflow directly, but after experimentation, I keep getting an error: “Inwalid hits him: Unkenen Param Teprexter 'Sample' “，please help me, how can this be solved
![Snipaste_2024-04-30_18-49-35](https://github.com/Stability-AI/StableSwarmUI/assets/131455899/1083eca3-8163-4355-acac-d5274b674685)
There is also a second question: I see that there are a lot of translation files in different languages in the language folder, such as en.json, es.json how can I use them
![Snipaste_2024-04-30_18-54-20](https://github.com/Stability-AI/StableSwarmUI/assets/131455899/637674d4-1e47-4b0f-b46d-5d334ad26f96)
I look forward to your help. Thank you very much

**Comment by Llin1028** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/131455899/90dbe503-4eae-437c-8d10-68adc7fae7e4)
I see that when using the comfyui workflow, the sampler cannot be adjusted here either

**Comment by mcmonkey4eva** [comment]
To select a translation, go to User -> User Settings -> select a Language from the dropdown.

To use comfy workflows in the generate tab hit this big shiny button
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/ba3ecb99-0348-4574-b3f9-e4e3fe48357a)

**Comment by Llin1028** [comment]
I'm sorry, I found that my user interface doesn't have a translation option, I suspect that my src folder is using a very old version, but the src folder in the beta is not complete, can you send me a full src folder?
