### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by Llin1028** [Stability-AI/StableSwarmUI#330]
I'm sorry, I found that my user interface doesn't have a translation option, I suspect that my src folder is using a very old version, but the src folder in the beta is not complete, can you send me a full src folder?

**Comment by Llin1028** [comment]
In addition, I found that when I switched to the comfyui interface, many plugins could not run, such as workflow management plugins, model preview plugins, etc., is there any way to make them run

**Comment by mcmonkey4eva** [comment]
- If you need to reinstall, follow the steps here: https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-windows
- If you have an old version, you can just run the update-windows.bat
- Comfy addons should all work on latest version, Manager is known to work.
