### ISSUE TITLE
VRam used without model loaded

### ISSUE THREAD

**Issue by filmgab** [Stability-AI/StableSwarmUI#332]
First I want to thank you for all the hard work. I love the UI.
Second, I was hessitant to even post this. I've been encountering an issue with stableswarm where it loads and keeps 146MiB into VRAM when launched. While this isn't a huge concern in terms of memory usage, the power draw is quite significant as my P40 GPU's consumption spikes from 9w to 50w upon loading anything into VRAM.

I've noticed that this increase in power consumption happens regardless of whether a model is loaded or not. I'm wondering if there are any settings within stableswarm that I can adjust to prevent it from using VRAM unless specifically needed for a model?

I'd appreciate any help in reducing the power draw when using stableswarm. Thank you all for your time and suggestions!

**Comment by mcmonkey4eva** [comment]
Most likely that'd be from pytorch loading in on the comfy backend, it'd be using that vram for it's core kernels and other essentials to function.

Sometimes the "free VRAM" button on the server info tab is all you need, but for the small kernel usage that probably isn't freeable.
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/289c69df-b15f-4c93-83be-ef4ca364086c)

If you want to get rid of all gpu connection without shutting down swarm, your next option is shut off the comfy backend (can be done from Server -> Backends in the UI), (but that sounds rather inconvenient vs shutting off swarm and starting it as-needed).

You could raise a request in https://github.com/comfyanonymous/ComfyUI about it but most likely you'll just get directed further back to https://github.com/pytorch/pytorch who will probably not care much about the small vram usage.
