### ISSUE TITLE
Allow larger values for Width/Height?

### ISSUE THREAD

**Issue by vertigoelectric** [Stability-AI/StableSwarmUI#335]
I'd like to try generating images at size 6400x1440.  I realize this isn't recommended, but I'd still like the option.  When I was using the ForgeUI it allowed me to enter such large values and generate images at that size.  In SwarmUI I get the following message:

> Invalid value for parameter Width: Invalid integer value for param Width - '6400' - must be between 128 and 4096

Changing the parameters in the user settings does not override this limit.  It appears to be hardcoded.

**Comment by mcmonkey4eva** [comment]
First, I question what/how you intend to generate at that resolution
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/699fdfde-de6e-4ee8-80a4-6a51b2479a34)

Second, I pushed a commit that raises the max to 16k, and instead sets a ViewMax for the reasonable range
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/8dcfc518-5028-421c-b1d6-02abc8efdc91)

Third, I note that it is a much better idea under most normal configurations to generate at 1mp and then use a refiner-upscale to obtain the target resolution

For example, these settings obtain the same resolution:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/f7acbfc7-9c92-4bae-8c34-0ab39c5dae36)

But generate a much more coherent image:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/9cf74567-6e5c-417c-a9b4-2f0e6671c55f)

Maybe higher control percentage, or maybe a slightly larger starting res (I did 1/4th here, maybe 1/3rd would be better) (or less wide aspect) would do even better, if you fiddle it.

Fourth, bonus note, testing this is the first time I've ever had a slow progress bar *on the VAE decode step*. Lol. Also has shown me a few minor issues with how the UI handles very-wide-aspect ratios that I need to fix now.
