### ISSUE TITLE
Two functional questions, please help me, thank you

### ISSUE THREAD

**Issue by Llin1028** [Stability-AI/StableSwarmUI#337]
Hello, I have two questions
The first problem is that after this thing is running, many comfyui plugins can't be used, such as the workflow plugin "comfyui-workspace-manager", I want to know, how to enable these plugins in the comfyui interface of SwarmUI.
![image](https://github.com/Stability-AI/StableSwarmUI/assets/131455899/c3e6ead0-f5b7-4145-8785-5d1d9bc5c537)

The second question is: I need a translation tool, the prompt word input window there, I want to type in German, and after typing, it will automatically become English, unlike the current English that can only be typed into the machine. It feels like a hassle
![image](https://github.com/Stability-AI/StableSwarmUI/assets/131455899/170f7851-1189-49bf-9877-4d165dde8df6)
Or is it possible that I'll change Swarmui to have input translation? But I haven't been able to find a file that can add this feature.

**Comment by mcmonkey4eva** [comment]
Adding automatic translations would be a feature request, please post that separately. It'd have to either run a local LLM or connect to a translations API (eg google translate). Alternately I believe Google Chrome has a built in translate option if you select text and right click it (that of course uses google translate), which might suffice for your needs?

---------------

Most comfy addons should work, there's been a few that broke but they've always gotten fixed once you point the developer of the relevant custom node repo to this comfy issue <https://github.com/comfyanonymous/ComfyUI/pull/867> which describes the most likely way things would break and how to fix it.
