### ISSUE TITLE
Docker mounting failing

### ISSUE THREAD

**Issue by AbduEhab** [Stability-AI/StableSwarmUI#338]
Here is the output when I run the docker script

![Screenshot_20240509_165946](https://github.com/Stability-AI/StableSwarmUI/assets/29149342/f282d019-7747-4c9e-a957-08d70738d93e)

Here is what I get when I try to modify the script:

![Screenshot_20240509_170144](https://github.com/Stability-AI/StableSwarmUI/assets/29149342/85dc9814-36d3-416a-b1cb-e4d815bac809)

**Comment by nightgrey** [comment]
The first log I don't know about, but the second message is not related to mounting, it is related to the GPU.

With NVIDIA GPUs, you have to install https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html so Docker can use the GPU.

But - you're using a Steam Deck, which uses an AMD APU. I don't know if this is supported by the underlying libraries (torch, etc.) or Docker.

If it is, there might be an equivalent to the NVIDIA Container Toolkit.

If not, you can remove the GPU parameter in launch-docker.sh and it should at least launch - but without GPU acceleration, there's probably even less of a chance of any generation being able to work.

I'd recommend researching Steam Deck specific Docker / Stable Diffusion specific advice.
