### ISSUE TITLE
Cant seem to connect to StabilityMatrix's hosted ComfyUI

### ISSUE THREAD

**Issue by zdaar** [Stability-AI/StableSwarmUI#342]
It used to work, as they officially support it and I ve been using it for a while. 
Now it does start the Self-Start ComfyYI backend correctly, but cannot connect to some API route, and no models are fetched. Image get generated if I select the only available sdxl1 default model, weirdly.

```
03:44:26.285 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:26.292 [Info] Creating new admin session 'local' for ::1
03:44:26.293 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:26.298 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:26.301 [Info] Creating new admin session 'local' for ::1
03:44:26.307 [Info] Creating new admin session 'local' for ::1
03:44:26.755 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:26.763 [Info] Creating new admin session 'local' for ::1
03:44:26.900 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:26.921 [Info] Creating new admin session 'local' for ::1
03:44:32.271 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:32.272 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:32.278 [Info] Creating new admin session 'local' for ::1
03:44:32.278 [Info] Creating new admin session 'local' for ::1
03:44:34.271 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:34.277 [Info] Creating new admin session 'local' for ::1
03:44:46.273 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
03:44:46.274 [Error] [WebAPI] Error handling API request '/API/ListBackends': Request input has unknown session id
03:44:46.281 [Info] Creating new admin session 'local' for ::1
03:44:55.275 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id
```

this is the error. 

I tried with my primary ComfyUI, with a fresh one installed just for this (through StabilityMatrix too), but always the same error, and No models get loaded (no error in the UI reflect this)

I can see my models list when I go to the Self-Started Comfy's Url

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4218386/72502180-9dfa-404f-bf97-fe705e02fa03)

but otherwise zero models 

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4218386/d4720b51-6061-4787-b1a9-268f8131bdc4)

I am not sure if there was a breaking change recently. Let me know if you think this is a problem on their end and Ill open an issue there too.

Tyvm

**Comment by mcmonkey4eva** [comment]
Those log messages look like a browser page refreshing repeatedly.

For Matrix automatic install / folder sharing, you'd want to file an issue with Matrix rather than here yeah.

You can probably just manually fix the settings (go to Server -> Server Configuration and point the model dirs at wherever your matrix models are at)

ftr swarm is very easy to stably install outside of tools like matrix https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-windows
