### ISSUE TITLE
pressing enter to finish auto-complete causes generation

### ISSUE THREAD

**Issue by yoinked-h** [Stability-AI/StableSwarmUI#343]
this shouldnt be intended i feel, maybe make it so you need to do control+enter to gen like in most webuis

https://github.com/Stability-AI/StableSwarmUI/assets/63889420/bee71d9c-d36c-48d5-951f-704d904ef306

mcmonkey pls fix :3

**Comment by mcmonkey4eva** [comment]
- it's tab completions. Use ya tab key.
- Fixed, enter on a tab-completion no longer triggers a gen

**Comment by mcmonkey4eva** [comment]
re control+enter, #344 seems nightgrey has the same preference, and added on something I didn't realize here: being able to use it while not selected into the prompt area but instead editing something else
