### ISSUE TITLE
Grid Generation - Aspect Ratio option used, but it generates the default ratio for each setting

### ISSUE THREAD

**Issue by brendanhoar** [Stability-AI/StableSwarmUI#346]
Default was set to 1:1.
Added Aspect Ratio to the list of variables for the Grid Generation.
Select all ratios.
Ran grid generation.
All ratios give the same image as 1:1.

**Comment by mcmonkey4eva** [comment]
That setting needs to be either hidden or special coded in grid gen, as it doesn't internally behave the way you'd expect.

**Comment by mcmonkey4eva** [comment]
This is the most broken grid i've ever generated lol, this is an upside down pyramid. But it works:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/9714e493-3711-4641-b7b6-bfb696e9c827)

**Comment by brendanhoar** [comment]
I was expecting a response telling me I was doing it wrong, not agreeing it didn't work and issuing a fix. lol.

Thanks!!!

One follow-up: does this fix work for both SD15 and SDXL?

Thanks
B

**Comment by mcmonkey4eva** [comment]
Yes, should work for all model types equally well.
