### ISSUE TITLE
Image Editor: make the size adjustable

### ISSUE THREAD

**Issue by FemBoxbrawl** [Stability-AI/StableSwarmUI#347]
Adjust size of image editor / empty image editor for more space etc.

**Comment by mcmonkey4eva** [comment]
re "zoom" in the title: you can zoom, just scroll wheel.

What I assume you probably want, is to be able to adjust the center bar -- currently it does a 50/50 split between the editor canvas and the output image, that should be adjustable.
Note that the left bar, right bar, and bottom bar are all collapsible, it's only the center bar that's not currently easily adjustable.

**Comment by mcmonkey4eva** [comment]
There's now a central size bar for the image editor

**Comment by FemBoxbrawl** [comment]
Thank you legend
