### ISSUE TITLE
Latest commit seems to have broken var_seed

### ISSUE THREAD

**Issue by lludlow** [Stability-AI/StableSwarmUI#348]
Latest commit seems to have broken var_seed, geting this when using -1
![image](https://github.com/Stability-AI/StableSwarmUI/assets/2191492/ba2fc702-72d0-439e-844a-6a7a8daf5e43)

`
"node_errors": {
    "10": {
      "errors": [
        {
          "type": "value_smaller_than_min",
          "message": "Value -1 smaller than min of 0",
          "details": "var_seed",
          "extra_info": {
            "input_name": "var_seed",
            "input_config": [
              "INT",
              {
                "default": 0,
                "min": 0,
                "max": 18446744073709551615
              }
            ],
            "received_value": -1
          }
        }
      ],
      "dependent_outputs": [
        "9"
      ],
      "class_type": "SwarmKSampler"
    },
`

**Comment by lludlow** [comment]
Ran the same genaration in comfy

![image](https://github.com/Stability-AI/StableSwarmUI/assets/2191492/a9489fb2-a7d5-4bc0-8ffe-6ec4ead51b5a)

**Comment by mcmonkey4eva** [comment]
The `||` to `&&` change was earlier and intentional (it's supposed to be `&&`, that was also mixed up in the refactor). The change above was removing the stray `!` and it does work, I tested to make sure.

**Comment by lludlow** [comment]
sorry, I was in the wrong dir... Thanks
