### ISSUE TITLE
Grid gen issue with using commas for prompt replace

### ISSUE THREAD

**Issue by rzfw** [Stability-AI/StableSwarmUI#350]
![ad](https://github.com/Stability-AI/StableSwarmUI/assets/154749888/679f1f93-5252-4b90-a3de-22d8df1b0682)

When trying to create a grid gen using prompt replace for different segment parameters, the commas within the syntax of the segment function are registered as dividers as seen in the image above

Im relatively new to this UI so I am unsure if I am using it incorrectly

**Comment by mcmonkey4eva** [comment]
This is mentioned in the grid generator docs https://github.com/Stability-AI/StableSwarmUI/blob/master/src/BuiltinExtensions/GridGenerator/README.md

Simply use `||` as a separator, and it will automatically switch to *only* `||` and treat your `,` as part of the input
