### ISSUE TITLE
[Feature Request] - Prompt delay

### ISSUE THREAD

**Issue by rzfw** [Stability-AI/StableSwarmUI#354]
Implementing Auto1111's prompt delay

[to:when]- adds to to the prompt after a fixed number of steps > (when)

[from::when]- removes from from the prompt after a fixed number > of steps (when)

**Comment by mcmonkey4eva** [comment]
Yes that's supported already https://github.com/Stability-AI/StableSwarmUI/discussions/11#discussioncomment-9206140
