### ISSUE TITLE
New Grid Generator Exception

### ISSUE THREAD

**Issue by MaideCa** [Stability-AI/StableSwarmUI#361]
A recent change to the Grid Extension broke the `Just Images` and `Grid Image` Output Type options.

I think we just need to add a missing `CreateDirectory` call above the `WriteAllBytes` call, but maybe there's a different place the folder was supposed to have been created?

This works for me:
```
if (!Directory.Exists(runner.BasePath))
{
    Directory.CreateDirectory(runner.BasePath);
}
```

See: https://github.com/Stability-AI/StableSwarmUI/commit/166fe548eeaf687ff38fd75f0e27162a2032a228#r142451172

**Comment by mcmonkey4eva** [comment]
Ohp, you're right, my bad, fixed
