### ISSUE TITLE
[Feature Request] - Include lora(s) name/filename in saving output image 

### ISSUE THREAD

**Issue by abclution** [Stability-AI/StableSwarmUI#365]
Currently if you add the parameter of [loras] to the filename output you get return the list object as part of the filename

ex - SystemCollectionsGenericList`1[System

ex for: 

raw/[year]-[month]-[day]/[year][month][day][hour][minute][second]_[prompt]_[model]_[loras]-[seed] 
it returns this filename

20240529181349_prompt text_wildcardxXLFusion_fusionsafetensors_SystemCollectionsGenericList`1[System-997719960.jpg

I'm evaluating loras effects on various models and would be super to be able to group by them on the file system.

**Comment by mcmonkey4eva** [comment]
works properly now

**Comment by mcmonkey4eva** [comment]
Actually^ made the code a bit better and added an option to skip folder names too

**Comment by abclution** [comment]
Amazing. Will test it out when I find some free time again to play with stable diffusion again. :)
