### ISSUE TITLE
ComfyUI API By URL uses wrong model name

### ISSUE THREAD

**Issue by Spybyte** [Stability-AI/StableSwarmUI#37]
If you want to work with a remote ComfyUI the name of the locally installed model is used instead of the remote model name.

I installed StableSwarmUI on my Mac and want to access a remote ComfyUI on my Linux box using ComfyUI API By URL. As soon as I want to generate an image ComfyUI on my Linux box is executed but I get the following error:

```
Failed to validate prompt for output 9:
* CheckpointLoaderSimple 4:
  - Value not in list: ckpt_name: 'OfficialStableDiffusion/sd_xl_base_1.0.safetensors' not in ['sd_xl_base_1.0.safetensors', 'sd_xl_refiner_1.0.safetensors']
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

```

So it uses the local path to the model from StableSwarmUI instead of the models installed on the remote machine.

**Comment by mcmonkey4eva** [comment]
Correct, it assumes the path is the same on all backends. I'm keeping the feature request of expanding it to support remote models open as #36
