### ISSUE TITLE
Load Image node is represented as text input in Generate tab

### ISSUE THREAD

**Issue by sanebg** [Stability-AI/StableSwarmUI#370]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/71310787/f0e3dca7-662d-453e-9299-365c5865683f)

![Screenshot of Image Generation - StableSwarmUI](https://github.com/Stability-AI/StableSwarmUI/assets/71310787/c9e75da7-cd97-4d45-b01a-8ff6c6624053)

Essentially rendering the workflow useless

**Comment by mcmonkey4eva** [comment]
This is intentional behavior that was requested by users - that's a filename input, useful for things like gridding files stored somewhere.
To get a direct image upload on swarm, you can either:
(A) use `SwarmLoadImageB64`, or
(B) build the workflow fully for swarm, ie using `SwarmInput` nodes, in which case use `SwarmInputImage`

**Comment by sanebg** [comment]
That's  ridiculous. It makes StableSwarm even more tedious to use than ComfyUI itself where at least I have an option.

StableSwarm was suppose to be more friendly for newbies and I hoped to introduce my low tech colleagues to Comfy via StableSwarm.

This sounds more like "it's not a bug, it's a feature"

**Comment by sanebg** [comment]
PS - Tried it with SwarmLoadImageB64, the workflow no longer works. "Invalid operation: Collection was modified; enumeration operation may not execute."

The swarmLoadImage is not supported by ICLight workflows.
Stop wasting resources on this joke, focus elsewhere.

**Comment by mcmonkey4eva** [comment]
I got notifications for some hostile replies here, I appreciate that you realized that was inappropriate and removed them.

If you're encountering bugs/limitations let's work to fix them.
If the available featureset doesn't cover you needs, please constructively explain what you'd need so we can find a way to support your needs properly
