### ISSUE TITLE
We can expect SwarmUI to support SD3 at first release date right?

### ISSUE THREAD

**Issue by FurkanGozukara** [Stability-AI/StableSwarmUI#373]
I am planning to make a tutorial and invest time in SwarmUI

We can expect SD3 to be support as in first day? Thank you

**Comment by mcmonkey4eva** [comment]
Yep!

There's also already API support (see here https://github.com/Stability-AI/StableSwarmUI/issues/308 )

And pre-emptive recognition for SD3 model arch ( https://github.com/Stability-AI/StableSwarmUI/commit/593a8d8c87977ccaeb3e1289009dfd6d4dba1369 ) and partial workflow gen code preppd for SD3 ( https://github.com/Stability-AI/StableSwarmUI/commit/b7bd543c5c88fc48419255a64b1e51f8cf42b42c )
Final full support will be pushed on launch day.

You can join the Discord @ https://discord.gg/q2y38cqjNw to see the announcement post immediately when it's ready, or just hit "Update and Restart" on the Server tab after the SD3 models are out (if all goes according to plan, model release and code release across all relevant projects should all be within a few hours of each other)
