### ISSUE TITLE
When using a BBOX YOLO model, only one face is inpainted

### ISSUE THREAD

**Issue by Sisimshow** [Stability-AI/StableSwarmUI#374]
I hate doing this since you added this for me (and very promptly!) but there does seem to be a small issue with using a BBOX model with the `<segment>` command. With a seg model, it makes a mask that covers both faces so they both get inpainted. With a BBOX model, only one face gets a mask so only one face gets inpainted. Below is an example. I used `<segment:yolo-facesv4.pt,0.5,0.7>` which doesn't have the parameter declaring a certain mask should be selected and inpainted (unlike `<segment:yolo-facesv4.pt-1,0.5,0.7>` so in theory multiple should be done.

I'll be honest, for me this isn't a huge problem because I usually only create one person at a time, but sometimes you get a false positive and their actual face gets skipped. So I wanted to bring this to your attention, I would call it a low priority to fix. Thank you so much for the work you've already done :)

BBOX mask
![18-59-11-2 women, shirt, pantssegmentyolo-face_-SDXLDreamshaperXLLightning-1541208248](https://github.com/Stability-AI/StableSwarmUI/assets/126213271/b8380bc1-0e13-4d29-b5a4-2af11b31b778)

SEG mask
![18-59-08-2 women, shirt, pantssegmentyolo-face_-SDXLDreamshaperXLLightning-1541208248](https://github.com/Stability-AI/StableSwarmUI/assets/126213271/a75e8494-9f6a-401e-b326-7f1cb5e7c975)

Picture
![18-59-13-2 women, shirt, pantssegmentyolo-face_-SDXLDreamshaperXLLightning-1541208248](https://github.com/Stability-AI/StableSwarmUI/assets/126213271/f9382dde-9bb6-4b6a-ab45-a5ec99cc9dce)

**Comment by mcmonkey4eva** [comment]
Oh, true, my bad -- fixed!

**Comment by Sisimshow** [comment]
You truly are the best :) thank you!
