### ISSUE TITLE
[Feature request] Slideshow mode

### ISSUE THREAD

**Issue by thradya** [Stability-AI/StableSwarmUI#378]
Would it be possible to either:

1) add a new toggle below "auto swap to images" that allows for swapping images in full screen browsing
2) add an option to scale images beyond their native size in default view (current vs lazy mock-up attached)

First option is the default behaviour in Forge and it's the only feature I'm missing.

For context - I have a 4k display and in default view (which has an option for auto swapping to latest generation) last generated image is rather tiny. Not really useful for "monitoring" what Swam is generating. On the other hand - in full screen browsing mode the image is large enough but it's not swapping to the latest generation. Which is a bummer.

![tiny_swarm](https://github.com/Stability-AI/StableSwarmUI/assets/72419924/1725b98b-6e0c-4f17-957c-ab5e2d61ade1)
![biggie_swarm](https://github.com/Stability-AI/StableSwarmUI/assets/72419924/e5bac26b-1195-4936-928e-9383ec1d7704)

**Comment by mcmonkey4eva** [comment]
I've added a new user setting `CenterImageAlwaysGrow` which will fix the _image won't fill space on a 4k monitor_ issue

**Comment by mcmonkey4eva** [comment]
And also user setting `AutoSwapImagesIncludesFullView` for the other part

**Comment by thradya** [comment]
Jesus, a commit in 25 minutes flat should be fucking illegal. You're making us all look bad :|

Thank you! Much appreciated!
