### ISSUE TITLE
Lora weights

### ISSUE THREAD

**Issue by FFouetil** [Stability-AI/StableSwarmUI#38]
Hey!
I've been trying to change LoRA weights but whatever I do, it always defaults to 1 (I've seen it used as default value somewhere in the code), but I couldn't find out if it's a bug or just me not writing the value correctly in this window:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/11708007/a514b8c4-b236-40a3-91b8-f1c1f61fed15)

The document doesn't mention anything about that yet (noticed it was added very recently), so I've tried both directly inputing a value alone, and adding the LoRA before it. Also tried only positive decimal values just to make sure. But nope, always 1.
Does this input field actually work, or is it a placeholder? Changing the content doesn't seem to do anything, as even click Generate Image will just output the latest render without running the process.

**Comment by cerarslan** [comment]
Hi mate! look at that issue. It will solve your problem. https://github.com/Stability-AI/StableSwarmUI/issues/26

**Comment by mcmonkey4eva** [comment]
Did that^
