### ISSUE TITLE
Feature request: add shortcuts for tools of the image editor

### ISSUE THREAD

**Issue by FemBoxbrawl** [Stability-AI/StableSwarmUI#381]
I was thinking to make things more efficient with the image editor, maybe we could add shortcuts for the eraser and the pen, as well as the color picker?

B = brush
E = eraser
I = color picker (or whichever key you think fits best to it)

I was thinking this because it would make things more efficient.

hope you add this!

**Comment by mcmonkey4eva** [comment]
Good idea -- added hotkeys for all the tools.

Note color picker tool doesn't exist yet, and the brush's color selector is a placeholder (need a proper interface, browser default color picker sucks)
