### ISSUE TITLE
SD3, upscaling factor incompatibility?

### ISSUE THREAD

**Issue by snottyone** [Stability-AI/StableSwarmUI#387]
with refiner do tiling enabled,  upscale factors 1.25 and 1.75 lead to:
`Invalid operation: ComfyUI execution error: division by zero`
(1.5 and 2.0 work)

**Comment by mcmonkey4eva** [comment]
Can't replicate? need more info

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/0fac1f12-696c-4fa3-ac0e-5a8f5a2679b4)

**Comment by snottyone** [comment]
didn't make a screenshot at the time, and can't replicate it either, must have been a fluke
please close issue and sorry
