### ISSUE TITLE
torchsde-0.2.5 issue when installation some custom nodes

### ISSUE THREAD

**Issue by cerarslan** [Stability-AI/StableSwarmUI#39]
When I try to install some custom node I get this error 'DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour...'' 

Here is the solution:
Go: C:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torchsde-0.2.5.dist-info and edit METADATA via notepad. Then scroll 'line 18' You should see '    Requires-Dist: numpy (>=1.19.*) ; python_version >= "3.7"    ' and change this one to Requires-Dist: numpy (>=**1.19)** ; python_version >= "3.7"

You just delete  --->    .*

**Comment by mcmonkey4eva** [comment]
That shouldn't _break_ anything from working, just nag you, unless  there's something more to it
