### ISSUE TITLE
when using sd3 if automatically downloading encoder can be disabled?

### ISSUE THREAD

**Issue by Red-Scarff** [Stability-AI/StableSwarmUI#392]
When trying to use sd3, I face a problem that I cannot auto downloading encoder because I cannot access to huggingface in my country.  It is abandoned here. Well I can download a encoder through a mirror site, but in so many python files I cannot find where to change the download website or just disable the auto downloading function. These files are too complicated. Can anyone give me a hand?

**Comment by mcmonkey4eva** [comment]
If you have one of the SD3 models that has baked in textencs, just update swarm - a few hours ago today it was fixed to not autodownload tencs if you have them in the model (this was posted in the discord announcements channel btw https://discord.gg/q2y38cqjNw ).

If not you can always just download the tencs from any other site (eg civitai's upload of sd3 medium includes separate downloads for the tencs) and save them in the folder `(Swarm)/Models/clip/` with filenames: `clip_g_sdxl_base.safetensors`, `clip_l_sdxl_base.safetensors`, `t5xxl_enconly.safetensors`

**Comment by Red-Scarff** [comment]
thanks for being so patient.

**Comment by Red-Scarff** [comment]
> If you have one of the SD3 models that has baked in textencs, just update swarm - a few hours ago today it was fixed to not autodownload tencs if you have them in the model (this was posted in the discord announcements channel btw https://discord.gg/q2y38cqjNw ).
> 
> If not you can always just download the tencs from any other site (eg civitai's upload of sd3 medium includes separate downloads for the tencs) and save them in the folder `(Swarm)/Models/clip/` with filenames: `clip_g_sdxl_base.safetensors`, `clip_l_sdxl_base.safetensors`, `t5xxl_enconly.safetensors`

thanks for being so patient.
