### ISSUE TITLE
Difference between Stable Swarm and AI Horde

### ISSUE THREAD

**Issue by db0** [Stability-AI/StableSwarmUI#4]
[AI Horde](https://aihorde.net) is a mature REST API which already provides the primary functionality the Stable Swarm aims to achieve, allowing distributed GPUs to be used by the same user. Only it goes much further and allows multiple GPUs to be be used by any number of users. 

It seems that you could use the AI Horde to handle the aggregation and then simply build the Swarm UI as a frontend in front of it.

I am just curious why this was developed from scratch instead of using an existing FOSS tool which could speed up the development aims of this tool

**Comment by mcmonkey4eva** [comment]
This users your own GPUs with unrestricted access to settings as deep as you want to go, in a neat cleanly packaged wrapper.
As opposed to horde which uses public GPUs and naturally needs reasonable access restrictions to prevent abuse.
Additionally, the part of the project that was used for the name and the headline is not the only focus of the project, there's several overlapping goals, that was just the easiest headline.

This originally started development as a hacking ground for internal Stability usage, and so any tool not 100% internal to us and not giving us 100% direct and instantly internal access was insufficient.

**Comment by db0** [comment]
Just FYI  the AI Horde can be hosted internally by anyone and used unrestricted in the same way you expect and it's open source allows access to all parts of the internals. I am also currently helping stability.ai (Joe's Team) with this kind of clustered inference. It might be worth collaborating as there's a lot of development you would be able to bypass.
