### ISSUE TITLE
Backend usage timeout, all backends occupied

### ISSUE THREAD

**Issue by realcarlos** [Stability-AI/StableSwarmUI#40]
I am installing StableSwarmUI on my A100 40G DGX Station , Ubuntu 22.04, and it always says: "No backends present. You must configure backends in the Backends section of the Server tab before you can continue." "Some backends are disabled. Please configure them to continue." , what should I do?

**Comment by realcarlos** [comment]
![Screenshot from 2023-08-08 18-14-15](https://github.com/Stability-AI/StableSwarmUI/assets/13853/b5387102-484a-448c-ab67-14a4cda91089)

**Comment by mcmonkey4eva** [comment]
Check the main program console, it would have an error message explaining why the backend failed to start.
