### ISSUE TITLE
Feature request: place most recent commit datetime value somewhere on the main UI, to help with diagnosing update-failure caused issues

### ISSUE THREAD

**Issue by brendanhoar** [Stability-AI/StableSwarmUI#401]
As per discord, it may be a good idea to present in the main UI the datetime value of the most recent commit pulled to the client machine (captured at startup), since we're all effectively on a dev-type branch at the moment and the version number is updated infrequently relative to commits.  Might save some aggravation for the developer(s) w/r/t requests for assistance. :)

B

**Comment by mcmonkey4eva** [comment]
Commit date is now in the corner and in the logs!
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/9671be3f-6c47-42fa-a14f-2fa951016f89)
