### ISSUE TITLE
After installation and restart the launch-linux.sh, error came out.

### ISSUE THREAD

**Issue by guquandaju012** [Stability-AI/StableSwarmUI#402]
After running the following command

"sh launch-linux.sh" 

the following error came out, anyone have solution for this?

launch-linux.sh: 4: Bad substitution
launch-linux.sh: 35: dotnet: not found
launch-linux.sh: 44: dotnet: not found
launch-linux.sh: 47: [: 127: unexpected operator

Thanks a lot.

**Comment by mcmonkey4eva** [comment]
it's a `bash` script, and you need to follow the install instructions in the readme https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-linux
