### ISSUE TITLE
In OutPathBuilder, [model] is defined as "model name", however this parameter includes a subpath component. Proposal to add [model_filename].

### ISSUE THREAD

**Issue by brendanhoar** [Stability-AI/StableSwarmUI#404]
For the purposes of the below, assume agreement on leaving out the file extension.

Issue:
I would like to use the model filename as part of my OutPathBuilder format string. As per the on screen documentation, [model] is defined as "model name". However, in reality [model] is "full sub path to model under the top level model directory."

Example/Request:
And since a picture is worth a thousand words, see yellow highlighted bits in the example below. In this example I would have preferred to only see [model] return "picxReal_10" instead of "_offload_i_sd15picxReal_10". Since [model] is already defined the way it is, I propose adding [model_filename] that does what I am requesting, which does not use the intervening directories in the output string. 

1. The definition of [model] is shown in GUI, as well as the example format string I entered:

![filenaming_01](https://github.com/Stability-AI/StableSwarmUI/assets/8979139/7414ea18-b4be-4a84-a5f2-e8d6230b03ef)

The generation screen showing the model sub-path:

![filenaming_02](https://github.com/Stability-AI/StableSwarmUI/assets/8979139/e271613a-1c24-4e2e-8655-d87451328952)

The resulting output path assigned to the image file, with the subpath component (slashes stripped) that I do not want:

![filenaming_04](https://github.com/Stability-AI/StableSwarmUI/assets/8979139/4f9f942a-4264-4b49-b634-10ecf8799923)

PS - if proposed enhancement is accepted, the on-screen documentation for [model] would obviously need to be updated.

**Comment by mcmonkey4eva** [comment]
Oh that'd be `[model_title]`
The full documentation for out path builder didn't fit in a popup so the popup just links https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/User%20Settings.md#path-format which documents model_title
```
[model]: the filename of the model
[model_title]: the metadata title of the model
```

*I've fixed the link to be clickable instead of just text of the url, heh

**Comment by brendanhoar** [comment]
No, that's not what I am asking for.

I am requesting the model filename (**at the operating system level**), not anything from the internal metadata.

B

**Comment by mcmonkey4eva** [comment]
You want... the filename, but not the full filename, and not the title either... why so specific? 0.o

**Comment by brendanhoar** [comment]
Basically:

Here are things that are the **filename**:
picxReal_10.safetensors

Here are things that are **not the filename**:
This OS-view file path is: G:\___all_webuis\StableSwarmUI\Models\Stable-Diffusion\_offload_i\_sd15\picxReal_10.safetensors
This app-view file path is: _offload_i\_sd15\picxReal_10.safetensors

I do not want any of the **directory** parts of the path, only the file name component.

`There are only two hard things in Computer Science: cache invalidation and naming things.

-- Phil Karlton`

**Comment by mcmonkey4eva** [comment]
My question was _why_

**Comment by brendanhoar** [comment]
> My question was _why_

Short version #1:
Well, at some point model organizing will become several more directory layers deep and it will just be too much noise in the filename. My policy is not to change data inside the files (e.g. metadata edits) as I have a slow side project of comparing hashes of files *and* file components.

Short version #2:
I've always done it that way with A1111.

**Comment by mcmonkey4eva** [comment]
If you haven't customized metadata on the model, the title _is_ the filename without directory info

**Comment by brendanhoar** [comment]
That may be the case most of the time, but I have downloaded files which display a "Title" that does not match the filename. I think is only the filename under certain metadata conditions?

![filenaming_06](https://github.com/Stability-AI/StableSwarmUI/assets/8979139/8e3c73ef-4475-4c77-94c4-4131a227abf1)

B

**Comment by mcmonkey4eva** [comment]
yes the uploader set a title on their model

**Comment by mcmonkey4eva** [comment]
oh this is delayed for me to remember sorry, but that's what this option is for:

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/eed3180f-dfdf-4b10-9c8b-ef32ac9b851e)

**Comment by brendanhoar** [comment]
lol ok thanks man, I should have investigated more. :) 

B
