### ISSUE TITLE
swarmsaveimagews node in workflow does not appear to be saving

### ISSUE THREAD

**Issue by mike4llison** [Stability-AI/StableSwarmUI#405]
I have been creating A LOT of images in the comfy workflow tabe, some really good ones too. Then I went to go find them and for the life of me I cannot find them within the Swarm directory. I was using the default swarmsaveimagews node and I have found the output directories `StableSwarmUI\dlbackend\comfy\ComfyUI\output` and `StableSwarmUI\Output\local\raw` none of which contain the generations. Am I missing something here or are the generations of the last few days gone forever? The only information I get from the console is...

```
13:58:47.617 [Info] Sent Comfy backend direct prompt requested to backend #0 (from user local)
13:59:07.128 [Info] Sent Comfy backend direct prompt requested to backend #0 (from user local)
14:03:22.329 [Info] Sent Comfy backend direct prompt requested to backend #0 (from user local)
14:06:12.278 [Info] Sent Comfy backend direct prompt requested to backend #0 (from user local)
14:13:24.712 [Info] Sent Comfy backend direct prompt requested to backend #0 (from user local)
14:18:56.256 [Info] Sent Comfy backend direct prompt requested to backend #0 (from user local)
```
and the feed is empty. When I connect to the default Comfy save image node, it works as expected and it saves to the aformentioned `StableSwarmUI\dlbackend\comfy\ComfyUI\output` directory.

from what I can tell the swarmsaveimagews node is to send it to the generate tab.

I am sorry if this seems trivial but I would really love to retrieve these images somehow and I have exhausted my ideas for solutions including searching online and in the issues tab here.

I appreciate any assistance that anyone can give.

**Comment by mcmonkey4eva** [comment]
SwarmSaveImageWS is meant for usage with porting the workflow to the Swarm Generate or Simple tabs, when used directly on the comfy tab it does not actually save to file anywhere.
You'd want the comfy standard `Save Image` node for having images auto save when working directly in the comfy tab.

So I'm sorry to inform you that your past images are gone :(

The comfy team are currently looking into adding node help docs that work like the `?` hint buttons on swarm's parameters&settings, and once integrated hopefully that will help save confusion from future users in regards to what different nodes do.
