### ISSUE TITLE
There is no "PixArtMS Sigma XL 2" option

### ISSUE THREAD

**Issue by matbee-eth** [Stability-AI/StableSwarmUI#406]

**Comment by mcmonkey4eva** [comment]
it was added earlier today, so make sure your swarm is updated (Server -> Update & Restart)

**Comment by matbee-eth** [comment]
I'm not stupid.

```
StableSwarmUI git:(master) ✗ git pull
Already up to date.
```
<img width="645" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/381356/86fb1e4e-25a6-4901-a91d-b6812d346dc9">

<img width="1623" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/381356/546d5f5a-458b-4aed-bc6d-cac57db3a91f">

**Comment by mcmonkey4eva** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/46068e12-b797-4d18-826e-b9e90189634c)

The current version is `0.6.4.1`

Just doing a `git pull` doesn't necessarily *build* the update, there is an update button in the UI and update scripts in the folder

**Comment by matbee-eth** [comment]
<img width="664" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/381356/c8349161-4d70-4f6e-a97c-f2079f6afaf8">

**Comment by mcmonkey4eva** [comment]
Yes, now that you've built it, launch swarm again and you should be good

**Comment by matbee-eth** [comment]
No, I actually am stupid, I am SSH'd in and manually killing the python process PID, it didnt kill the swarm process
