### ISSUE TITLE
"SwarmClipTextEncodeAdvanced" this comfy node is not compatible with StableSwarmUI Advanced Prompt Syntax?

### ISSUE THREAD

**Issue by suede299** [Stability-AI/StableSwarmUI#408]
Can the Advanced Prompt Syntax listed in doc only be used in the generation of StableSwarmUI?

**Comment by mcmonkey4eva** [comment]
Yes that syntax is for the `Generate` tab. On the inside it works by modifying how swarm auto-generates the workflow, it wouldn't work as a single node on its own

The swarm text encode node is for processing the auto-webui-style timestep editing from https://github.com/Stability-AI/StableSwarmUI/discussions/11#discussioncomment-9206140
