### ISSUE TITLE
[Feature Request] Add adetailer in the generate tab

### ISSUE THREAD

**Issue by TheForgotten69** [Stability-AI/StableSwarmUI#419]
I think adding a detailler tab inside the generate part would do wonder

**Comment by mcmonkey4eva** [comment]
That's called _Auto Segmentation_ in Swarm.
It's documented here: https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Features/Prompt%20Syntax.md#automatic-segmentation-and-refining

if you want to be super close to the original ADetailer extension, use a YOLOv8 model
