### ISSUE TITLE
I want to reinstall Swarmui

### ISSUE THREAD

**Issue by kingsae1** [Stability-AI/StableSwarmUI#420]
It is cached somewhere and cannot be reinstalled. No matter how many times I restart, the UI that the installation is complete appears.
Is there a way to uninstall and reinstall? (I am using Docker)

**Comment by mcmonkey4eva** [comment]
If using Docker, check the docker interface, it does indeed save docker images somewhere that you have to clear. On Windows there's a desktop gui for it,

on Linux you need terminal commands... `docker images | grep swarm` I think then `docker rmi (put the id of the swarm image here)`
