### ISSUE TITLE
Attempting to use a ComfyUI Server Running In Runpod Unable To Get Models To Work

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [Stability-AI/StableSwarmUI#423]
Hello, you all trying to think of solutions to access my server I am working on as a discord bot quickly from my computer to update internally.

I can use the custom back and put the URL

if I go to the comfy it works great.

Then I attempted basic workflow then used this workflow for UI and it did not accept the model

Does anyone know what I am missing in short

I would like to be able to use Swarm and just turn on backends as needed to make art and just overall provide maintenance.

Thank you for the help.

**Comment by mcmonkey4eva** [comment]
You need the model to exist in the Models folder of the server. So when using runpod, you have to upload the model to the server. Or, if the model is a public one on HF/civitai/whatever, you can use Utilities -> Model Downloader to download it to the server (probably faster than using your home internet upload for most people).
