### ISSUE TITLE
为何打不开0.0.0.0访问，修改后依然返回localhost

### ISSUE THREAD

**Issue by night666e** [Stability-AI/StableSwarmUI#425]

**Comment by night666e** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/125663783/85566651-9bbb-463d-8e18-ae3dbae64007)

**Comment by mcmonkey4eva** [comment]
on a remote server without a display? Use `--launch_mode none --host 0.0.0.0`, leave default port `7801` unless you have a very good reason to change, `8088` would overlap with other things

See also https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Command%20Line%20Arguments.md
and https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Advanced%20Usage.md

**Comment by night666e** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/125663783/c45319cb-3f83-48a3-a8bf-bf457640a5e7)
这是什么情况

**Comment by mcmonkey4eva** [comment]
you copied some random text into cli args
