### ISSUE TITLE
Add Ctrl+click form pull-down lists to allow multiple selection

### ISSUE THREAD

**Issue by rafstahelin** [Stability-AI/StableSwarmUI#428]
When selecting multiple items, such as Loras or samplers, the current process of individually selecting each item, adding a comma, and repeating can be time-consuming, especially when choosing 10 or 20 items.

I propose implementing a system that allows for multi-selection of items using the standard Ctrl key functionality. This would enable users to select multiple items simultaneously, significantly improving efficiency and reducing the time required for the selection process.

**Comment by mcmonkey4eva** [comment]
Swarm issues are now tracked at https://github.com/mcmonkeyprojects/SwarmUI
