### ISSUE TITLE
Backend don't find Models when ModelRoot is changed.

### ISSUE THREAD

**Issue by PietroPizzi69** [Stability-AI/StableSwarmUI#429]
Hi,

Is something wrong with my config or is it not really possible to have the Models outside?

My Install is on Windows. I used the Install-Windows.bat in C:\Apps now I have it installed under C:\Apps\StableSwarmUI\ .

My Models are in: D:\AI-Art\StableDiffusion-Resources\Stable-Diffusion
I set the ModelRoot to: D:\AI-Art\StableDiffusion-Resources
And the SDModelFolder to: Stable-Diffusion

When i refresh the models unter Generate it finds it. I picked DreamShaperXL_v21TurboDPMSDE.safetensors. Now when I write somthing in Promt and hit Generate a Error popup appears:
Invalid operation: No backends match the settings of the request given! Backends refused for the following reason(s):
- Request requires model 'DreamShaperXL_v21TurboDPMSDE.safetensors' but the backend does not have that model

(When I copy the Model to ./Models/Stable-Diffusion and set the ModelRoot to Models all works, incl. the Outputpath in another directory: D:\AI-Art\StableDiffusion-Outputs)

Do anybody know if this is a Bug or how it is fixable?

**Comment by PietroPizzi69** [comment]
Sorry. My bad! A Windows reboot did the trick.

**Comment by mcmonkey4eva** [comment]
Just needed a swarm or backend restart but full PC works too lol
