### ISSUE TITLE
Upscale without refine?

### ISSUE THREAD

**Issue by richardtallent** [Stability-AI/StableSwarmUI#433]
In A1111, my normal approach was to not use refiner steps, but to just to a 2x Lanczos directly on the output from the model before saving.

However, in StableSwarmUI, there doesn't seem to be a way to skip the refining part and *just* upscale:

- Trying to choose "---" as the refiner model leads to an error
- Setting `Refiner Control Percentage` to `0` leads to no upscaling
- Using the "2x" button in the More menu for the preview image also runs the refiner
- Playing with Refiner Method had no effect.

Am I missing a nuance in the UI?

**Comment by mcmonkey4eva** [comment]
Did you miss the readme migration notice? https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#migration-notice
https://github.com/mcmonkeyprojects/SwarmUI/discussions/2

**Comment by richardtallent** [comment]
Whoops! I knew about it, but somehow ended up with the wrong one open. Will re-file.
