### ISSUE TITLE
Communication Request

### ISSUE THREAD

**Issue by ultraxia** [Stability-AI/StableSwarmUI#452]
Hello,

I am interested in becoming a sponsor for your project on GitHub. Could you please provide your contact information such as Discord or email where we can discuss this further?

My email address is ultraxia@foxmail.com, and my Discord handle is @ultrazett.

Thank you!

**Comment by mcmonkey4eva** [comment]
Did you miss the readme migration notice? https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#migration-notice
https://github.com/mcmonkeyprojects/SwarmUI/discussions/2
