### ISSUE TITLE
CivitAI URLs not recognised

### ISSUE THREAD

**Issue by zygote279** [Stability-AI/StableSwarmUI#454]
Sure I'm doing something silly, but fresh install and adding a test model URL from CivitAI and I'm getting errors in the model downloader?

![image](https://github.com/user-attachments/assets/24045243-d1b1-4d90-aefa-0d354fd8e11e)

Any ideas what I'm missing?

**Comment by jwax33** [comment]
Civitai made some changes and broke downloading.  McMonkey pushed a quick fix through tonight.  If you haven't, run the update script or git pull to grab the latest changes and you should be able to download again.

**Comment by zygote279** [comment]
Ah brilliant, good to know it's not just me then!
