### ISSUE TITLE
[Error] Failed to load resource: bootstrap.bundle.min.js.map, line 0)

### ISSUE THREAD

**Issue by olivierlacan** [Stability-AI/StableSwarmUI#46]
Seeing this error in the JS console both during the installation process (backend setup) and in the UI after setup is complete. 

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.bundle.min.js.map, line 0)
```

There are other errors in the console but this is the one I've seen most consistently, running latest commit from `master` here on a fully cleaned (`git clean -fdx`) repo:

```
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (object_info, line 0)
http://localhost:7801/ComfyBackendDirect/object_info
```

```
TypeError: backendsListView.checkVisibility is not a function. (In 'backendsListView.checkVisibility()', 'backendsListView.checkVisibility' is undefined)
http://localhost:7801/js/backends.js?vary=0.5.3.0 (backends.js:165)
```

**Comment by mcmonkey4eva** [comment]
The checkVis you already fixed, 

The comfy one seems to indicate trying to load comfy before backends are ready, which is normal and there's a "Try Again" button for if you did that.

The bootstrap one should be fixed by the commit above.

**Comment by olivierlacan** [comment]
Thanks, nice turnaround time 😛
