### ISSUE TITLE
IP Adapter "FaceID Portrait" for style transfer not found and does not download

### ISSUE THREAD

**Issue by Griphen116** [Stability-AI/StableSwarmUI#461]
![image](https://github.com/user-attachments/assets/d20b1c0f-5edb-4704-bfb0-81098f392236)

![image](https://github.com/user-attachments/assets/0d1f86de-99aa-4da0-8d2a-ab2e669ab25f)

Tried using FaceID Portrait and it kept saying the IP Adaapter Model is not found, it was not downloaded automatically either.

Looking in my Models folder, only these models were present:
![image](https://github.com/user-attachments/assets/bc0459b5-0b30-407a-8e10-9e820c84b9ca)

**Comment by mcmonkey4eva** [comment]
Did you miss the readme migration notice? https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#migration-notice
https://github.com/mcmonkeyprojects/SwarmUI/discussions/2
