### ISSUE TITLE
(Windows 10) The install downloads the files but then does not open properly.

### ISSUE THREAD

**Issue by mackiskool** [Stability-AI/StableSwarmUI#5]
I followed the instructions on how to download the UI. It does not open a browser and instead quickly opens and then closes the command prompt which would have let it start.

I have nothing else I can add here.

**Comment by mcmonkey4eva** [comment]
Have you tried, uh, just running it again? Sometimes it needs to be ran twice.

If it repeatedly files, try opening a command prompt window to the folder and trigger the script from there (so that the window stays open and you can see what error message it might give)

**Comment by mackiskool** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/130073167/8517b417-82ae-4d05-9683-4f5f650f99fe)

This is what I get back from doing that.

I'll go through with downloading that.

**Comment by mackiskool** [comment]
![image](https://github.com/Stability-AI/StableSwarmUI/assets/130073167/bb5ed987-1163-4021-bfdf-747d01946c78)
I already have this installed actually.

**Comment by mackiskool** [comment]
I tried to repair it but nothing changed.

**Comment by mcmonkey4eva** [comment]
Possibly uninstall and reinstall?

Sorry i'm not sure why... dotnet would just fail to install or function. You'd think a library created by Microsoft would just work :tm: on Microsoft's operating system...

**Comment by mackiskool** [comment]
> Possibly uninstall and reinstall?
> 
> Sorry i'm not sure why... dotnet would just fail to install or function. You'd think a library created by Microsoft would just work :tm: on Microsoft's operating system...

I have uninstalled and reinstalled both the runtime version and the use version.

Over time there will be tutorials on how to install this. I will also ask my friends I'd they can help me install it.

**Comment by mcmonkey4eva** [comment]
If it's still not working, check https://github.com/Stability-AI/StableSwarmUI/issues/2 

> After uninstalling every instance of .NET SDK, .NET, ASP.NET and Microsoft Windows Desktop Runtime, and then reinstalling just the SDK, running install-windows.bat, and running launch-windows.bat --launch_mode webinstall, it still didn't work. ran it three more times, still no. deleted folder, grabbed newest install-windows.bat and ran it. didn't work. deleted folder and ran it again and then launch-windows.bat --launch_mode webinstall. still didn't work. deleted the folder, ran install-windows.bat and, at this point, i was out of ideas, so I tried just double-clicking launch-windows.bat instead of the launch-windows.bat --launch_mode webinstall and now it's working.

Let me know if that (or anything else) fixes it for you. Whatever the consistent final solution is I'd like to have either run itself or at least documented.
