### ISSUE TITLE
Won't load my backend, won't let me configure a new one.

### ISSUE THREAD

**Issue by AIMusicExperiment** [Stability-AI/StableSwarmUI#50]
Since this latest update my backend isn't loading and it says that I have no backend, When I try to configure one, it doesn't bring up the interface.

**Comment by mcmonkey4eva** [comment]
Huh? Can you... give some more info here?
Probably a screenshot of the console window and the UI?

**Comment by AIMusicExperiment** [comment]
It was fixed in the next commit, it is working fine now. Thanks for all you do,!
