### ISSUE TITLE
Scrolling not working on installer on Colab

### ISSUE THREAD

**Issue by LukeOvermind** [Stability-AI/StableSwarmUI#51]
When running colab either temporay install or Google Drive install, at the installer landing page with the Stable Diffusion Model License agreement, I am unable to to scroll down to click agree and move on to the next step.

Tested both in Chrome and Edge same thing

**Comment by danielfrg** [comment]
I see the same thing.
Using commit a8af246552410e9c04ff972364d45ef90480aafc works for me

**Comment by LukeOvermind** [comment]
> I see the same thing. Using commit [a8af246](https://github.com/Stability-AI/StableSwarmUI/commit/a8af246552410e9c04ff972364d45ef90480aafc) works for me

Hi Daniel

I got around it by using the browser zooming out function. 
Not very technical, how do you use a specific commit? 
Also, how are you using the colab?  I tried to install on my Drive which worked, however I ran into trouble if I try to run it a second time after install

**Comment by olivierlacan** [comment]
Fixed this in #52, will be good when it's merged but in the meantime you can remove `position: fixed;` in `src/wwwroot/css/site.css`: https://github.com/olivierlacan/StableSwarmUI/blob/0501a42d4723dd122f2fd4c6fa6a96e139477048/src/wwwroot/css/site.css#L11-L11

**Comment by mcmonkey4eva** [comment]
Fixed in https://github.com/Stability-AI/StableSwarmUI/commit/7d80c95d6fa7eda8e76e41464785967db9645d1e
