### ISSUE TITLE
Placeholder shows in place of generated image 

### ISSUE THREAD

**Issue by olivierlacan** [Stability-AI/StableSwarmUI#55]
A placeholder image shows up in the output view initially before any previews start appearing (a nice touch BTW), but that placeholder image seems to remain in the DOM by mistake even after the final output is sent which yields this bug: 

<img width="1352" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/65950/aeba04c0-9d13-45f2-8c03-9fd6ce10e9b2">

When you click on the output: 

<img width="1348" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/65950/3a70d16d-5674-44a3-bfaa-9a43ef0edee6">

A quick check shows the popup modal does have the placeholder image in it in the DOM: 
<img width="768" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/65950/4b62be1d-ee85-492c-a23c-b7eb5cc0fe70">. So I think I have a way to fix this.

**Comment by mcmonkey4eva** [comment]
I believe this is fixed as of the commits today.

**Comment by olivierlacan** [comment]
@mcmonkey4eva Cool. Good to see the fix isn't too different [from mine](https://github.com/Stability-AI/StableSwarmUI/commit/07a40fb504b3b903efd27ebe80102268921ea272#diff-79b2ff4626e09b3cad24d8261da325ef98d04eb04d5226651033d2aefbfe6d18R281). Wasn't completely off base I guess 😅.
