### ISSUE TITLE
Missing torchvision dependency for ComfyUI backend silently fails and causes some nodes not to show up in ComfyUI Workflow Editor

### ISSUE THREAD

**Issue by lukas-kirschner** [Stability-AI/StableSwarmUI#60]
When I install all python dependencies in the ComfyUI venv at dlbackend/comfyui/venv using `pip install -r requirements.txt`, my venv is missing the `torchvision` dependency (which needs to be fixed in ComfyUI's requirements.txt file).
Unfortunately, the error is silently caught in StableSwarmUI and never appears on the console while it shows up if I run ComfyUI on its own, which makes it extremely hard to find the cause why the nodes are missing.

**Comment by mcmonkey4eva** [comment]
The error actually does show up in the normal console, swarm doesn't try to catch it at all. I tested just now and it does show.

For me trying to do that, it gives me `AssertionError: Torch not compiled with CUDA enabled` as the error.

is there any particular reason you're installing this manually vs. the automated installer?
