### ISSUE TITLE
Default Capitalization of Stable Diffusion Model Path breaks Automatic1111 integration on Linux

### ISSUE THREAD

**Issue by lukas-kirschner** [Stability-AI/StableSwarmUI#61]
The default capitalization of the Stable Diffusion Models path in StableSwarmUI is `Stable-Diffusion`, while the default capitalization of Automatic1111's models path is `Stable-diffusion`. This breaks compatibility on Linux-based systems where paths are different if they have a different capitalization.

**Comment by mcmonkey4eva** [comment]
You can name the path anything you want under Server -> Configuration in the UI.
