### ISSUE TITLE
400 - Bad Request when loading input in Load Image node

### ISSUE THREAD

**Issue by olivierlacan** [Stability-AI/StableSwarmUI#63]
Seems to come from http://localhost:7801/ComfyBackendDirect/upload/image

I know the path is fine because the Load Image node defaults to `dlbackend/Comfy/input` and I put the file in there. So there's something wonky going on.

**Comment by mcmonkey4eva** [comment]
Yeah there's something wrong in the internal comfy proxy logic

**Comment by mcmonkey4eva** [comment]
Fixed
