### ISSUE TITLE
StableSwarmUI ERROR backends  

### ISSUE THREAD

**Issue by kosetex911** [Stability-AI/StableSwarmUI#65]
I have a error with the backends i still in other computer still the same mistake.I see in the installation something was missing how i fix this? 
The stablewarn didnt detect the folder when i appear i have all archives they requested but somehow didnt work 
![image](https://github.com/Stability-AI/StableSwarmUI/assets/142453721/fac17148-fc4e-4b17-8173-6a2c5c96451e)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/142453721/9ea84188-7156-4577-a061-ad9d8d49daa3)

**Comment by mcmonkey4eva** [comment]
If this is your first installation, delete swarm and reinstall, and make sure to select the ComfyUI backend while installing.

If you're intentionally adding a custom backend, you'll have to add and configure it.

If this isn't your first install and somehow a valid backend disappeared, you'll have to explain more carefully what happened

**Comment by kosetex911** [comment]
i did but still isnt working i just make everything by default but the error persist.This cuda nvidea error appear 
![image](https://github.com/Stability-AI/StableSwarmUI/assets/142453721/37da30fa-f59d-4ad9-822d-ec96b8943e43)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/142453721/5afdc5d4-4b7c-4396-b535-0f0e138271b0)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/142453721/50f4cf8e-3e5c-4866-a772-82599345e254)
I change the route and still the problem either detect the model for some reason 
![image](https://github.com/Stability-AI/StableSwarmUI/assets/142453721/f1b8d622-b993-48c1-afa4-7048b51126d4)
the automatic installating is falling for some reason the same in the other computer i tried.the installer seem to be problematic in windows more if you dont have nvidea i have amd but in the other computer i have nvidea card.
will better if the stableSwarm is focus in make a clean an install like winrar or normal programing in this way looks bring a lot issues
