### ISSUE TITLE
About the SDXL model location of shared COMFYUI?

### ISSUE THREAD

**Issue by aimarxjg** [Stability-AI/StableSwarmUI#66]
Hello, thank you for your work. I have installed it smoothly. Since the original COMFYUI is installed on the PC, I also downloaded XL's BASE,REIF model. So the instructions follow, skipping the COMFY and model download steps. However, SwarmUI still need me to move the XL model to the SwarmUI MODEL folder in order to use it normally. I pointed the model folder path to the COMFYUI MODEL folder in the server settings. It does not work. It cannot read XL model files. Can you tell me how to solve the problem? Now I can only copy one copy of the two XL models for SWARMUI to use alone.

**Comment by mcmonkey4eva** [comment]
You can point both UIs to the same model path -- edit swarm's path in Server -> Server Configuration, if you use comfy self-start it will automatically tell comfy about swarm's path settings so you don't even need to worry about configuring that half
