### ISSUE TITLE
StableSwarm not working in Colab

### ISSUE THREAD

**Issue by dotcsv** [Stability-AI/StableSwarmUI#67]
Hi StableSwarm team,

I love using StableSwarm, but I've run into an issue on Colab. Everything installs correctly, but after loading the models, the image generation process gets stuck and doesn't advance, rendering the tool non-functional.

Thanks in advanced!

**Comment by unexpectedly** [comment]
same here

**Comment by mcmonkey4eva** [comment]
... why must GitHub close and improperly reference a commit when I'm just trying to tag it.

But -- it should be working as intended now.
