### ISSUE TITLE
How to run on M1 Ultra?

### ISSUE THREAD

**Issue by Tyresecaps** [Stability-AI/StableSwarmUI#7]
How do I run this on M1 Ultra? Will this also use the M1 GPU?

**Comment by mcmonkey4eva** [comment]
In theory, yes it should work - in practice, I'm not sure of the details. It's likely very similar to the Linux setup instructions, however I'll need an experienced mac user to help nail down the Mac installation.

**Comment by Tyresecaps** [comment]
got it working..

Install git, Python 3, and DotNET 7.
Create a virtual Python environment called "myenv".
Activate the virtual Python environment.
Clone the StableSwarmUI repository.
Change directory to the StableSwarmUI directory.
Run the following command to install the StableSwarmUI dependencies:
pip install -r requirements.txt
Run the following command to launch the StableSwarmUI server:
./launch-linux.sh

**Comment by mcmonkey4eva** [comment]
You don't need the venv or the requirements command, StableSwarmUI is written in C# not python lol

**Comment by Tyresecaps** [comment]
Lol yeah. Just needed to install the DotNET using `brew install dotnet`

**Comment by Tyresecaps** [comment]
![Screenshot 2023-07-27 at 1 55 28 AM](https://github.com/Stability-AI/StableSwarmUI/assets/110111220/8509b0a6-ec33-47f1-a429-cb22eb13b8e1)

It's installing.

**Comment by Tyresecaps** [comment]
I think a venv is needed for the comfyUI to process in the backend. Also when I am writing a prompt and clicking on generate, an error occurs saying no Model. also setting up backend. give me some time. working on it.

**Comment by mcmonkey4eva** [comment]
ComfyUI on windows standard install uses miniconda, on Linux has its own venv - in either case, you don't need to make it yourself.

For the model error, just git pull, was already fixed

**Comment by jorge-campo** [comment]
> In theory, yes it should work - in practice, I'm not sure of the details. It's likely very similar to the Linux setup instructions, however I'll need an experienced mac user to help nail down the Mac installation.

@mcmonkey4eva, the Linux script works with no changes on M1 or M2 Mac computers – I send the updated installation instructions here: https://github.com/Stability-AI/StableSwarmUI/pull/14.

Hope this helps!

**Comment by vicento** [comment]
> > In theory, yes it should work - in practice, I'm not sure of the details. It's likely very similar to the Linux setup instructions, however I'll need an experienced mac user to help nail down the Mac installation.
> 
> @mcmonkey4eva, the Linux script works with no changes on M1 or M2 Mac computers – I send the updated installation instructions here: #14.
> 
> I hope this helps!
> 
> ![Screenshot 2023-07-30 at 3 16 52@2x](https://user-images.githubusercontent.com/62282406/257053540-79d90cdc-90c1-4d5f-8370-50d57d2cc103.png)

thanks, will give it an other try
