### ISSUE TITLE
ComfyUI Load Image node results in a "400 - Bad Request"

### ISSUE THREAD

**Issue by c-dilworth** [Stability-AI/StableSwarmUI#70]
When running ComfyUI, using the Load Image node results in a "400 - Bad Request" when trying to load any image other than example.png--even after complete re-install. No errors or diagnostic info in cmd.

Running locally on Win 10 Pro with RTX 3090 FE.

**Comment by mcmonkey4eva** [comment]
This was a bug about a week ago that has already been resolved -- update and be sure to CTRL+F5.
