### ISSUE TITLE
Star button ⭐

### ISSUE THREAD

**Issue by lpinilla** [Stability-AI/StableSwarmUI#72]
Hi all,

First of all, thanks for the project!

I wanted to ask for a feature which is a "star button" ⭐ to classify good results on the UI. These results can be stored into a separate folder.

This way one could star images while some generations are in queue and then download all the "starred" images quickly, facilitating the classification process.

Thanks

**Comment by mcmonkey4eva** [comment]
Such a button already exists:

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/0dfb5664-9305-4cb0-9536-330832eb7918)

It just doesn't do anything atm as that's a planned feature not-yet-implemented
