### ISSUE TITLE
.NET install on Windows

### ISSUE THREAD

**Issue by SoftologyPro** [Stability-AI/StableSwarmUI#74]
install-windows.bat does not ensure dotnet is installed.
When starting StableSwarm you get "dotnet is not recognized" errors.
Uncommenting this line
`rem winget install Microsoft.DotNet.SDK.7 --accept-source-agreements --accept-package-agreements`
does work and does install the required DotNet.  It does still prompt for admin privs so is not 100% hands free, but StableSwarm launches fine after the install finishes.
So maybe unremark that line for the next update?

**Comment by mcmonkey4eva** [comment]
Oh, huh, that explains a few reported install issues -- the `rem` was removed a few weeks back, but I forgot to update the downloadable copy in the readme's instructions. Fixed now, thank you!
