### ISSUE TITLE
may i know how to set it to use automatic path for sharing checkpoint and lora?

### ISSUE THREAD

**Issue by satangel2222** [Stability-AI/StableSwarmUI#75]
anyone know who to do it?

**Comment by mcmonkey4eva** [comment]
Not sure what you're asking?
Paths are configured under the Server -> Server Configuration tab.
If you're using a comfy self-start backend it will automatically send your swarm-configured paths to comfy to sync them.

**Comment by satangel2222** [comment]
hi, i mean i wan to use the checkpoint in different path inside my automatic1111 stable difussion folder, eg: E:\stable-diffusion-webui\models\Stable-diffusion, but my stableswarmui is in d:stablesaarmui, i need to copy all the checkpoint from there to use it, it wasted space.

**Comment by satangel2222** [comment]
> Not sure what you're asking? Paths are configured under the Server -> Server Configuration tab. If you're using a comfy self-start backend it will automatically send your swarm-configured paths to comfy to sync them.
hi, i mean i wan to use the checkpoint in different path inside my automatic1111 stable difussion folder, eg: E:\stable-diffusion-webui\models\Stable-diffusion, but my stableswarmui is in d:stablesaarmui, i need to copy all the checkpoint from there to use it, it wasted space.

**Comment by mcmonkey4eva** [comment]
Again, server -> server configuration tab
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/31effde8-adba-4b96-8d8d-6a98054d7a7c)

Just edit the modelroot to be `E:\stable-diffusion-webui\models\` and save and restart swarmui and you'll be good

**Comment by satangel2222** [comment]
> Again, server -> server configuration tab ![image](https://user-images.githubusercontent.com/4000772/263296798-31effde8-adba-4b96-8d8d-6a98054d7a7c.png)
> 
> Just edit the modelroot to be `E:\stable-diffusion-webui\models\` and save and restart swarmui and you'll be good

many thanks ,it works.
