### ISSUE TITLE
How can i launch the SwarmUI remotely?

### ISSUE THREAD

**Issue by PancrasPZ** [Stability-AI/StableSwarmUI#77]
Hi all, 
i installed the SwarmUI on my Ubuntu server.
But how can i open it remotely?

Such as "--listen" flags with A1111 webui?

thanks

``14:25:40.147 [Init] === StableSwarmUI v0.5.4.0 Starting ===
14:25:40.180 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
14:25:40.187 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
14:25:40.187 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
14:25:40.187 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
14:25:40.187 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
14:25:40.187 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
14:25:40.209 [Init] Parsing command line...
14:25:40.220 [Init] Loading settings file...
14:25:40.228 [Init] Re-saving settings file...
14:25:40.237 [Init] Applying command line settings...
14:25:40.248 [Init] Prepping options...
14:25:40.331 [Init] Loading models list...
14:25:40.332 [Init] Loading backends...
14:25:40.332 [Init] Loading backends from file...
14:25:40.334 [Init] Prepping API...
14:25:40.334 [Init] Backend request handler loop ready...
14:25:40.335 [Warning] Unused command line flag 'help'
14:25:40.335 [Init] Prepping webserver...
14:25:40.442 [Init] Scan for web extensions...
14:25:40.444 [Init] Readying extensions for launch...
14:25:40.444 [Init] Launching server...
14:25:40.444 [Init] Starting webserver on http://localhost:7801
14:25:40.469 [Init] Program is running.
14:25:40.970 [Init] Launch web browser to install page...
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://localhost:7801/Install'

**Comment by mcmonkey4eva** [comment]
See command line docs: https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Command%20Line%20Arguments.md

you probably want `--host 0.0.0.0` here, that'd be the direct equivalent of auto's `--listen`. Might also want `--launch_mode none`

**Comment by PancrasPZ** [comment]
> 

yes, --host is what i need
thanks
