### ISSUE TITLE
Knit Picky but Frustrating 

### ISSUE THREAD

**Issue by AIMusicExperiment** [Stability-AI/StableSwarmUI#78]
Hi Alex, sorry to be "that girl" but could you move or modify the save and load workflow buttons? They cover the manager window when it is open and and make it so you can't change the filter by settings. (see picture) The world won't end if you can't as I can use the other gui for updates if need be, but I'm trying to use your GUI as much as I can!   

While i'm picking knits, it is inconvenient that the whole "Queue Prompt" box is not movable. In other GUIs you can move this around.  If you are using the preview feature so that it shows up here, half the picture is out of the window.

As always, thanks for improving the world of AI!  Stable Swarme is, "DA Bomb!" 
-Ava, the AI Music Experiment   
![button in the way](https://github.com/Stability-AI/StableSwarmUI/assets/133187055/0986bd59-a1b9-407a-887c-e0d70f4114ba)

**Comment by mcmonkey4eva** [comment]
The top-left box is overly large for you as, er, I did not test on chrome and apparently chrome is weird and makes that chonkier than it should be. That's fixed to sync with other browsers and not be overly large. From this fix alone it should no longer be in the way.

But, to be extra super sure, I have also added a little button to tell the whole menu to go away:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/e49693ba-3f42-4a8a-9893-191ce1be5a5c)

click to turn into:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/daaa2a07-74dc-4acd-8f15-d6fb1a32b4e6)

Which shouldn't ever block anything.

---

The "Queue Prompt" menu is part of ComfyUI, so you'd have to raise comments on that part of the UI there - https://github.com/comfyanonymous/ComfyUI
