### ISSUE TITLE
It would be ideal if images could be directly pasted with CTRL+V into i2i, instead of needing to first save the images locally.

### ISSUE THREAD

**Issue by xdong189** [Stability-AI/StableSwarmUI#79]
When using i2i or CONTRONET to select images, it would be preferable if it could be done similarly to WEBUI, where you can directly screenshot and paste images instead of having to save images locally first before selecting them.  This would be more convenient as it's not always feasible to save images beforehand.

**Comment by mcmonkey4eva** [comment]
You can CTRL+V directly into the prompt area now, and drag to different areas as well. The interface for image inputs is overall nicer (with thanks to pythongosssss for help with it)
