### ISSUE TITLE
Theme Color

### ISSUE THREAD

**Issue by Heckler-Dark** [Stability-AI/StableSwarmUI#81]
where can i change the color of SwarmUI..

**Comment by mcmonkey4eva** [comment]
User (top of the page) -> User Settings -> Theme (at the bottom)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/af404998-96ab-4199-9c40-8c9b575ceb18)

There's currently 3 themes built in, theoretically easy to make more via extensions. I plan to add a way to custom via UI in the future, but for now if you want to customize, you can edit the CSS https://github.com/Stability-AI/StableSwarmUI/blob/master/src/wwwroot/css/themes/dark_dreams.css

**Comment by Heckler-Dark** [comment]
> User (top of the page) -> User Settings -> Theme (at the bottom) ![image](https://user-images.githubusercontent.com/4000772/264766082-af404998-96ab-4199-9c40-8c9b575ceb18.png)
> 
> There's currently 3 themes built in, theoretically easy to make more via extensions. I plan to add a way to custom via UI in the future, but for now if you want to customize, you can edit the CSS https://github.com/Stability-AI/StableSwarmUI/blob/master/src/wwwroot/css/themes/dark_dreams.css

Thanks!
