### ISSUE TITLE
Continue generating the images after an interrumption in electricity

### ISSUE THREAD

**Issue by fabianrodrigo** [Stability-AI/StableSwarmUI#82]
I want to know if we could easily recover from an electricy issue, for example. If the server closes for example... Can I reopen the server again and continue generating images from the same queue? Should we persist the current queue on disk in realtime? Does it make sense?

Thanks a lot for your time

**Comment by mcmonkey4eva** [comment]
That's... a new one. Have you considered, uh, a _UPS_? (Uninterruptable Power Supply - hardware device that's essentially a giant battery specifically to protect computers from failure if power fails)

**Comment by mcmonkey4eva** [comment]
Spent some time considering whether to maybe implement some form of option for drive-caching of the generation queue or something, but I don't think it's going to fit as a valid feature, at least not during the current Alpha stage.
So, for now, yeah best advice is get a UPS lol. Once Swarm is out of alpha and in release phase, can reopen this and reconsider the possibility.
