### ISSUE TITLE
any way to change the batch size?

### ISSUE THREAD

**Issue by yesbroc** [Stability-AI/StableSwarmUI#84]
running this on a comfyui backend on my pc, only thing i can change about the number of mages is the number of batches

(this could be a planned feature but i cant tell)

**Comment by mcmonkey4eva** [comment]
Yes, I do have plans for batching that's a little fancier than just "add a param about it" (tldr, automatically determine batch size based on available resources, available backends, call rate, expected performance results, etc. such that you just generate as many images as you want and it automatically uses an ideal batch size without you ever having to worry about it).

That plan however is going to be delayed for a while as there's much higher priority things to do, so I've gone ahead and just added a simple batch size param, it's under the "Display Advanced Options" checkbox (imo 95% of users never have reason to touch this. It's technically a little bit faster to generate in batches, but usually not by much. You can get a better performance uplift by turning previews off lol).

Note that the seeds displayed in the UI from a comfy backend with batching will be wrong until this Comfy PR https://github.com/comfyanonymous/ComfyUI/pull/1454 is merged.

**Comment by mcmonkey4eva** [comment]
since comfy doesn't want to merge the seed fix i just went ahead and fixed it myself in swarm https://github.com/Stability-AI/StableSwarmUI/commit/8e21b9b3567d5dc352b6d4eb4f5eaa4c001508b0
