### ISSUE TITLE
Regarding the sampler feature

### ISSUE THREAD

**Issue by ahsanba-id** [Stability-AI/StableSwarmUI#85]
I apologize if I've overlooked it, but I haven't been able to locate the sampler or sampling methods option. Is it possible that this feature has not yet been implemented?

**Comment by mcmonkey4eva** [comment]
Sampler selection when using the Comfy backend is under the "Comfy" parameter group, normally at the bottom of the parameter listing.

**Comment by ahsanba-id** [comment]
Noted! Thanks.
