### ISSUE TITLE
Error ComfyUI Self-Starting using Google Colab

### ISSUE THREAD

**Issue by arthurp1** [Stability-AI/StableSwarmUI#86]
I've added ComfyUI startscript path (hosted on my Google Drive): /content/drive/MyDrive/ComfyUI/main.py

I would expect ComfyUI to boot in the same Google Colab session while still running StableSwarm is this possible?

Occasionally I get this error message, other times it just exits immediately:

```
Self-Start ComfyUI on port 7822 is loading...
[WebAPI] Error handling API request '/API/TriggerRefresh': Request input has unknown session id
 Self-Start ComfyUI on port 7822 exited.
```

**Comment by rocketpal** [comment]
+1

**Comment by mcmonkey4eva** [comment]
"unknown session id" messages are largely ignorable, it just means you restarted the server but didn't refresh the webpage.

Yes self-starting comfy should work fine in colab, as long as the path is valid.
