### ISSUE TITLE
Unable to Load LoRAs - 

### ISSUE THREAD

**Issue by journeysine1984** [Stability-AI/StableSwarmUI#87]
Hello, I'm unable to access LoRAs through the LoRAs tab.  (Nothing comes up to choose from and the folder is full of LoRAs) I've updated the Server Configuration tab but nothing is coming up under the tab.  Can someone share their Server Configuration or tell me where I need to put my LoRAs to access them? Thanks in advance.

**Comment by mcmonkey4eva** [comment]
- Under server configuration you can change or customize the path.
- By default the folder is `StableSwarmUI/Models/Lora`
- If you added new lora files while the server was running, there is a refresh button within the LoRA list you need to press
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/57500238-4911-405a-ae80-a85d058fef79)
- If you edited server settings, or just generally whenever in doubt, restart the swarm server to ensure everything applies and updates
