### ISSUE TITLE
OSError: [Errno 22] Invalid argument  -Appears after update

### ISSUE THREAD

**Issue by suede299** [Stability-AI/StableSwarmUI#95]
22:13:07.659 [Info] Self-Start ComfyUI on port 7821 unexpectedly exited (if something failed, launch with `--loglevel debug` to see why!)
22:13:07.659 [Info] Self-Start ComfyUI on port 7821 had errors before shutdown:
ComfyUI error: Traceback (most recent call last):
ComfyUI error:   File "D:\Program Files\StableSwarmUI\dlbackend\comfy\ComfyUI\main.py", line 158, in <module>
ComfyUI error:     load_extra_path_config(config_path)
ComfyUI error:   File "D:\Program Files\StableSwarmUI\dlbackend\comfy\ComfyUI\main.py", line 120, in load_extra_path_config
ComfyUI error:     with open(yaml_path, 'r') as stream:
ComfyUI error:          ^^^^^^^^^^^^^^^^^^^^
ComfyUI error: OSError: [Errno 22] Invalid argument: "'D:\\Program"
-----------------------------------------------------------------------------------
Appeared after version 0.54 update. Launching comfyui alone is fine.

**Comment by suede299** [comment]
Problems with folder paths containing spaces, all of a sudden all bat's have this problem, it's not a StableSwarmUI problem.

**Comment by suede299** [comment]
Problems with folder paths containing spaces, all of a sudden all bat's have this problem, it's not a StableSwarmUI problem.

**Comment by mcmonkey4eva** [comment]
Oops, pushed a fix (for swarm at least). But yeah spaces in paths in general is pretty iffy. Also `Program Files` paths are dangerous too, as Windows does weird things with those (though yours is on `D:` so idk what you've got going on there).
