### ISSUE TITLE
No backends present. You must configure backends in the Backends section of the Server tab before you can continue.

### ISSUE THREAD

**Issue by Crazy-CYZ** [Stability-AI/StableSwarmUI#96]
Suddenly the error appeared!

![微信截图_20230908134019](https://github.com/Stability-AI/StableSwarmUI/assets/89187812/41c1cd68-7355-446b-a6d4-eab3c0a178ba)

**Comment by mcmonkey4eva** [comment]
it, uh, looks like you don't have any backends?

Is this a new installation? If so, you may have just not selected to install one - in which case go back, reinstall and select the comfy backend.
If this is a pre-existing installation, did you edit the backend list or launch params? If so you'll have to go to the `Server` tab and add your preferred backend back. The default is comfy self start, unless you wanted a different one.
If this is a pre-existing install but you updated and that broke it ... uh, update again, might've been a temp path handling bug that's fixed? Or check if there's something weird in your `Data` dir?

**Comment by Crazy-CYZ** [comment]
> it, uh, looks like you don't have any backends?
> 
> Is this a new installation? If so, you may have just not selected to install one - in which case go back, reinstall and select the comfy backend. If this is a pre-existing installation, did you edit the backend list or launch params? If so you'll have to go to the `Server` tab and add your preferred backend back. The default is comfy self start, unless you wanted a different one. If this is a pre-existing install but you updated and that broke it ... uh, update again, might've been a temp path handling bug that's fixed? Or check if there's something weird in your `Data` dir?

I've been using it for a while now and the error popped up today!

Is this how the backend is set up? I can enter comfyui after setting it, but there are many warnings!

![微信截图_20230908141817](https://github.com/Stability-AI/StableSwarmUI/assets/89187812/49fe0d95-4100-4423-aef2-8078aa86db7d)

![微信截图_20230908141714](https://github.com/Stability-AI/StableSwarmUI/assets/89187812/0ae3ae6f-7832-4f3e-bf92-0fe7bf14ee83)

**Comment by mcmonkey4eva** [comment]
That looks correct. Those errors indicate that you have some custom nodes installed that are missing dependencies.
A recent change was made that disabled ComfyUI accidentally accessing the global python lib folder, so if those nodes worked before now you may need to reinstall them (if installing manually, make sure to use the `dlbackend/comfy/ComfyUI/python_embeded/python.exe` to install rather than global python)
