### ISSUE TITLE
After zooming in on the image, I cannot return to the operation interface.

### ISSUE THREAD

**Issue by wibur0620** [Stability-AI/StableSwarmUI#98]
https://github.com/Stability-AI/StableSwarmUI/assets/131615326/39447048-a416-4f6a-97db-bab3472ed09e

**Comment by mcmonkey4eva** [comment]
Click outside the popup (far left or right of the screen) or press Escape.

But yeah I should add a clear "Close" button somewhere so you don't get lost

**Comment by mcmonkey4eva** [comment]
there's now a button at the top right that's clearly a close button

**Comment by wibur0620** [comment]
Yes, the problem has been resolved now. thanks
